### ISSUE TITLE
Date column

### ISSUE THREAD

**Issue by csta** [awalker89/openxlsx#100]
When I have a column with type POSIXlt,

'data.frame':	74 obs. of  4 variables:
 $ Last.Day.of.Period      : POSIXlt, format: "2014-02-15" "2014-02-22" "2014-03-01" "2014-03-08" ...

I get,

R> write.xlsx(tab, "results.xlsx")
Error in is.nan(df[[i]]) : default method not implemented for type 'list'

Maybe it should be a feature request?

**Comment by awalker89** [comment]
This works for me so it must be something else

````
df <- data.frame(id = 1:10, 
                 time = as.POSIXlt(Sys.time() - 0:9), 
                 time2 = as.POSIXct(Sys.time() - 0:9)
                 )
sapply(df, class)

openXL(write.xlsx(x = df, file = tempfile()))

```

Do you have a reproducible example of this bug?

**Comment by engti** [comment]
I had the same error. I fixed it by using *as.character* on the column with the dates in them.

Hope this helps anyone else searching this issue, since this seems to be the only relevant link showing up on Google.

**Comment by AMChalkie** [comment]
I also get this error if there is a column with AsIs as the type. So to be cleaner, it would be useful if the function checked all the columns of the inputs and threw a more useful error / warning for any columns that did not meet expected criteria. 

Expected criteria: every column of every sheet is of class character/numeric/...? (Or... is not list).
