### ISSUE TITLE
Excel charting mechanism Charting

### ISSUE THREAD

**Issue by csta** [awalker89/openxlsx#101]
I would find it very helpful, and a big time saver if I could program charting in my xlsx workbooks.

Thanks,

**Comment by awalker89** [comment]
I had a look in to this and is far too complicated to do from R. If you really want Excel charts, create a template xlsx file with a chart and just use R to load the xlsx file and write over the cells you are looking at.
For example:

```
## See chart of Petal Width on "IrisSample" worksheet
file <- system.file("loadExample.xlsx", package = "openxlsx")
openXL(file)

## now load the workbook and write over the "Petal Width" values
wb <- loadWorkbook(file)
writeData(wb, sheet = "IrisSample", x = rep(10, 50), startCol = 4, startRow = 2)
openXL(wb)
```

**Comment by py9mrg** [comment]
Package writexl is a wrapper around libxlsxwriter, which allows adding charts to an Excel sheet (as opposed to an image insertion) - albeit I've never tried so I don't know how difficult it is. I wonder if you could use this package in yours to give the same functionality - but maybe it would change everything else too much? Your package does table formatting brilliantly, but no charts, the reverse is true of libxlsxwriter - it would be wonderful if the two were combined. Maybe I can do it manually by combining the two packages?

**Comment by jsavinc** [comment]
In case anyone is looking for a workaround that doesn't involve using templates, it's not too difficult to code up a Python script (using its `XlsxWriter` package) to write data to a spreadsheet and build a native excel chart from scratch. I've written up a gist here: https://gist.github.com/jsavn/cbea4b35d73cea6841489e72a221c4e9

I'm new to this so not sure how difficult/tedious managing a Python installation is though...
