### ISSUE TITLE
Automatic header in writeDataTable

### ISSUE THREAD

**Issue by tgwhite** [awalker89/openxlsx#104]
It looks like the default behavior of writeDataTable is to always include column names (even of colNames = F). Is this somehow necessary to the integration with Excel or can this feature be removed? Sometimes one wants to simply input raw data. 

Here is the bit of code I'm talking about: 

```r

  showColNames <- colNames 

  if(colNames){
    colNames <- colnames(x)
    if(any(duplicated(tolower(colNames))))
      stop("Column names of x must be case-insensitive unique.")
      
    ## zero char names are invalid
    char0 <- nchar(colNames) == 0
    if(any(char0)){
      colNames[char0] <- colnames(x)[char0] <- paste0("Column", which(char0))
    }

  }else{
    colNames <- paste0("Column", 1:ncol(x))
    names(x) <- colNames ### why is this necessary?
  }

```

**Comment by awalker89** [comment]
Use writeData().

**Comment by r2evans** [comment]
Then why go through the code and logic to suggest you will allow them to be not written? Even if you want to retain the function argument for consistency with other functions, it would be clearer in the documentation to say this, such as

```r
#' @param colNames Ignored, Excel requires column names on data tables.
```
