### ISSUE TITLE
Strange rounding problem on read.xlsx

### ISSUE THREAD

**Issue by tijoseymathew** [awalker89/openxlsx#105]
read.xlsx() on a sheet similar to this produces
![untitled](https://cloud.githubusercontent.com/assets/5517216/8846028/82a732f8-3156-11e5-9631-d2bbd274bac7.jpg)

read.xlsx(".\\Book4.xlsx")
                             some
1 1234561.1000000001
2                           3A1.2

How can I avoid the strange rounding. My actual case consists of a large table with column "some" containing about 3k levels of categorical values (i.e. factor). Conversion of 1234561.1 to 1234561.1000000001 would cause problems for me down the line.
Thanks

**Comment by awalker89** [comment]
This is how the number is being stored by Excel. openxlsx is reading it exactly how it appears.
![image](https://cloud.githubusercontent.com/assets/7400673/8892079/63eda44a-3387-11e5-804e-b8eef60a618b.png)
