### ISSUE TITLE
write.xlsx with freezePane and setColWiths

### ISSUE THREAD

**Issue by ckluss** [awalker89/openxlsx#106]
Hi,

many thanks for the greate package!

Is there an easy way to get a write.xlsx function with parameters like 
- freezeFirstRow = TRUE
- colWith = "auto"

i.e. 
write.xlsx2(..., freezefirstrow = TRUE,  colWith = "auto")

That would simplify my source ;)

Christof

**Comment by awalker89** [comment]
I will add this in in the near future. Something like this will work for you now.
```
require('openxlsx')
write.xlsx2 <- function(x, file, ...){
  wb <- write.xlsx(x = x, file = tempfile(), ...)
  freezePane(wb, sheet = 1, firstRow = TRUE)
  setColWidths(wb, sheet = 1, cols = 1:ncol(x), widths = "auto")
  saveWorkbook(wb, file = file, overwrite = TRUE)
}

write.xlsx2(x = iris, file = "test.xlsx")
openXL("test.xlsx")

```

**Comment by ckluss** [comment]
that is great, thank you very much!

**Comment by awalker89** [comment]
You can now pass freezePane parameters into write.xlsx and colWidths = "auto".
```
devtools::install_github("awalker89/openxlsx")
openXL(write.xlsx(iris, tempfile(), colWidths = "auto", firstRow = TRUE))
```
