### ISSUE TITLE
Rules in conditionalFormatting for cell values

### ISSUE THREAD

**Issue by omarbenites** [awalker89/openxlsx#107]
Hi awalker,

I want to know how can I write two rules for condtionalFormatting function (and pass to "rule" argument).
```{r, echo=FALSE}
openxlsx::conditionalFormatting(wb, sheet, cols=2,rows = 2:7, rule=rule, style = negStyle)
```

#FirstRule   0=<Var1<=10
 
![image](https://cloud.githubusercontent.com/assets/5264796/8899190/eab80f46-33f6-11e5-8341-2bfb0dfe1813.png)

#SecondRule   Var2 which only has values 1,3,5,7. 

 So i want to paint the values which are out of these values. (In the little table  4,6,9)
(I was thinking in rule like:     rule="c(1,3,5,7)"  but it's wrong)
 
![image](https://cloud.githubusercontent.com/assets/5264796/8899194/f929c132-33f6-11e5-874d-54afa18830fa.png)

Thank so much in advance.

**Comment by awalker89** [comment]
Please update to the dev version with 
```
devtools::install_github("awalker89/openxlsx")
```

Now this should work
```
df <- data.frame('var1' = -10:10, "var2" = -10:10, "var3" = -10:10)
wb <- write.xlsx(df, file = "temp.xlsx")

## between (newly added)
conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2:22, rule = c(-5, 5), type = "between")


#### ----- IN - Two ways to do this
## (write it as you would in Excel: "OR($B2=1,$B2=3,$B2=5,$B2=7)") 

values <- c(1,3,5,7)
rule <- sprintf("OR(%s)", paste(paste0("$B2=", values), collapse = ",")) 
conditionalFormatting(wb, sheet = 1, cols = 2, rows = 2:22, rule = rule)


## or just write several rules
for(val in values)
  conditionalFormatting(wb, sheet = 1, cols = 3, rows = 2:22, rule = sprintf("==%s", val))

openXL(wb)
```
![image](https://cloud.githubusercontent.com/assets/7400673/8903362/d95911b0-349a-11e5-819a-8e3fe8a2d6ea.png)

**Comment by omarbenites** [comment]
Many thanks Alex!!
