### ISSUE TITLE
Exporting NAs as blanks

### ISSUE THREAD

**Issue by skanskan** [awalker89/openxlsx#108]
I've noticed that when I export to Excel with write.xlsx(MyData, file="MyFile.xlsx") NAs appear as #NUM! when the file is opened on Excel.

I couldn't find any option to change this behaviour from openxlsx.
I've tried options such as showNA or keepNA but they don't seem to have any effect.

It would be great if write.xlsx could export NAs just as blanks.

**Comment by awalker89** [comment]
Please update to the dev version with devtools::install_github("awalker89/openxlsx")

The below should work for you.

```
require('openxlsx')
df <- head(iris)
df[2,3] <- NA
df[2,5] <- NA
df[3,5] <- NaN
openXL(write.xlsx(df, file = tempdir()))
```
![image](https://cloud.githubusercontent.com/assets/7400673/8902554/29255a9c-3495-11e5-98ce-a07c8a032688.png)





```
require('openxlsx')
df <- head(iris)
df[2,3] <- NA
df[2,5] <- NA
df[3,5] <- NaN
openXL(write.xlsx(df, file = tempdir(), keepNA = TRUE))
```

![image](https://cloud.githubusercontent.com/assets/7400673/8902609/831048aa-3495-11e5-9c68-1037fb8543ec.png)

**Comment by skanskan** [comment]
OK, thank you. That solves my problem.

**Comment by skanskan** [comment]
Hello.

I don't know why sometimes it works but sometimes produces  #NUM!
