### ISSUE TITLE
CRAN version has spurious `rm(dXML)` line

### ISSUE THREAD

**Issue by joranE** [awalker89/openxlsx#109]
FYI, when I install version 3.0.0 from CRAN openxlsx::loadWorkbook has:

    if (any(hasDrawing)) {
                for (i in 1:length(xml)) {
                    if (hasDrawing[i]) {
                      target <- unlist(lapply(drawXMLrelationship[[i]], 
                        function(x) regmatches(x, gregexpr("(?<=Target=\").*?\"", 
                          x, perl = TRUE))[[1]]))
                      target <- basename(gsub("\"$", "", target))
                      relsInd <- grepl(target, drawingRelsXML)
                      if (any(relsInd)) 
                        wb$drawings_rels[i] <- dRels[relsInd]
                      drawingInd <- grepl(target, drawingsXML)
                      if (any(drawingInd)) 
                        wb$drawings[i] <- dXML[drawingInd]
                    }
                }
                rm(dXML)
            }

and the `rm(dXML)` line is throwing a warning saying `dXML` doesn't exist. I don't see that line in the github version, so maybe that just didn't get removed before you submitted to CRAN.

**Comment by awalker89** [comment]
This has been fixed in the dev version. It will be updated on CRAN soon.
