### ISSUE TITLE
read.xlsx : logic problem when rows = 1

### ISSUE THREAD

**Issue by heywelshie** [awalker89/openxlsx#110]
There is a flaw in the IF/ELSE IF/ELSE logic at the beggining of the read.xlsx function, which causes the program to STOP when Rows == 1. 

Suggested fix, change the ELSE statement to: 
    else if (length(rows) != 1) {
      stop("rows must be a integer vector of length 1 or 2 else NULL")

**Comment by awalker89** [comment]
I believe this has already been fixed in the dev version.
