### ISSUE TITLE
openxlsx does not find RTools

### ISSUE THREAD

**Issue by RomanBi** [awalker89/openxlsx#111]
Hey, 

I installed openxlsx and it works perfectly on my desktop, however it does not work on my notebook. The versions of RTools, R and openxlsx are the same.

    saveWorkbook(wb, file = "dq", overwrite = TRUE)
    Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is     available to R.
    Try installr::install.rtools() on Windows.
    installr::install.rtools()
    No need to install Rtools - You've got the relevant version of Rtools installed
    saveWorkbook(wb, file = "dq", overwrite = TRUE)
    Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
    Try installr::install.rtools() on Windows.

There is one closed error report describing the same problem. It could be solved be deinstallation of RTools, cleaning the registry and reinstallation of RTools. However, this did not work for me.

Thanks

**Comment by awalker89** [comment]
when you do
``` system("PATH")``` do you the path to "Rtools\bin" in the result?

**Comment by RomanBi** [comment]
Oh... you are right. I forgot to set the path variable when installing Rtools, Sys.getenv("PATH") told me. Works perfectly now.

Thank you, Alex!

**Comment by samot79** [comment]
Sorry to bump this thread but I have the exact problem. I have no idea how to "set the path variable".. Can you please help me?

> saveWorkbook(wb, "writeDataExample.xlsx", overwrite = TRUE)
Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows.

> installr::install.rtools()
No need to install Rtools - You've got the relevant version of Rtools installed

**Comment by awalker89** [comment]
I've added a vignette to explain this. During the install of Rtools you need to tick the box to edit the system PATH

![image](https://cloud.githubusercontent.com/assets/7400673/12230758/99fb2202-b8a6-11e5-82e6-836159440831.png)

An alternative to this is to set it within the R session with
```
Sys.setenv("R_ZIPCMD" = "C:/Rtools/bin/zip.exe") ## path to zip.exe
```

**Comment by samot79** [comment]
Worked perfect. Thanks a lot :)

Date: Mon, 11 Jan 2016 02:03:09 -0800

**Comment by mubashirqasim** [comment]
Hi there, how about this error on Linux?

**Comment by tmamiya** [comment]
Hi Alex, I was curious also about Linux.  I think i need to set the R_ZIPCMD system variable:  however don't know where to set it to, I have installed zip, but don't know where it is in rhel.  Any help would be appreciated.

**Comment by tmamiya** [comment]
Nm figured it out.
For those out there who are looking for Rtools in linux, you can use zip as an alternative.
1. install zip into linux
2. set your path (using command below) to that location for me it was  /usr/bin/zip
Sys.setenv(R_ZIPCMD= "/usr/bin/zip")

**Comment by Anto58** [comment]
Hi Alex,
I'm having the same problem and I've read your vignette on Installation of openxlsx.  Sys.getenv("R_ZIPCMD") shows that I do indeed have a path to C:/Rtools/bin/zip.exe, but if I run shell("zip"), I get:
 
zip diagnostic: GetVolumeInformation failed
  adding: - (deflated 0%)
PK-

I think the loadWorkbook function is working as a get an object in my environment but when I try the saveWorkbook function I get the message that RomanBi reported in his/her original message.

I don't know if it is relevant that I am working on a system where I don't have administrator rights and can't alter things on the C drive.

I'm a novice in these things and any help you can provide would be much appreciated.
Thanks,  Susan

**Comment by jabowery** [comment]
I've recently had to switch from Linux to Windows and find the instructions for installing R on Windows need cleaning up.  Even though Rtools is big, it isn't really an optional component for serious use.  Rather than challenging the user with the modification of the PATH, that point in the install should offer the option of downloading the 100M Rtools package and modify the PATH at the same time.

More to the point of the present topic, telling people what they should have done during install after the fact isn't helpful.  Moreover, telling them that (in the _likely_ event they didn't pre-install Rtools _before_ installing R) such an essential component should be made available by modifying the PATH at the start of every R session -- rather than telling them how to permanently modify the PATH as though they had done so during install -- is not very helpful.

**Comment by awalker89** [comment]
@jabowery does this have anything to do with this specific R package (openxlsx)?

**Comment by jabowery** [comment]
My point is that openxlsx/issues/111 isn't an openxlsx issue at all.  It is an R installation issue and should be raised as such.
