### ISSUE TITLE
Hidden sheets?

### ISSUE THREAD

**Issue by mattrad** [awalker89/openxlsx#112]
Hi Alex, thanks for this great package!

Can we get a function to manage the visibility of sheets? Check visibility, hide, unhide, etc?

It would be nice if the default behavior of write activities did not unhide sheets.

Thanks!

Matt

**Comment by awalker89** [comment]
217dd35ccfc3da406d501eac9af351b69eb4bbd6 adds sheet visible/hidden functionality.  
see ```?sheetVisible``` for examples

**Comment by mattrad** [comment]
Amazing. Thank you!
