### ISSUE TITLE
Strange behavior reading xlsx with too many columns

### ISSUE THREAD

**Issue by gerosa** [awalker89/openxlsx#113]
I'm reading a xlsx files with more than 26 columns (i.e using AA, AB, etc columns) with the column's name in the first row. Also, I'm not defining any additional parameter:
```R
dt <- read.xlsx("file.xlsx")
```

The result data frame doesn't have the expected name in the 27th and ongoing columns (it default to X27, X28, etc) and it inserted two rows with NA values in first columns 26 columns and the original column name in remaining columns

**Comment by awalker89** [comment]
Hi do you have an example of this?

For example, this weeks fine for me
```

require('openxlsx')
options('stringsAsFactors' = FALSE)

df <- data.frame("X" = rep("A", 10))
for(i in 2:26) df <- cbind(df, LETTERS[i])
names(df) <- LETTERS
df2 <- cbind(df, apply(df, 2, function(x) paste0("A", x) ))
df2 <- cbind(df2, apply(df, 2, function(x) paste0("B", x) ))

write.xlsx(df2, "c:/users/alex/desktop/wide.xlsx")
a <- read.xlsx("c:/users/Alex/Desktop/wide.xlsx")
all.equal(a, df2)
```
![image](https://cloud.githubusercontent.com/assets/7400673/9076432/82ec9726-3b65-11e5-96f0-b6b4e6cb5151.png)

**Comment by gerosa** [comment]
I noticed the issue only happens with a xlsx file exported from another tool I'm using. If I open the fileon the a Excel for Mac 2011, it looks good. If I save it without any modification, openxlsx starts to work fine.

I have just sent to your email the problematic file.

Thanks

**Comment by awalker89** [comment]
Thanks for sending the file through.
"AA" has been converted to "[" inside the file. Maybe this is a encoding issue. Perhaps check with whatever software you created the file with.

![image](https://cloud.githubusercontent.com/assets/7400673/9132062/075b6184-3d34-11e5-802f-eb012a1b550a.png)

I'll close the issue as it appears unrelated to openxlsx.
