### ISSUE TITLE
writeData with .xlsx file with existing hyperlinks results in corrupt file

### ISSUE THREAD

**Issue by jasonelaw** [awalker89/openxlsx#114]
Writing to a .xlsx worksheet with existing hyperlinks via writeData results in a corrupted file. With a file (test.xlsx) with a single hyperlink in Sheet1 cell A1 and the code below, the resulting test2.xlsx is corrupt.

```r
wb <- loadWorkbook("test.xlsx")
writeData(wb, sheet = 'Sheet1', iris, startCol = 1, startRow = 2)
saveWorkbook(wb, file = "test2.xlsx")
```

R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_3.0.4 devtools_1.8.0 rJava_0.9-6

**Comment by awalker89** [comment]
Do you have file I can use to replicate this bug?
A basic example works fine for me.

![image](https://cloud.githubusercontent.com/assets/7400673/9101894/e121df98-3c2f-11e5-8ba1-e2f75605c6b1.png)

**Comment by jasonelaw** [comment]
Here is a test file and the output:
[test.xlsx](https://drive.google.com/file/d/0B9ne6QWuWB0LT0RTWVhvMmFBOGM/view?usp=sharing)

[test_output.xlsx](https://drive.google.com/file/d/0B9ne6QWuWB0LRi10V200MkpHYXM/view?usp=sharing)

It seems that the problem is restricted to links within the document. Sorry, I didn't narrow that down previously. I chose a simple test case, but I didn't try it with other kinds of hyperlinks.

Jason

**Comment by awalker89** [comment]
Thanks for sending the example through Jason. This update still requires proper testing.

**Comment by jasonelaw** [comment]
Thanks for the fix. Since I'm a bleeding edge kind of guy, I'll grab the latest dev and give it a shot.
