### ISSUE TITLE
Error on reading .xlsx that contains hyperlink with fragment identifier

### ISSUE THREAD

**Issue by jasonelaw** [awalker89/openxlsx#115]
loadWorkbook is failing to load a workbook that has a url with a [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier). The error occurs in this [line](https://github.com/awalker89/openxlsx/blob/master/R/loadWorkbook.R#L542), because `wb$hyperlinks[[hlinksInds[i]]]` does not contain the hyperlink with the fragment identifier, while the `target` object does. Thus, the length of the names doesn't match the length of `wb$hyperlinks`. So, the issue appears to be in the code that constructs `wb$hyperlinks`,

That's as far as I got. It looks like wb$hyperlinks is constructed in `loadWorksheets`, but I'm not sure where it goes wrong. Here's a [link](https://drive.google.com/file/d/0B9ne6QWuWB0LNFZsQ1ZxTFI3Mzg/view?usp=sharing) to a file that should file on loadWorkbook. It needs more than one hyperlink because it doesn't seem to recognize any hyperlinks if you have only a hyperlink with a fragment identifier.

**Comment by awalker89** [comment]
d761a59728af4b7f4f23a97cc64d1ee5e564dca4 is a full rebuild of hyperlink handling. This should work now.
