### ISSUE TITLE
Error in comment_list[[i]]: subscript out of bounds

### ISSUE THREAD

**Issue by r2evans** [awalker89/openxlsx#116]
Up front: I'm dealing with a large spreadsheet, and I can't give it to you (proprietary), so I'm trying to reproduce the error with smaller data.

I'm getting `Error in comment_list[[i]] : subscript out of bounds` when trying to save a worksheet. The sequence:

```r
## "out" is a large data.frame
wb <- loadWorkbook('template.xlsx')
## normally I do something more here, but in testing I do nothing
saveWorkbook(wb, file='newdata.xlsx', overwrite=TRUE)
```

So I started debugging, specifically `openxlsx:::writeCommentXML`. The first time, it completes just fine. The second time, `comments` is an empty list, causing (as you might imagine) the first line in the loop to fail:

```r
authorInd <- which(authors == comment_list[[i]]$author) - 1L
```

The workbook has five worksheets. They are all very similarly structured: the first three have graphs and some tables doing lookups to the last two worksheets, which are a pivot-table and a "medium-large" data table (only 37K rows, so not huge). There are no external data source links.

It may be related to an SO question [#31595749](http://stackoverflow.com/questions/31595749/openxlsx-number-of-worksheets) (gives the same error), but I'm not certain.

This is using a freshly-pulled version from github.

Other than getting you a MWE, is there anything else I can do to help troubleshoot this?

~bill

```r
sessionInfo()
## R version 3.2.1 (2015-06-18)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 8 x64 (build 9200)
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## attached base packages:
## [1] grid      stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## other attached packages:
## [1] openxlsx_3.0.7     ggplot2_1.0.1      gridBase_0.4-7     RColorBrewer_1.1-2
## [5] rgeos_0.3-11       sp_1.1-1           tidyr_0.2.0        dplyr_0.4.1       
## [9] r2_0.4.15         
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.0      xml2_0.1.1       magrittr_1.5     devtools_1.8.0  
##  [5] MASS_7.3-43      munsell_0.4.2    colorspace_1.2-6 lattice_0.20-33 
##  [9] stringr_1.0.0    plyr_1.8.3       tools_3.2.1      parallel_3.2.1  
## [13] gtable_0.1.2     DBI_0.3.1        git2r_0.10.1     rversions_1.0.2 
## [17] htmltools_0.2.6  lazyeval_0.1.10  assertthat_0.1   digest_0.6.8    
## [21] reshape2_1.4.1   curl_0.9.1       memoise_0.2.1    rmarkdown_0.7   
## [25] stringi_0.5-5    compiler_3.2.1   scales_0.2.5     proto_0.3-10    
```

**Comment by awalker89** [comment]
seems I was missing some brackets. Should be fixed now.

**Comment by r2evans** [comment]
Can no longer reproduce this, thanks.

**Comment by andyosborn** [comment]
Hi, I am getting this error using exactly the same code : 
wb <- loadWorkbook('template46.xlsx')
saveWorkbook(wb, file='newdata.xlsx', overwrite=TRUE)
This seems to be happen if there is a comment in the worksheet, delete the comment and it works.
[template46.xlsx](https://github.com/awalker89/openxlsx/files/339475/template46.xlsx)

**Comment by carriesmith** [comment]
@andyosborn: I was having the same problem. There's an issue if you have multiple sheets and they don't _all_ have comments. I made it work by adding one comment in an out-of-the-way cell to all the sheets that don't have a real comment. 

c1 <- createComment(comment = "", visible = FALSE)
writeComment(wb, 2, col = 100 , row = 1, comment = c1)

**Comment by andyosborn** [comment]
@carriesmith Awesome, thank you very much!

**Comment by luis-zapata-b** [comment]
I have the same problem. Is it fixed? If i have one comment in an excel, i get the error.

**Comment by andyosborn** [comment]
I put in a workaround in the end : 
# These lines workaround bug #116 "Error in comment_list[[i]]: subscript out of bounds"
# caused when a workbook has comments in some sheets but not in others
# The workaround adds a comment to every sheet in column 100

for (i in 1:length(names(wb))){ # for each sheet
  c1 <- createComment(comment = "bugworkaround", visible = FALSE)
  removeComment(wb, i, col=100, row=1, gridExpand = TRUE)
  writeComment(wb, i, col=100 , row=1, comment = c1)
}

**Comment by andyosborn** [comment]
## These lines workaround bug #116 "Error in comment_list[[i]]: subscript out of bounds"
## caused when a workbook has comments in some sheets but not in others
## The workaround adds a comment to every sheet in column 100

for (i in 1:length(names(wb))){ ## for each sheet
  c1 <- createComment(comment = "bugworkaround", visible = FALSE)
  removeComment(wb, i, col=100, row=1, gridExpand = TRUE)
  writeComment(wb, i, col=100 , row=1, comment = c1)
}

**Comment by andyosborn** [comment]
I put this workaround in when I couldn't find a fix : 
###These lines workaround bug #116 "Error in comment_list[[i]]: subscript out of bounds"
###caused when a workbook has comments in some sheets but not in others
###The workaround adds a comment to every sheet in column 100

for (i in 1:length(names(wb))){ # for each sheet
  c1 <- createComment(comment = "bugworkaround", visible = FALSE)
  removeComment(wb, i, col=100, row=1, gridExpand = TRUE)
  writeComment(wb, i, col=100 , row=1, comment = c1)
}
