### ISSUE TITLE
Page Breaks

### ISSUE THREAD

**Issue by JKigotho** [awalker89/openxlsx#117]
Hi,

This package was a gamechager for me, esp with my high usage of excel in analysis.

Is it possible to have an option for inserting pagebreaks? It would really be revolutionary.

Secondly, the number format does not appear to be customizable after saving to excel. e.g, having negative numbers in brackets, red font, with commas and 2dp. 

Finally, detectDates was working just fine for me until i updated the package(on 14/08/2015). I ran the same code but it picked the dates as character. The code is as below, with two date columns. 

open <- read.xlsx(xlsxFile = "Customer_Open_Transaction_Listing_With_Cut_Off.xlsx",sheet = 1,colNames = FALSE,startRow = 4, detectDates = TRUE)

Will appreciate any help.

Best package for R-excel users.

Thanks
Joseph

**Comment by awalker89** [comment]
992392f512d9cd688c23b597e75e784e00c2fb00 adds pageBreak functionality. see ?pageBreak.

Do you have examples I can run for your 2nd and 3rd queries?

**Comment by JKigotho** [comment]
Hi Alex,

looks like the latest version i'm able to get from the net is 3.0.0, which
doesn't have pagebreak functionality, but i see we're currently at 3.0.9.

Do you think you could assist wit a link where i can get 3.0.9?

on my second and third queries, i'll send you a file and code once i'm able
to consistently reporduce it.

Thanks and regards.

**Comment by awalker89** [comment]
Update from github with
devtools::install_github("awalker89/openxlsx")

**Comment by JKigotho** [comment]
thanks.

Had tried it severally but got an error:

> devtools::install_github("awalker89/openxlsx")
Downloading github repo awalker89/openxlsx@master
Error in curl::curl_fetch_memory(url, handle = handle) :
  Timeout was reached

Rtools is installed properly. I've seen the error being reported severally
by other users but no conclusive solution is provided.
