### ISSUE TITLE
feature request: support list columns in write.xlsx

### ISSUE THREAD

**Issue by richierocks** [awalker89/openxlsx#119]
Data frames can contain list columns:

    d <- data.frame(x = 1:10)
    d$y <- lapply(1:10, function(i) letters[1:i])
    d
    ##     x                            y
    ## 1   1                            a
    ## 2   2                         a, b
    ## 3   3                      a, b, c
    ## 4   4                   a, b, c, d
    ## 5   5                a, b, c, d, e
    ## 6   6             a, b, c, d, e, f
    ## 7   7          a, b, c, d, e, f, g
    ## 8   8       a, b, c, d, e, f, g, h
    ## 9   9    a, b, c, d, e, f, g, h, i
    ## 10 10 a, b, c, d, e, f, g, h, i, j

...but at the moment, `write.xlsx` can't write them to file.

    write.xlsx(d, "test.xlsx")
    ## Error: default method not implemented for type 'list'

It would be nice if this feature was supported.

I suggest collapsing the list columns to be character vectors (probably with a warning).  You'll need to allow an extra argument (the equivalent in `data.table::fread` is `sep2`) to specify the separating character when you collapse the lists.

**Comment by richierocks** [comment]
Does this works with nested list columns too?  You might need something like

    df[[i]] <- sapply(lapply(df[[i]], unlist), paste, collapse = list_sep)

**Comment by awalker89** [comment]
5e94abca8af9a5af17c2001b58e5daa814cd0620 should do it. Thanks.
