### ISSUE TITLE
add 'paperSize' as available option in pageSetup 

### ISSUE THREAD

**Issue by BioScientist** [awalker89/openxlsx#120]
Would it be possible to set the paperSize (for printing) when doing page setup? Looking in the code,
Line 1658 in the R/wrapper.R file, it looks like paperSize is hardcoded in as "9", while all the other options are fed in from R with "%s". 

Would it be possible to expose the paperSize option as well, or was there some strange bug that prevented that from working? Where would I find the documentation what the available options for paperSize correspond to?

Thank you for the great package btw.

**Comment by awalker89** [comment]
paperSize is now a parameter to pageSetup. 
See ?pageSetup detail for possible paperSize values.

**Comment by BioScientist** [comment]
Thank you very much!
