### ISSUE TITLE
add Print_Titles support

### ISSUE THREAD

**Issue by BioScientist** [awalker89/openxlsx#122]
Excel has a feature that lets you specify header rows and columns from a table that are to print on every page (helpful when printing large tables).

I looked into how this is actually implemented, it looks like it's not part of page setup XML tag (in spite of the menu placement within Excel). The print titles are just named regions specified in the workbook.xml with the following name: "_xlnm.Print_Titles" 

The error checking in createNamedRegion right now prevents me from creating this named region because of the "." . 

FYI, I realized that Print titles are really just named regions from here: https://github.com/jmcnamara/XlsxWriter/blob/1bdbcd912c8c8f0b2ff6ac07b9daad69414f6229/xlsxwriter/workbook.py  (just search for Print_Titles )

Eventually, this should probably be rolled up as an option into pageSetup, but having some slightly more lax error checking in the createNamedRegion function would be helpful right now...

**Comment by BioScientist** [comment]
Relevant link; here are listed some other custom named regions that implement functionality; under 
name (Defined Name):

https://msdn.microsoft.com/en-us/library/office/documentformat.openxml.spreadsheet.definedname.aspx

**Comment by awalker89** [comment]
print tiles is now implemented in pageSetup and error checking on named region names now allows "."

**Comment by BioScientist** [comment]
Thank you! This is amazing!

just a question about naming conventions, is there a reason you called it printTileCols and not printTitleCols ? I just haven’t seen it called that before.

Thank you again.

**Comment by awalker89** [comment]
No reason, just tired. Fixed now.
