### ISSUE TITLE
Literal NA imported from Excel read as missing observation (<NA>)

### ISSUE THREAD

**Issue by m-sostero** [awalker89/openxlsx#123]
When importing text cells containing the literal `NA`, these are interpreted an missing values (NA), even if the rest of the column is correctly parsed as text.
`read.xlsx` should allow to escape specific values of `NA` with an option `na.strings`.

**Comment by awalker89** [comment]
I've added the paramater "na.strings" to read.xlsx. 
see    ```  ?read.xlsx ```

**Comment by spedygiorgio** [comment]
the parameter seems missing in openxlsx 3
