### ISSUE TITLE
Is It Better to namedRegion Case Insensitive?

### ISSUE THREAD

**Issue by ab3rd** [awalker89/openxlsx#125]
Hey Alex & Guys,

I frequently use read.xlsx(xlsxFile = workBookName, namedRegion = 'XYZ'). It is a very good functionality. Thank you very much.

I just noticed namedRegion is case sensitive. In other words, if in Excel, the name is spelled as "xyz" my function call above will fail. However, Excel doesn't really distinguish named range "XYZ" v.s. "xyz". In spreadsheet formulas or VBA, both mean the same. 

Do you think this argument is better made case insensitive? Thanks.

**Comment by awalker89** [comment]
Thanks for pointing this out. I will remove the case sensitivity here.
