### ISSUE TITLE
Rcpp depends should be higher than 0.11.3

### ISSUE THREAD

**Issue by Dulani** [awalker89/openxlsx#126]
I just heard about and installed this awesome package.  Looking forward to ditching the quirky Java dependencies.  I am on a Mac using R 3.1.0 and had Rcpp version 0.11.3 installed.  I just installed the latest openxlsx version (3.0.0) and attempted to load an Excel file.  I got the following error: 
`Error in withCallingHandlers(tryCatch(evalq((function (x)  :  object '.rcpp_warning_recorder' not found`

After Googling, I learned that my Rcpp should be updated.  After installing the latest Rcpp (0.12.1), the error went away (I can now load xlsx files with openxlsx).  

If my diagnosis and solution are correct, it sounds like the Rcpp depends version should be higher than currently stated (CRAN lists the minimum version as >=0.11.1).

**Comment by awalker89** [comment]
Thanks for reporting this. I'll update the DESCRIPTION.
