### ISSUE TITLE
No data found on worksheet

### ISSUE THREAD

**Issue by rocrat** [awalker89/openxlsx#127]
I have a problem with downloaded excel files that appear to be missing some attributes.  When I try to open the file with read.xlsx I get a warning message "No data found on worksheet."  However, if I open the file with excel and then save it again I am able to open the file with no problems.  It is worthy to note that simply opening the file and saving with excel increases the size of the file by about 75kb so I assume that there are a bunch of missing attributes that excel "fills in" when saving.  Is there any work-around that does not involve opening and re-saving the file?

**Comment by awalker89** [comment]
If you can email an example xlsx file to Alexander.Walker1989@gmail.com, I'll have a look into it.

**Comment by rocrat** [comment]
Sorry, I couldn't reproduce the problem with non-confidential data.

**Comment by zh1665** [comment]
>I also encountered this problem, and I found that this error occurs when the name of the worksheet is a long string of Chinese.
@awalker89

**Comment by surmann** [comment]
@awalker89 I've got the same problem:
`> read.xlsx("data/Test.xlsx", startRow = 2)
NULL
Warnmeldung:
No data found on worksheet. `
When I just save the file without any changes the read in works. It is an export from the system LeanIX. Unfortunately, I have the same problem as @rocrat.
