### ISSUE TITLE
[feature request] Fill every merged cell

### ISSUE THREAD

**Issue by stefanfritsch** [awalker89/openxlsx#128]
Hi,

when reading worksheets where you have merged cells then `read.excel` will fill the content of the merged cells only in the first cell in R. I'd like a way to get the content in all of them.

So let's say you have fifty rows of species "virginica" and the user didn't enter "virginica" in all fifty rows but instead merged those fifty rows. I want to be able to read a data.frame where I have fifty rows of species "virginica".

While it would be easy to fill those rows in R in the example, this gets tedious and error prone if the merged cells are rectangular and not entirely regular. It would be nice to have a solution that was based on the actual Excel sheet.

Thank you,
Stefan

**Comment by BioScientist** [comment]
@stefanfritsch, see `tidyr:fill()` to do this for vertical merged cells. If you want to do this for horizontally merged column names, you may be able to do something like `names(df) %<>% as_data_frame(col_names = .) %>% fill(col_names)` as well.

**Comment by stefanfritsch** [comment]
Thanks for the reply, that's what I'm doing but that workaround works only in some cases.

It fails, e.g., for this:

![image](https://cloud.githubusercontent.com/assets/7372706/11441203/f0439600-9509-11e5-8e94-669d0178290c.png)

It fails as it is not clear which cells were merged just by looking at the NA-structure. But that is a pretty common structure for headers in my experience.

As I see it merging cells in Excel is the equivalent of writing the content in every cell (it's a visual help) so it should be imported accordingly.

Ciao,
Stefan

**Comment by awalker89** [comment]
4c9557dadd271e9f07c89bff7b4222cb72d0a17b adds this functionality - still issues when used with startRow and startCol to be resolved.

**Comment by stefanfritsch** [comment]
Sorry, I completely forgot this thread (tough not the functionality).

I just wanted to say thank you very much for your efforts :)
