### ISSUE TITLE
"zip" dependence in windows

### ISSUE THREAD

**Issue by lolow** [awalker89/openxlsx#130]
Hi, is there a way to embed the "zip" tool in openxlsx? or is there a workaround to not use Rtools. Rtools requires the administrator rights for the installation and, here, we don't have these rights.
Thanks for any helps or suggestions.

**Comment by awalker89** [comment]
CRAN doesn't allow executable files within packages so I'm not sure of how to include a zip tool with openxlsx.

A work around is to just point R to a zip.exe

```
path <- Sys.getenv("PATH")
Sys.setenv("PATH" = paste(path, "path_to_zip.exe", sep = ";"))
```

**Comment by lolow** [comment]
Thanks! I will try a work around. Do you know if there is a wrapper for the libzip library in R (read and write)? If not I should give it a try.

**Comment by awalker89** [comment]
I do not know but if you found a way of removing the zip dependency I would love to incorporate it into openxlsx.

**Comment by noamross** [comment]
It looks like https://github.com/Bioconductor-mirror/zlibbioc packages zlib for all systems, which would let you you call zlib via C everywhere.

**Comment by digEmAll** [comment]
+1 to @noamross finding
Installing RTools or configuring a zip.exe sometimes is not possible in particular in production environments... embedding zlip in the package would be great (maybe you could let an option to still use zip.exe...)
Or maybe we can think to fork zlibbioc and create a CRAN package for zip functionalities...

**Comment by mhermans** [comment]
Would the new zip-package in r-lib cover the requirements?: https://github.com/r-lib/zip

**Comment by krlmlr** [comment]
This looks solved in current master?

**Comment by AdrianHordyk** [comment]
Is it true that this is solved in the current development version? It would be great if there was a straightforward workaround to the RTools dependency

**Comment by rdatasculptor** [comment]
Had it indeed been solved in the development version?

**Comment by mhermans** [comment]
Yes, it [appears to be solved](https://github.com/awalker89/openxlsx/blob/3b3b17580fab4ccafad787f3348b18b7c10f6dff/R/WorkbookClass.R#L535) in development. 

Are there issues preventing this from being included in a release? Any testing we might help out with (CC @driesvanher)?

**Comment by rdatasculptor** [comment]
Very good news! Same here: of you need any help in testing, let is know.

**Comment by msberends** [comment]
:+1: Please release to CRAN :smiley:

**Comment by awalker89** [comment]
Released to CRAN

**Comment by hatemr** [comment]
> +1 to @noamross finding
> Installing RTools or configuring a zip.exe sometimes is not possible in particular in production environments... embedding zlib in the package would be great (maybe you could let an option to still use zip.exe...)
> Or maybe we can think to fork zlibbioc and create a CRAN package for zip functionalities...

Also having trouble in production environment. Cannot use Rtools or configure a zip.exe. @digEmAll  any advice?
