### ISSUE TITLE
Time not being written correctly

### ISSUE THREAD

**Issue by jholtman** [awalker89/openxlsx#131]
When creating a worksheet that has POSIXct time is it, it is not being written correctly.  Here is the script and the output:

    > x <- structure(list(custAcct = c("00000000041472528888", "00000000042414118178", 
    + "00000000041403841376", "00000000041476741347", "00000000000000000000", 
    + "00000000041416760654", "00000000041445146602", "00000000041432631251", 
    + "00000000041460689841", "00000000041405635487", "00000000041416772642"
    + ), tranID = 86:96, term = c(5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    + 5L, 5L), start = structure(c(1446910200, 1446910260, 1446910380, 
    + 1446910440, 1446910680, 1446910920, 1446911160, 1446911340, 1446911520, 
    + 1446912000, 1446912120), class = c("POSIXct", "POSIXt"), tzone = "UTC"), 
    +     end = structure(c(1446910200, 1446910260, 1446910380, 1446910440, 
    +     1446910680, 1446910920, 1446911160, 1446911340, 1446911520, 
    +     1446912000, 1446912120), class = c("POSIXct", "POSIXt"), tzone = "UTC"), 
    +     nItems = c(45L, 11L, 22L, 2L, 4L, 37L, 21L, 14L, 7L, 113L, 
    +     42L)), .Names = c("custAcct", "tranID", "term", "start", 
    + "end", "nItems"), row.names = 80:90, class = "data.frame")
    > 
    > 
    > # data that is being written incorrectly
    > x
                   custAcct tranID term               start                 end nItems
    80 00000000041472528888     86    5 2015-11-07 15:30:00 2015-11-07 15:30:00     45
    81 00000000042414118178     87    5 2015-11-07 15:31:00 2015-11-07 15:31:00     11
    82 00000000041403841376     88    5 2015-11-07 15:33:00 2015-11-07 15:33:00     22
    83 00000000041476741347     89    5 2015-11-07 15:34:00 2015-11-07 15:34:00      2
    84 00000000000000000000     90    5 2015-11-07 15:38:00 2015-11-07 15:38:00      4
    85 00000000041416760654     91    5 2015-11-07 15:42:00 2015-11-07 15:42:00     37
    86 00000000041445146602     92    5 2015-11-07 15:46:00 2015-11-07 15:46:00     21  << correct time
    87 00000000041432631251     93    5 2015-11-07 15:49:00 2015-11-07 15:49:00     14
    88 00000000041460689841     94    5 2015-11-07 15:52:00 2015-11-07 15:52:00      7
    89 00000000041405635487     95    5 2015-11-07 16:00:00 2015-11-07 16:00:00    113
    90 00000000041416772642     96    5 2015-11-07 16:02:00 2015-11-07 16:02:00     42
    > 
    > require(openxlsx)
    > wb <- createWorkbook()
    > addWorksheet(wb, 'x')
    > writeData(wb, 'x', x)
    > saveWorkbook(wb, '/temp/x.xlsx', overwrite = TRUE)

What gets written to the file:

![image](https://cloud.githubusercontent.com/assets/131205/11044865/5e5f726a-86f2-11e5-839e-58bac42989cc.png)

**Comment by awalker89** [comment]
Thanks for this.

499dd33408c8d1c9e652bee07ace7d557e308140 should fix this.

Completely wrong dates was due to incorrect timezone specification when convert POSIXct to a float.
Slightly wrong times was due to rounding on this conversion when converting to character which appears to be caused by options("digits")

Let me know if this hasn't fixed your issue.

**Comment by jholtman** [comment]
Alex,

Thanks, that seems to have cleared up the problem that I was having.


Jim Holtman
Data Munger Guru

What is the problem that you are trying to solve?
Tell me what you want to do, not how you want to do it.
