### ISSUE TITLE
write.xlsx with Excel column data types

### ISSUE THREAD

**Issue by ckluss** [awalker89/openxlsx#138]
Hi

thank you again for this package that simplifying my daily work

would it be possible to pre-format the Excel columns 
(e.g. data type numeric, display only 1 or 2 digits; data type simple date; ...)

Best wishes
Christof

**Comment by awalker89** [comment]
The formatting vignette has all the formatting features available.
https://cran.r-project.org/web/packages/openxlsx/vignettes/formatting.pdf
