### ISSUE TITLE
write.xlsx() subtracts a day from dates

### ISSUE THREAD

**Issue by v1nsai** [awalker89/openxlsx#140]
write.xlsx() seems to subtract a day from records

     > date
        Date
     1 2009-08-01
     2 2008-08-01
     3 2013-04-12
     4 2011-07-01
     5 2013-09-06
     6 2012-04-19
     > write.xlsx(date, "Date.xlsx")

The resulting table looks like this

     Date
    2009/07/31 19:00:00
    2008/07/31 19:00:00
    2013/04/11 19:00:00
    2011/06/30 19:00:00
    2013/09/05 19:00:00
    2012/04/18 19:00:00

**Comment by awalker89** [comment]
Are you using the dev version 3.0.27?

**Comment by v1nsai** [comment]
I realize what I was doing.  I was using read_excel() from the readxl
library to read the xlsx into my workspace, then write.xlsx() from openxlsx
to write it.  There must have been some conversion problems somewhere.
Using only the openxlsx library solved the problem.

Sorry, I should have slept on it before posting a bug report.

**Comment by awalker89** [comment]
No problem. I'll still have a look in to it - bit weird it's doing that.
