### ISSUE TITLE
How to install on portable R using unzip()

### ISSUE THREAD

**Issue by goodllama** [awalker89/openxlsx#141]
Is there a way to install using unzip() without access to Rtools.  I can use openxlsx  but can't write uncorrupted files to "file.xlsx".  Thanks Jan

**Comment by awalker89** [comment]
Something like this should work - just tell R inside the session where to find zip

```
Sys.setenv("R_ZIPCMD" = "C:/Rtools/bin/zip.exe") ## path to zip.exe

require('openxlsx')
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
saveWorkbook(wb, "test.xlsx")

```
