### ISSUE TITLE
writeDataTable() with a df containing lists

### ISSUE THREAD

**Issue by abelew** [awalker89/openxlsx#142]
Greetings,
  If one calls
openxlsx::writeDataTable(wb, sheet, x=data, ...) where one column of data contains a list, line 708 of WorkbookClass.R throws an error when the is.nan() and is.infinite() function calls attempt to run on lists.
One therefore receives:
Error in is.nan(df[[i]]) : default method not implemented for type 'list'

A cheesy method to avoid this is to wrap them as suggested on :
http://stackoverflow.com/questions/18142117/how-to-replace-nan-value-with-zero-in-a-huge-data-frame

Thus I added:
is.nan.data.frame <- function(x) {
do.call(cbind, lapply(x, is.nan))
}
is.infinite.data.frame <- function(x) {
do.call(cbind, lapply(x, is.infinite))
} 

and changed the return to: 
is.nan.data.frame(df[[i]] | is.infinite.data.frame(df[[i]])

If you are very sensibly wondering why one's data frame would be so stupid, I used rtracklayer to extract annotation information from a gff file and wanted to drop that into a xls file to give to someone who prefers excel.  The resulting data frame from rtracklayer has an alias column which is in turn a series of lists/data frames.

Therefore, alternate solutions include deparsing the offending column into an as.character(), or to add another case in the if() statement to add !"data.frame" %in% class(df[[i]].

  I tried all three and it seems to me the the wrapping is the nicest, but they all work.

 I hope you are doing well.

**Comment by awalker89** [comment]
This should work in the dev version. If the below doesn't work for you please let me know.
```
d <- data.frame(x = 1:10)
d$y <- lapply(1:10, function(i) letters[1:i])
d

wb <- createWorkbook()
addWorksheet(wb, "Sheet1")

writeData(wb, sheet = 1, x = d, sep = ",")
writeDataTable(wb, sheet = 1, x = d, sep = "|", startCol = 5)
openXL(wb)

```
