### ISSUE TITLE
zero values smaller than 10E-200

### ISSUE THREAD

**Issue by splaisan** [awalker89/openxlsx#144]
I have issues with very small scientific numbers which get converted by Excel with wrong decimal separator to 0.00000000000 instead of 0,00.
Is there a way to filter numerical values during export and convert all values smaller than a given bare minimum (10E-200 in my case would do) to 0 before writing to excel?

Thanks for the great package
Stephane

PS: my problem is illustrated at http://stackoverflow.com/questions/34974914/r-package-openxlsx-floating-point-arithmetic-may-give-inaccurate-results

**Comment by splaisan** [comment]
found the issue already existed but your solution did not work out (see original issue (https://github.com/awalker89/openxlsx/issues/132)

Sorry for duplo

**Comment by awalker89** [comment]
closing as duplicate.
