### ISSUE TITLE
Rounding error when importing dates (+ detectDates fails)

### ISSUE THREAD

**Issue by czietz** [awalker89/openxlsx#146]
When reading the attached test case with ...
`x <- openxlsx::read.xlsx("./date.xlsx", 1, detectDates = T)`
... the column _Datum_ is not detected as date but read as numeric value. Then, using ...
`openxlsx::convertToDateTime(x$Datum)`
... a rounding error occurs. The date in the Excel file is "2016-01-24 15:39:00", convertToDateTime however returns "2016-01-24 15:39:**08**".

[date.xlsx](https://github.com/awalker89/openxlsx/files/113932/date.xlsx)

**Comment by czietz** [comment]
Further digging into the code of convertToDateTime shows that the error lies in the line
`y <- paste(hrs, mins, secs, sep = ":")`. hrs, mins and secs themselves are calculated correctly. 

For the test case mentioned above:

\> hrs
[1] 15
\> mins
[1] 39
\> secs
[1] 8.38190317153931e-08
\> paste(hrs, mins, secs, sep = ":")
[1] "15:39:8.38190317153931e-08"

I suppose this can be fixed by using sprintf instead of paste or by not converting the time into a string in the first place.

**Comment by awalker89** [comment]
The conversion is now fixed.
![image](https://cloud.githubusercontent.com/assets/7400673/14231217/53796d12-f9be-11e5-91b7-103bef1c9f63.png)

**Comment by awalker89** [comment]
read.xlsx doesn't detect and convert datetimes yet. Maybe will add the functionality in the future.

**Comment by czietz** [comment]
Thanks for the fix. However, I wonder if the conversion to a string is necessary in the first place. I wrote the following implementation of convertToDateTime to import my Excel sheets:

`myconvertToDateTime <- function (x, origin = "1900-01-01", ...) 
{
  rem <- x%%1
  date <- as.POSIXlt(openxlsx::convertToDate(x, origin))
  attr(date,"tzone") <- list(...)$tz
  fraction <- 24 * rem
  date$hour <- floor(fraction)
  minFrac <- (fraction - date$hour) * 60
  date$min <- floor(minFrac)
  date$sec <- round((minFrac - date$min) * 60)
  
  return(as.POSIXct(date))
}`
