### ISSUE TITLE
Round formula does not work

### ISSUE THREAD

**Issue by Grrrusti** [awalker89/openxlsx#147]
Hi, 

SUM or AVERAGE formula in this function works perfectly, but not with ROUND.
In R it does not show any error, but when opening excel file it shows that it found some problem with content and removes the ROUND formula from Excel file.

`writeFormula(wb, "sheet1",paste0("ROUND(A",1,";2)"))`

**Comment by awalker89** [comment]
You just need to use a comma instead of a semicolon

This will work
```
wb <- createWorkbook()
addWorksheet(wb, "sheet1")
writeData(wb, sheet = "sheet1", x = 12.345234)
writeFormula(wb, sheet = "sheet1", x = paste0("ROUND(A",1,",2)"), startCol = 2)
openXL(wb)
```
