### ISSUE TITLE
saveWorkbook does not commit workbook changes

### ISSUE THREAD

**Issue by rappster** [awalker89/openxlsx#148]
Hi Alex,

and first of: kudos for having written `openxlsx`! It looks very promising for freeing me from "manual Excel hell" which I'll be forever thankful for once I get everything working like I need it ;-)

Unfortunately, I'm having trouble with changes to a workbook actually being "committed" once I'm done.
It seems to mee like calling`saveWorkbook()` at the very end of my changes does not fully commit everything to the file which results in changes being lost unless files are opened and saved in Excel **manually** before continuing to manipulate them via calling your functions.

The reasons I believe that are twofold:

1. When saving via `saveWorkbook()`, opening the file in Excel (2016), not changing anything and closing the file again, Excel fires its "Save file" dialogue:

    ![excel_1](https://cloud.githubusercontent.com/assets/1205659/12800000/78de5024-cad2-11e5-9927-33915c10daf3.png)

    (Sorry for the German, I don't have an English version of Excel at my disposal)

2. When saving via `saveWorkbook()`, **NOT** opening the file in Excel but continuing with the next "change and save" cycle, the following warning is thrown:

    ```
Warning message:
In rm(dXML) : object 'dXML' not found
```

As I'm also experiencing the same problems when using [`XLConnect`](https://github.com/miraisolutions/xlconnect), I'm assuming it has something to do with the Java-API (?) or something related to the "underlying technology" for manipulating Excel files rather than something specific in your package.

Below you'll find a small example that illustrates the issue

# Example

```
library(openxlsx)

addExcelFormulaToColumn <- function(path, name, sheet = "Sheet 1") {
  if (!file.exists(path)) {
    wb <- createWorkbook()
    addWorksheet(wb, sheet = sheet)
    dat <- data.frame(a = 1:3, b = 11:13)
    writeData(wb, sheet = sheet, x = dat)
  } else {
    wb <- openxlsx::loadWorkbook(path)
    dat <- readWorkbook(path, sheet = sheet)
  }

  forms <- sapply((1:nrow(dat)) + 1, function(ii) {
    cols <- int2col(1:ncol(dat))
    paste0("SUM(", cols[1], ii, ":", cols[length(cols)], ii, ")")
  })

  class(forms) <- c(class(forms), "formula")
  writeData(wb, sheet = sheet, x = forms, startRow = 2, startCol = ncol(dat) + 1)
  writeData(wb, sheet = sheet, x = name, startRow = 1, startCol = ncol(dat) + 1)
  openxlsx::saveWorkbook(wb, path, overwrite = TRUE)
}

path <- "openxlsx-test-column.xlsx"
addExcelFormulaToColumn(path, "sum_1")

## Open the Excel file and hit "Save" before proceeding
addExcelFormulaToColumn(path, "sum_2")

## Do NOT open the Excel file but simply proceed
addExcelFormulaToColumn(path, "sum_3")
```
# System info

1. Excel: [Excel 2016](https://support.office.com/en-us/article/What-s-new-in-Excel-2016-for-Windows-5fdb9208-ff33-45b6-9e08-1f5cdb3a6c73?ui=en-US&rs=en-US&ad=US)

2. Java: [jre1.8.0_66](http://www.msiwisdom.com/articles/oracle/476-java-runtime-environment-version-8-0-update-66)
3. Session info

    ```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] XLConnect_0.2-11    XLConnectJars_0.2-9 openxlsx_3.0.0     

loaded via a namespace (and not attached):
[1] tools_3.2.3    Rcpp_0.12.3    memoise_0.2.1  digest_0.6.9   rJava_0.9-8   
[6] devtools_1.9.1
```

**Comment by rappster** [comment]
I did try the latest dev version of `openxlsx` as well. The warning isn't thrown anymore, but the changes are still lost unless save manually.

**Comment by rappster** [comment]
I did try the latest dev version of `openxlsx` as well. The warning isn't thrown anymore, but the changes are still lost unless saved manually.

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_3.1.6

loaded via a namespace (and not attached):
 [1] httr_1.0.0     R6_2.1.1       magrittr_1.5   tools_3.2.3    curl_0.9.4    
 [6] Rcpp_0.12.3    memoise_0.2.1  stringi_1.0-1  knitr_1.12.1   stringr_1.0.0 
[11] digest_0.6.9   devtools_1.9.1
```

**Comment by awalker89** [comment]
Thanks for the detailed bug report - this should be fixed now. 
Please update to the dev version with 
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by rappster** [comment]
Thanks, I'll check it out.

**Comment by nicolairj** [comment]
Dear Alexander,

First of all, I wanted to thank you for the openxlsx package! It saves a lot of time dealing with tedious Excel.

I also wanted to bring to your attention one issue with the package. The issue has been brought up in previous posts:

https://stackoverflow.com/questions/52952207/evaluate-excel-file-without-opening-saving/58120879#58120879 

Although here you commented about the issue being resolved, I have been testing it, and the bug does not seem to be resolved in my case. Here is what I am running:

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister
 Normal:  Inversion
 Sample:  Rounding
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
[1] openxlsx_4.1.0.1

loaded via a namespace (and not attached):
[1] compiler_3.6.1  tools_3.6.1     rstudioapi_0.10 Rcpp_1.0.2      zip_2.0.4

Also, I have a workaround for the issue, but it would be great if it wasn't necessary. The solution is executing the following function right after you use saveWorkbook() and before you read data from the workbook you just saved:

calculate_wb_fn <- function(excel_file_directory, excel_file_name)
{
  macro_calculate_wb <- file(paste0(excel_file_directory,"macro_calculate_wb.vbs") )
  writeLines(c("Const xlVisible = -1",
               "Dim objExcel",
               "Dim objWb",
               "Dim objws",
               "Dim strFileName",
               paste0("strFileName = \"",gsub("/","\\\\",excel_file_directory),excel_file_name,"\""),
               "On Error Resume Next",
               "Set objExcel = CreateObject(\"excel.application\")",
               "Set objWb = objExcel.Workbooks.Open(strFileName)",
               "objExcel.DisplayAlerts = False",
               "objWb.Save",
               "objWb.Close SaveChanges=True",
               "objExcel.Close",
               "objExcel.Quit",
               "set objWb = Nothing",
               "set objExcel = Nothing",
               "On Error GoTo 0")
             , macro_calculate_wb)

  close(macro_calculate_wb)


  file <- normalizePath(paste0(excel_file_directory,"macro_calculate_wb.vbs") )


  shell(shQuote(string = file), wait = T)

  file.remove(paste0(excel_file_directory,"macro_calculate_wb.vbs"))
}

The function creates a file with a VBscript that opens the file, saves it (i.e., also calculates it), and closes it. Then it executes the script, and then it deletes the script.

Thank you so much again for the package, and for your attention and time.

Best,
Nicolas
