### ISSUE TITLE
No documentation for creating internal hyperlinks

### ISSUE THREAD

**Issue by timyoungren** [awalker89/openxlsx#151]
I see that you did some work described as "Hyperlink rebuild to handle internal hyperlinks", but I am unable to find any documentation on how to create internal hyperlinks. Can this be added?

Thank you. And thank you for an excellent tool.

**Comment by GeraldCNelson** [comment]
I use the function below to create a link from a metadata worksheet to another worksheet in the same workbook. sheetName is the name of the sheet (already created). shtDesc is a text string that describes the contents of the other worksheet and which has the hyperlink. Hope this is useful.

f.hyperlink <- function(sheetName, shtDesc) {
  #here's what I need a link to look like =HYPERLINK("#test!A1","testDescription")
  part1 <- '=HYPERLINK("#'
  part2 <- paste(sheetName, "!A1", '",', sep = "")
  part3 <- paste('"', shtDesc, '")', sep = "")
  hlink <- paste(part1, part2, part3, sep = "")
  return(hlink)
}


Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by timyoungren** [comment]
Gerald,
Thank you. That did not directly work for me, but it helped me along. I got it working with some modifications.

I tweaked your code to this:

f.hyperlink <- function(filename, sheetName, shtDesc) {
  #here's what I need a link to look like =HYPERLINK("[filename.xlsx]sheetName!A1","shtDesc")
  hlink <- paste0('=hyperlink("[', filename, '.xlsx]', sheetName, '!A1', '", "', shtDesc, '")') 
  return(hlink)
}

And for reference, in case anyone else might find it helpful, to create the link, this code is paired with:

v <- f.hyperlink(filename, sheetName, linkText)
class(v) <- c(class(v), 'formula')
writeData(wb, sheet = sheetName, x = v, xy = c(1, 1))

Thanks again,
Tim Youngren

**Comment by audiolion** [comment]
should we just create a function for this and merge with the package code?

**Comment by GeraldCNelson** [comment]
Seems like a good idea to me.


Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by awalker89** [comment]
Thanks for the functions. I've generalised this to the below code - let me know if this does everything you need it to and I will commit the code.
Alex.
```
wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
addWorksheet(wb, "Sheet2")
addWorksheet(wb, "Sheet 3")
writeData(wb, 3, iris)



makeHyperlinkString <- function(sheet, row = 1, col = 1, text = NULL, file = NULL){
  
  cell <- paste0(int2col(col), row)
  if(!is.null(file)){
    dest <- sprintf("[%s]'%s'!%s", file, sheet, cell)
  }else{
    dest <- sprintf("#'%s'!%s", sheet, cell)  
  }
  
  if(is.null(text)){
    str <- sprintf("=HYPERLINK(\"%s\")", dest)
  }else{
    str <- sprintf("=HYPERLINK(\"%s\", \"%s\")", dest, text)
  }
  
  return(str)
}


## External Hyperlink
x <- c("http://www.google.com", "http://www.google.com.au")
names(x) <- c("google", "google Aus")
class(x) <- "hyperlink"
writeData(wb, sheet = 1, x = x, startCol = 10)


## Internal Hyperlink - create hyperlink formula
writeFormula(wb, "Sheet1", x = '=HYPERLINK("#Sheet2!B3", "Text to Display - Link to Sheet2")', startCol = 3)

## Internal - No text to display
writeFormula(wb, "Sheet1", startRow = 1, x = makeHyperlinkString(sheet = "Sheet 3", row = 1, col = 2))

## Internal - Text to display
writeFormula(wb, "Sheet1", startRow = 2, x = makeHyperlinkString(sheet = "Sheet 3", row = 1, col = 2, text = "Link to Sheet 3"))

## Link to file - No text to display
writeFormula(wb, "Sheet1", startRow = 4, x = makeHyperlinkString(sheet = "testing", row = 3, col = 10, file = system.file("loadExample.xlsx", package = "openxlsx")))

## Link to file - Text to display
writeFormula(wb, "Sheet1", startRow = 3, x = makeHyperlinkString(sheet = "testing", row = 3, col = 10, file = system.file("loadExample.xlsx", package = "openxlsx"), text = "Link to File."))


openXL(wb)

```

**Comment by audiolion** [comment]
looks good! was gonna try to help out and write it for ya but I am unfamiliar with writing code for Rcpp, helps to see how you would implement it though!

**Comment by awalker89** [comment]
makeHyperlinkString() added to package with documentation.
