### ISSUE TITLE
Error in tolower(sharedStrings) : invalid input ... in 'utf8towcs'

### ISSUE THREAD

**Issue by alberto-martin** [awalker89/openxlsx#153]
Hello, I'm getting the following error when I try to load my workbook (it contains special characters and non-latin characters)

> > citations <- read.xlsx('citations_to_import.xlsx', sheet = 'citations')
> > Error in tolower(sharedStrings) : 
> >   invalid input 'æ¤ç”°çœŸä¸€éƒŽï¼Œ èŠæ± å¥æ¬¡éƒŽï¼Œ ä¸­å±±é›…æ–‡ï¼Œ ð¡ˆ½æ©‹å“ä¹Ÿ' in 'utf8towcs'

I'm using R 3.2.3 and openxlsx 3.0.0

**Comment by alberto-martin** [comment]
In other machine, with R 3.1.1 and openxlsx 2.2.1 it didn't throw that error :/ ¿?

**Comment by awalker89** [comment]
Are you able to send me an example xlsx file showing this error? And which version of openxlsx are you using?. Please update to the most recent dev version if you are not using it.

**Comment by sittingdown1000** [comment]
Hi awalker89,

I am facing the same issue as well. Able to advise? THANKS!

Original file was saved as .tsv in UTF-8. When opened with excel, it is able to display the special characters (chinese).
**"Rachel Au不用找了，不是我要的😔"**
I saved the file as .xlsx with UTF-8 encoding.

Then i imported it with the following:
**library(openxlsx)
setwd("C:/Users/muscleman/Desktop/SamplingTest")

# Retrieve the data
readpopulation = function() {
  population_dat = read.xlsx("excelFileSavedInUTF8.xlsx",
                             sheet = "Sheet1",
                             colNames = TRUE)
  population_dat[population_dat == ""] = NA
  return(population_dat)
}

population_dat = readpopulation()**

After which, it outputs the following error:
**Error in tolower(sharedStrings) : 
  invalid input 'Rachel Auä¸ç”¨æ‰¾äº†ï¼Œä¸æ˜¯æˆ‘è¦çš„ðŸ˜”' in 'utf8towcs'
Called from: tolower(sharedStrings)**

It also auto outputs the following function: tolower (namespace:base)
**function (x) 
{
	if (!is.character(x)) 
		x <- as.character(x)
	.Internal(tolower(x))
}**

R version: 3.3.3
RStudio version: 1.0.136
openxlsx version: 4.0.17

[excelFileSavedInUTF8.xlsx](https://github.com/awalker89/openxlsx/files/1469389/excelFileSavedInUTF8.xlsx)
