### ISSUE TITLE
write.xlsx() to add sheets to workbook

### ISSUE THREAD

**Issue by enricoferrero** [awalker89/openxlsx#157]
Hi,

More a question than an issue. I'm currently using xlsx but considering to migrate to openxlsx.

Something I do quite often is generate some results and write to an XLSX file, then generate some other results and write these as another sheet in the same XLSX file. I understand the preferred way to do this with openxlsx is to create a list and then use write.xlsx() on the list, i.e.:

```
data(iris)
data(mtcars)
write.xlsx(list(iris=iris, mtcars=mtcars), "file.xlsx")
```

However I find this impractical in many occasions. Is there any way I can do something like this and append the second data.frame as  a second sheet to the same XLSX file?

```
data(iris)
write.xlsx(iris, "file.xlsx", sheetName="iris")
data(mtcars)
write.xlsx(mtcars, "file.xlsx", sheetName="mtcars")
```

Thanks.

**Comment by GeraldCNelson** [comment]
If I understand your question, this is quite easy with openxlsx. You create a workbook object in your script, create new worksheet objects and write data to them, then write the workbook object out  to your hard drive. 

I have written some functions that simplify this process a bit for a project I’m working on. I have attached the R file. Hopefully it will give you some tips on how to move forward.

Jerry


Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by enricoferrero** [comment]
Thank you. I don't see any attachment though, can you please share the code here on GitHub?

**Comment by GeraldCNelson** [comment]
It’s possible that github doesn’t like attachments. I have copied the code below. 

# Intro -------------------------------------------------------------------
#This script contains functions to generate spreadsheets of the nutrition requirements results

#Copyright (C) 2015 Gerald C. Nelson, except where noted

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details at http://www.gnu.org/licenses/.

source("setup.R")#create some common styles
numStyle <- createStyle(numFmt = "0.00")
numStyle3 <- createStyle(numFmt = "0.000")
shareStyle <- createStyle(numFmt = "0.0%")
textStyle <-
  createStyle(
    fontName = NULL,
    fontSize = NULL,
    fontColour = NULL,
    numFmt = "GENERAL",
    border = NULL,
    borderColour = getOption("openxlsx.borderColour", "black"),
    borderStyle = getOption("openxlsx.borderStyle", "thin"),
    bgFill = NULL,
    fgFill = NULL,
    halign = "left",
    valign = NULL,
    textDecoration = NULL,
    wrapText = FALSE,
    textRotation = NULL
  )

#function to create the first, common worksheets in the results workbook
f.createGeneralWorksheet <- function() {
  wbGeneral <- createWorkbook()
  
  #create a worksheet with info on creator, date, model version, etc.
  creationInfo <-
    ("Information on creator, date, model version, etc.")
  creationInfo <- rbind(creationInfo, paste("Creator:", userName))
  creationInfo <-
    rbind(creationInfo, paste("Date of file creation:", Sys.Date()))
  creationInfo <-
    rbind(creationInfo, paste("IMPACT data:", IMPACTfileName))
  creationInfo <-
    rbind(creationInfo, paste("Nutrient data:", nutrientFileName))
  creationInfo <-
    rbind(creationInfo,
          paste("Nutrient requirements data:", EARFileName))
  creationInfo <-
    rbind(creationInfo, paste("SSP data:", SSPdataZipFileName))
  addWorksheet(wbGeneral, sheetName = "creation_Info")
  writeData(
    wbGeneral,
    creationInfo,
    sheet = "creation_Info",
    startRow = 1,
    startCol = 1,
    rowNames = FALSE,
    colNames = FALSE
  )
  
  #Set up a dataframe to collect common worksheet names and descriptions.
  wbInfoGeneral <-
    data.frame(
      sheet_Name = character(),
      sheet_Desc = character(),
      stringsAsFactors = FALSE
    )
  
  wbInfoGeneral[1,] <-
    c("Sheet names", "Description of sheet contents")
  wbInfoGeneral[(nrow(wbInfoGeneral) + 1),] <-
    c("creation_Info",
      "Information on creator, date, model version, etc.")
  
  #create a worksheet with info on the regions
  addWorksheet(wbGeneral, sheetName = "metadataRegions")
  wbInfoGeneral[(nrow(wbInfoGeneral) + 1),] <-
    c("metadataRegions", "Region metadata")
  writeData(
    wbGeneral,
    IMPACTregions,
    sheet = "metadataRegions",
    startRow = 1,
    startCol = 1,
    rowNames = FALSE
  )
  addStyle(
    wbGeneral,
    sheet = "metadataRegions",
    style = textStyle,
    rows = 1:nrow(IMPACTregions),
    cols = 1:ncol(IMPACTregions),
    gridExpand = TRUE
  )
  
  #create a worksheet with info on the nutrient sources
  req.metadata <-
    read.xlsx(EARFileName, sheet = 1, colNames = FALSE)
  addWorksheet(wbGeneral, sheetName = "MetaDataNutrnts")
  writeData(
    wbGeneral,
    req.metadata,
    sheet = "MetaDataNutrnts",
    startRow = 1,
    startCol = 1,
    rowNames = FALSE,
    colNames = FALSE
  )
  wbInfoGeneral[(nrow(wbInfoGeneral) + 1),] <-
    c("MetaDataNutrnts",
      "Information about the requirements sources")
  
  
  #create a worksheet with info on the commodities and nutrients
  addWorksheet(wbGeneral, sheetName = "IMPACTCommdlist")
  #commodityNames <- cbind(nutrients[c("Name","IMPACT_code")])
  writeData(
    wbGeneral,
    nutrients,
    sheet = "IMPACTCommdlist",
    startRow = 1,
    startCol = 1
  )
  addStyle(
    wbGeneral,
    sheet = "IMPACTCommdlist",
    style = numStyle,
    rows = 1:nrow(nutrients),
    cols = 2:ncol(eval(parse(text = reqList[i]))),
    gridExpand = TRUE
  )
  
  wbInfoGeneral[(nrow(wbInfoGeneral) + 1),] <-
    c("IMPACTCommdList",
      "IMPACT commodities and their nutrient content")
  
  tmp <- list(wbGeneral, wbInfoGeneral)
  return(tmp)
}

f.hyperlink <- function(sheetName, shtDesc) {
  #here's what I need a link to look like =HYPERLINK("#test!A1","testDescription")
  part1 <- '=HYPERLINK("#'
  part2 <- paste(sheetName, "!A1", '",', sep = "")
  part3 <- paste('"', shtDesc, '")', sep = "")
  hlink <- paste(part1, part2, part3, sep = "")
  return(hlink)
}

f.finalizeWB <- function(wb, wbInf, file.name) {
  #add sheet with info about each of the worksheets
  #the first column is written using writeFormula
  addWorksheet(wb, sheetName = "sheetInfo")
  for (i in 1:nrow(wbInf)) {
    writeFormula(
      wb,
      "sheetInfo",
      x = f.hyperlink(wbInf[i, 1], wbInf[i, 1]),
      startCol = 1,
      startRow = i
    )
  }
  
  writeData(
    wb,
    wbInf[, 2],
    sheet = "sheetInfo",
    startRow = 1,
    startCol = 2,
    rowNames = FALSE,
    colNames = FALSE
  )
  addStyle(
    wb,
    sheet = "sheetInfo",
    style = textStyle,
    rows = 1:nrow(wbInf),
    cols = 1:(ncol(wbInf)),
    gridExpand = TRUE
  )
  setColWidths(wb,
               sheet = "sheetInfo",
               cols = 1:2,
               widths = 20)
  
  #move sheetInfo worksheet from the last to the first
  temp <- 2:length(names(wb)) - 1
  temp <- c(length(names(wb)), temp)
  worksheetOrder(wb) <- temp
  xcelOutFileName <-
    paste("results/", file.name, Sys.Date(), ".xlsx", sep = "")
  
  saveWorkbook(wb, xcelOutFileName, overwrite = TRUE)
}

f.write.incShare.sheet <- function(incShare, wb) {
  #incShare contains rows for one scenario, three budget calcs based on Pw, Pc, and Pcon, all regions and all years
  #wb is the spreadsheet file set up in workSheetCreation.R
  #wbInfo is used to create the metadata sheet
  shtName <- paste("IncShare_", unique(incShare$scenario), sep = "")
  shtName <- substr(shtName, 1, 31) #sheetnames in xls must be <= 31
  incShare.wide <-
    spread(incShare[, c("region", "year", "Pcon")], year, Pcon)
  addWorksheet(wb, sheetName = shtName)
  writeData(
    wb,
    incShare.wide,
    sheet = shtName,
    startRow = 1,
    startCol = 1,
    rowNames = FALSE,
    colNames = TRUE
  )
  return(c(
    shtName,
    paste(
      "Expenditure on IMPACT commodities as a share to per capita GDP in scenario",
      (unique(incShare$scenario)),
      sep = " "
    )
  ))
}

f.write.nut.sheet <- function(nutdf, wb) {
  #nutdf contains rows for one scenario, food.group,code, and nutrient, all regions and all years
  #wb is the spreadsheet file set up in workSheetCreation.R
  #wbInfo is used to create the metadata sheet
  shtName <-
    paste(
      unique(nutdf$scenario),
      unique(nutdf$food.group.code),
      unique(nutdf$nutrient),
      sep = "_"
    )
  shtName <- substr(shtName, 1, 31) #sheetnames in xls must be <= 31
  print(shtName)
  nutdf.wide <-
    spread(nutdf[, c("region", "year", "value")], year, value)
  addWorksheet(wb, sheetName = shtName)
  writeData(
    wb,
    nutdf.wide,
    sheet = shtName,
    startRow = 1,
    startCol = 1,
    rowNames = FALSE,
    colNames = TRUE
  )
  return(c(
    shtName,
    paste(
      "Average daily consumption of",
      (unique(nutdf$nutrient)),
      "in scenario",
      (unique(nutdf$scenario)),
      "and food group",
      (unique(nutdf$food.group.code)),
      sep = " "
    )
  ))
}

f.write.nut.sum.sheet <- function(nutdf, wb) {
  #nutdf contains rows for one scenario, food.group,code, and nutrient, all regions and all years
  #wb is the spreadsheet file set up in workSheetCreation.R
  #wbInfo is used to create the metadata sheet
  shtName <- paste(unique(nutdf$scenario),
                   unique(nutdf$nutrient), sep = "_")
  shtName <- substr(shtName, 1, 31) #sheetnames in xls must be <= 31
  nutdf.wide <-
    spread(nutdf[, c("region", "year", "value")], year, value)
  addWorksheet(wb, sheetName = shtName)
  writeData(
    wb,
    nutdf.wide,
    sheet = shtName,
    startRow = 1,
    startCol = 1,
    rowNames = FALSE,
    colNames = TRUE
  )
  # the <<- structure below is supposed to allow one to access a global variable such as wbInfo
  return(c(
    shtName,
    paste(
      "Average daily consumption of",
      (unique(nutdf$nutrient)),
      "in scenario",
      (unique(nutdf$scenario)),
      sep = " "
    )
  ))
}  




Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by awalker89** [comment]
Preferred way to do this in openxlsx is like so:
```
wb <- createWorkbook()

addWorksheet(wb, "Sheet1")
writeData(wb, sheet = "Sheet1", x = iris)

addWorksheet(wb, "Sheet2")
writeData(wb, sheet = "Sheet2", x = mtcars)

addWorksheet(wb, "Sheet3")
writeDataTable(wb, sheet = "Sheet3", x = iris) ## write is a a Excel table

openXL(wb)
```

**Comment by sdanielzafar** [comment]
This methodology is substandard. Let's say you are working with a very large and complicated existing excel workbook and simply need to add in a single sheet. Reading the large and complicated workbook into a workbook object is not perfect and messes up things like images in my experience. There should be a way to append a sheet to an existing workbook without reading it into R. This capability exists in other R packages and should be supported here as well as the premiere excel package for r.

**Comment by ThomasAmetNike** [comment]
Here is one of the solution I have used:

It will overwrite an existing sheet unless it doesn't exist then it will add a new ws to the exisiting workbook and then overwrite it.
`tryCatch({
        wb <- loadWorkbook(fileName)
        writeData(wb = wb, sheet = sheetName, x = output, colNames = T, rowNames = F)
        saveWorkbook(wb = wb, file = fileName, overwrite = T)
      }, error = function(err){
wb <- loadWorkbook(fileName)
addWorksheet(wb = wb, sheetName = sheetName)
writeData(wb = wb, sheet = sheetName, x = output, colNames = T, rowNames = F)
saveWorkbook(wb = wb, file = fileName, overwrite = T)
      })`
