### ISSUE TITLE
Bug in addStyles when stack = TRUE and gridExpand = FALSE

### ISSUE THREAD

**Issue by t-kalinowski** [awalker89/openxlsx#159]
Hello again, and again thank you for making the best R-excel package around. 

I came across some unexpected behavior yesterday with stacking styles. Here is a small reproducible example:

```
#A small reproducible example:
  # Setup example
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
x <- matrix("abc", nrow = 10, ncol = 10)
writeData(wb, 1, x)
addStyle(wb, 1, createStyle(
  halign = "center", border = "TopBottomLeftRight"
), 1:11, 1:10, gridExpand = TRUE)
```
makes this: ![screen shot 2016-03-11 at 7 47 19 am](https://cloud.githubusercontent.com/assets/8462255/13702558/84568906-e75d-11e5-9111-5cd1b4e3907c.png)
```
#--- this call gives unexpected behavior ---
addStyle(wb, 1, createStyle(
  textDecoration = "bold", 
  fgFill = "salmon"), 3:7, 3:7, 
  gridExpand = FALSE, stack = TRUE)

openXL(wb)
#saveWorkbook("stack_styles_bug.xlsx")
```
makes this:
![screen shot 2016-03-11 at 7 44 36 am](https://cloud.githubusercontent.com/assets/8462255/13702498/281454b6-e75d-11e5-82cb-94d2bd023c8e.png)

Notice that, some formatting was lost in cells adjacent to those targeted by the 2nd call to addStyle().

I tried to have a peek in `wb$addStyle()` but I'm afraid that it's a bit over my head to be able to spot the bug...

**Comment by awalker89** [comment]
Thanks for the bug report. This should be fixed now.

**Comment by t-kalinowski** [comment]
Thank you very much! I finally got a chance to test it, looks all good now. 
Thanks again.
