### ISSUE TITLE
worksheetOrder  problem

### ISSUE THREAD

**Issue by maizemaze** [awalker89/openxlsx#162]
very  appreciate this package 

i write code to generate a workbook contain many sheets each sheet have one png plot and a table .

after that i want to reorder sheet position, 

code as following 

wb <- loadWorkbook("***.xlsx")
sheet = names(wb)
worksheetOrder(wb) <- c(order(sheet))

saveWorkbook(wb, "worksheetOrderExample2.xlsx",  overwrite = TRUE)

when i open  "worksheetOrderExample2.xlsx", some of sheet was OK ,but some of them png plot not show 

in the position of png plot got message ： this image cannot currently be displayed.

**Comment by awalker89** [comment]
This can happen if the image no longer exists when saveWorkbook() is called.
Do you have a reproducible example.  This below works for fine unless I delete any of the images before calling openXL(). I will add in a check for file existance but let me know if this isn't your issue.

```
require('ggplot2')
require('openxlsx')

## a plot to save to each worksheet
p <- ggplot() + geom_point(data = iris, aes(x = Sepal.Length, y = Sepal.Width, colour = Species))

wb <- createWorkbook()
for(i in 1:25){
  
  ## save plot as png
  plot_file <- tempfile(pattern = sprintf("Plot%s", i), fileext = ".png")
  p <- p + labs(title = sprintf("Plot%s", i))
  ggsave(filename = plot_file, plot = p)
  
  ## insert plot to worksheet
  addWorksheet(wb, sheet = sprintf("Sheet %s", i))
  insertImage(wb = wb, sheet = sprintf("Sheet %s", i), file = plot_file)

}

worksheetOrder(wb) <- order(names(wb))
openXL(wb)
```

**Comment by maizemaze** [comment]
it working
