### ISSUE TITLE
Indent argument doesn't work

### ISSUE THREAD

**Issue by NelsonChangCW** [awalker89/openxlsx#163]
When I create style with Indent argument, there no indentation appear in the cells of exported .xlsx file I specified. By the way, I think there no code error if I gave indent argument a integer value, like 1.

Here's my actual code
createStyle(indent = 1, fgFill = "#F5F5F5")

Thank U for responding in advance!!

**Comment by awalker89** [comment]
This is fixed now
```

wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
writeData(wb, 1, head(iris))
st <- createStyle(indent = 10, fgFill = "#F5F5F5")
addStyle(wb, sheet = 1, style = st, rows = 1, cols = 1:2)
openXL(wb)
```

![image](https://cloud.githubusercontent.com/assets/7400673/14231061/a50ef806-f9b7-11e5-82cd-c40ad82823aa.png)

**Comment by NelsonChangCW** [comment]
Thank u for the fixing.
