### ISSUE TITLE
large workbooks  zipping up workbook failed

### ISSUE THREAD

**Issue by maizemaze** [awalker89/openxlsx#164]
i need create a large Workbook which may contain 322 sheets,each sheet a png plot and some datatable.

after adding 100 sheets , i got message:

i am sure already installed Rtools 。

because when i process a csv file have 14,000 rows and create a workbook 86 sheets  it worked fine 

Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows. If the "Rtools\bin" directory does not appear in Sys.getenv("PATH") please add it to the system PATH 
         or set this within the R session with Sys.setenv("R_ZIPCMD" = "path/to/zip.exe")

Traceback:
4 stop("zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.\n         Try installr::install.rtools() on Windows.", 
    call. = FALSE) 
3 zipWorkbook(tmpFile, list.files(tmpDir, recursive = TRUE, include.dirs = TRUE, 
    all.files = TRUE), quiet = quiet) 
2 wb$saveWorkbook(quiet = TRUE) 
1 saveWorkbook(wb, filename, overwrite = TRUE) 

In addition: Warning message:
In rm(dXML) : object 'dXML' not found

**Comment by awalker89** [comment]
183650f8829f68324fd1ffc36a50da4c2fddfa1e should fix this. Let me know if you still have issues.
Please update to the dev version with
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by maizemaze** [comment]
Perfect
