### ISSUE TITLE
Question, conditionalFormatting

### ISSUE THREAD

**Issue by tmamiya** [awalker89/openxlsx#165]
Is there a way to have two conditions in the rule argument.  The package is awesome by the way!  Thanks for your work

**Comment by awalker89** [comment]
Yeah just use Excels logical operators
```


wb <- createWorkbook()
addWorksheet(wb, "logical operators")

writeData(wb, "logical operators", 1:10)
writeData(wb, "logical operators", 1:10, startCol = 3)

conditionalFormatting(wb, "logical operators", cols = 1, rows = 1:10,
 rule = "OR($A1=1,$A1=3,$A1=5,$A1=7)")

conditionalFormatting(wb, "logical operators", cols = 3, rows = 1:10,
                      rule = "AND($A1>=3, $A1<=6)")


openXL(wb)

```

**Comment by tmamiya** [comment]
Hello,
Thank you for the reply!
Quick follow up question, if I had the following condition
rule=">A1"
where the condition is referencing the active cell
What would be the syntax, can you just reference the first cell in the range?

Todd-

**Comment by tmamiya** [comment]
Nevermind, yup! you just need to reference the first cell in the range and set the reference to relative
ie:
conditionalFormatting(wb, "logical operators", cols = 3, rows = 1:10,
                      rule = "AND(A1>=A1, A1<=A1)")
