### ISSUE TITLE
troubles with rsconnect recognizing openxlsx loaded from github vs CRAN and install issue?

### ISSUE THREAD

**Issue by klittle314** [awalker89/openxlsx#166]
Hi, I have documented some troubles installing openxlsx from github and then having shinyapps.io recognize that it has to build my shiny app using the github version of openxlsx.   Not sure if openxlsx is really the issue but I did note that on install I am getting warnings that don't seem typical, fyi.

thnks enjoy using your package.

[https://groups.google.com/forum/#!topic/shinyapps-users/9P6DoDTRlxE](url)

**Comment by awalker89** [comment]
the version of openxlsx output by appDependencies() is definitely the github version so not sure what's going on there.

**Comment by klittle314** [comment]
I rolled back to the CRAN version 3.0.0 after trying without success the suggestions from Tareef at RStudio who said maybe a bug in rsconnect [https://groups.google.com/forum/#!topic/shinyapps-users/9P6DoDTRlxE] ...wrestling with another issue in the same app, working with authorization of Google.   when it rains it pours. [https://groups.google.com/forum/#!topic/shinyapps-users/xSL6AWmtc08](url)

**Comment by MikeBadescu** [comment]
If somebody still searching, I confirm the issue with `rsconnect` 0.4.4. I had to remove `rsconnect` in order to install `openxlsx` from github,
