### ISSUE TITLE
getNamedRegions on a Workbook object

### ISSUE THREAD

**Issue by dannyparsons** [awalker89/openxlsx#174]
`getNamedRegions`works when `x` is a file but doesn't seem to work when `x` is a Workbook object. Example:
```
> getNamedRegions(system.file("loadExample.xlsx", package= "openxlsx"))
[1] "Slicer_Species"
> wb <- loadWorkbook(file = system.file("loadExample.xlsx", package= "openxlsx"))
> getNamedRegions(wb)
Error in unzip(xlsxFile, exdir = xmlDir) : invalid zip name argument
```
It appears to be using the method for file and not the one for Workbook. Is that correct?

**Comment by cderv** [comment]
Yes. When you look at the code of the `getNamedRegions`, it is not compatible with a workbook object. It is like `getSheetNames` which work only with an xlsx or xlsm file. 

At first, it could be useful to update the help page of `getNamedRegions`, from 

> _xlsxFile_ An xlsx file or Workbook object

to 

> _xlsxfile_	 An xlsx or xlsm file.

Could make a PR if you want, with adding test on xlsx arguments.

Then, maybe open a Feature Request to make these two functions compatible with a workbook object.

**Comment by awalker89** [comment]
This now works.
![image](https://cloud.githubusercontent.com/assets/7400673/16545245/75e008e2-4168-11e6-93bd-797e322de1b5.png)
