### ISSUE TITLE
read.xlsx Cells with entry "NA" will be treated as NA in R

### ISSUE THREAD

**Issue by robertleitner** [awalker89/openxlsx#176]
Hello, 

gibt a spreadsheet in Excel with cells that contain the string "NA" in a string column, read.xlsx treats it as an empty cell and declares NA to it...

Can you please fix this?

**Comment by awalker89** [comment]
na.strings parameter in read.xlsx will fix this.  see ?read.xlsx
```
na.strings	
A character vector of strings which are to be interpreted as NA. Blank cells will be returned as NA.
```
