### ISSUE TITLE
encoding parameter not supported

### ISSUE THREAD

**Issue by legendaryApps** [awalker89/openxlsx#177]
According to the documentation, the read.xlsx function should support the "encode" parameter, but it doesn't.

My actual problem is that I have subscript text in my Excel file I want to import. On Mac OS X everything works fine, but on Windows the subscript characters are converted to normal ones. This is why I want to set the encoding to UTF-8. However, I always get: `unused argument (encoding = "UTF-8")`.

Thanks!

**Comment by awalker89** [comment]
Hi, can you please attach an example xlsx file I can use to reproduce the bug you are seeing.
