### ISSUE TITLE
read NamedRegions do not work for a one cell regions

### ISSUE THREAD

**Issue by cderv** [awalker89/openxlsx#178]
Hi, 

if you want to read a region defined by just one cell, `read.xlsx` return an error: 

> Error in seq.default(from = cols[1], to = cols[2], by = 1) :  'to' cannot be NA, NaN or infinite.

Issues is that, when address of the region is converted to `cols` and `rows`, the case for range of one cells is not accepted : 

```r
cols <- unlist(lapply(strsplit(region, split = ":", 
            fixed = TRUE), convertFromExcelRef))
rows <- unlist(lapply(strsplit(region, split = ":", 
          fixed = TRUE), function(x) as.integer(gsub("[A-Z]", 
            "", x))))
cols <- seq(from = cols[1], to = cols[2], by = 1)
rows <- seq(from = rows[1], to = rows[2], by = 1)
```
`cols[2]` and `rows[2]` do not exists so it throws an error. 

The function should be modified to accept one cell region.

For exemple, we could do : 
```r
cols <- ifelse(length(cols) == 1, cols[1], seq(from = cols[1], to = cols[2], by = 1))
rows <- ifelse(length(rows) == 1, rows[1], seq(from = rows[1], to = rows[2], by = 1))
```
but then `rows` is checked to be of `length(rows) > 1` and throw an other error.
```r
    if (is.null(rows)) {
        rows <- NA
    }
    else if (length(rows) > 1) {
        rows <- as.integer(sort(rows))
    }
    else {
        stop("rows must be an integer vector else NULL or NA")
    }
```
If I do not check this, I have no error. However, the function returns an empty data.frame with the value of the cell as colname. `read.xlsx` aims to return a `data.frame`, so it does not play well with just a value from one cell.

Conclusion : It should be possible to read a one cell region, but a few modifications has to be done. 
Do not know if it is easy, or if it is the aim of the `read.xlsx` function with `namedRegion` argument. Maybe another function `readNamedRegion` is necessary...

**Comment by awalker89** [comment]
Thanks for the detailed bug report.
