### ISSUE TITLE
Unresolved routine names

### ISSUE THREAD

**Issue by renozao** [awalker89/openxlsx#179]
I get the following error when re-sourcing a file that calls `loadWorkbook` : 

```R
Error in .Call("openxlsx_loadworksheets", wb, styleObjects, worksheetsXML,  : 
  "openxlsx_loadworksheets" not resolved from current namespace (openxlsx) 
```

Adding `PACKAGE = "openxlsx"` in the call `.Call("openxlsx_loadworksheets", ...` in loadWorkbook.R solves the issue.

See http://stackoverflow.com/questions/31352789/keep-hitting-the-error-loop-apply-not-resolved-from-current-namespace-plyr/31592895

**Comment by awalker89** [comment]
Merged.
