### ISSUE TITLE
Question: input via rawConnection

### ISSUE THREAD

**Issue by harveyl888** [awalker89/openxlsx#182]
Hi.
Thanks for a great package.

Is it possible to read an excel file which is stored as a raw vector?
I have excel files stored in a mongodb database (gridfs) and retrieve them via a search.  I can grab the file content as a binary rawConnection.  For data stored in csv format the following code will read in rawData using the read_csv function from the readr library:

```
print(rawData[1:20])
[1] 4e 61 6d 65 2c 31 20 5b 70 6f 73 5d 2c 32 20 5b 70 6f 73 5d

f <- rawConnection(rawData, 'r+b')
myContents <- readr::read_csv(x)
```

Any thoughts on reading a raw vector object with openxlsx?

Thanks!

**Comment by awalker89** [comment]
openxlsx can't do this at the moment. Try https://github.com/hadley/readxl.

**Comment by harveyl888** [comment]
Thanks.  I'll give it a go.
