### ISSUE TITLE
saveWorkbook gives : Error in comment_list[[i]] : subscript out of bounds 

### ISSUE THREAD

**Issue by andyosborn** [awalker89/openxlsx#184]
Hi, I am getting the error using exactly the same code as reported previously in #116 
wb <- loadWorkbook('template46.xlsx')
saveWorkbook(wb, file='newdata.xlsx', overwrite=TRUE)
This seems to be happen if there is a comment in the worksheet, delete the comment and it works.
template46.xlsx

**Comment by andyosborn** [comment]
This is a great package, thanks for all your efforts in creating this, it is currently helping me process cetacean survey data in Excel.
This sounds very like #158, apologies if its a duplicate. 
Is there any chance of getting the fix into the release version of openxlsx?
I tried installing the dev version of openxlsx, but I am getting errors doing that : 
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG    -I"C:/Users/Owner/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++: not found
make: *** [RcppExports.o] Error 127
Warning: running command 'make -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="openxlsx.dll" OBJECTS="RcppExports.o cppFunctions.o"' had status 2
ERROR: compilation failed for package 'openxlsx'

**Comment by awalker89** [comment]
Assuming this was resolved now.  Issue with compilation here is ``` c:/Rtools/mingw_32/bin/g++: not found  ```
Adding rtools to system path will fix this.
