### ISSUE TITLE
more than two conditional formattings in a workbook

### ISSUE THREAD

**Issue by mkim0710** [awalker89/openxlsx#186]
Dear awalker89

Thank you so much for developing this wonderful openxlsx package.

May I ask your advice on a problem I have faced while using your package?

It seems that when more than two conditional formattings are applied in a workbook, the orders are not reserved. 

Could you please advise if this could be fixed?

Or, could you please advise which source code to look into?

I am attaching following codes which I have been trying, which gives me an xls file with only two conditional formattings are applied.

Please let me know your advice.

Thanks.

M

	

# install.packages("NHANES")
library(NHANES)

NHANES_glm <- glm(Depressed ~ Age + Gender + Race1 + Education + MaritalStatus + HHIncomeMid, data = NHANES, family = binomial)

glm_coefCIexp.clean.openxlsx <- function(glm.object, overwrite = FALSE
                                   , red.rule = "<=0"
                                   , yellow.rule = ">=1.1"
                                   , green.rule = ">=1.2"
                                   , blue.rule = ">=1.3"
                                   , emptyRows = 10  
                                   , emptyCols = 10
                                   , first.column.width = "auto", other.columns.widths = 15) {
  
  filename <- paste0( deparse(substitute(glm.object)), "_coefCIexp.clean" )

  rule.list <- list()
  rule.list$red = red.rule
  rule.list$yellow = yellow.rule
  rule.list$green = green.rule
  rule.list$blue = blue.rule
  
  return.df <- as.data.frame(cbind(summary(glm.object)$coefficients, confint.default(glm.object)))

  return.df$OR <- exp(return.df$Estimate)
  return.df$`OR 2.5 %` <- exp(return.df$`2.5 %`)
  return.df$`OR 97.5 %` <- exp(return.df$`97.5 %`)
  

  library(openxlsx)
  df <- data.frame( coefficients = row.names(return.df) )
  df <- cbind(df, return.df)
  
  wb <- createWorkbook()
  
  addWorksheet(wb, "conditionalFormatting")
  
  Style.list <- list()
  Style.list$red <- createStyle(fontColour = "#600000", bgFill = "orangered2")
  Style.list$yellow <- createStyle(fontColour = "goldenrod4", bgFill = "khaki2")
  Style.list$green <- createStyle(fontColour = "#006000", bgFill = "darkolivegreen2")
  Style.list$blue <- createStyle(fontColour = "#000060", bgFill = "cyan2")
  
  sheet.index = 1

  writeDataTable(wb, sheet.index, df, startRow = emptyRows + 1, startCol = emptyCols + 1)
  
  for (i in 1:length(rule.list)) {
    conditionalFormatting(wb, sheet.index, cols= (emptyCols + 2):(emptyCols + ncol(df)), rows= (emptyRows + 2):(emptyRows + nrow(df)+1), rule= rule.list[[i]], style = Style.list[[i]] )
  }
  
  # 
  writeData(wb, sheet.index, as.data.frame(rule.list), startRow = 4, startCol = emptyCols + 2,
            borders = "surrounding", borderStyle = "medium")
  for (i in 1:length(rule.list)) {
    conditionalFormatting(wb, sheet.index, cols= (emptyCols + 1 + i):(emptyCols + 1 + i), rows= 4:5, rule= ">=0", style = Style.list[[i]] )
  }
  
  # setRowHeights(wb, 1, rows = 1:emptyRows, heights = 1 )
  setColWidths(wb, sheet.index, cols = 1:emptyCols, 1)
  setColWidths(wb, sheet.index, cols= emptyCols + 1, widths = first.column.width)
  setColWidths(wb, sheet.index, cols= (emptyCols + 2):(emptyCols + ncol(df)), widths = other.columns.widths)
  
  saveWorkbook(wb, file =  paste0(filename,".xlsx"), overwrite = overwrite)
  
  return.df
}
glm_coefCIexp.clean.openxlsx(NHANES_glm)

**Comment by awalker89** [comment]
Thanks for the bug report - This has been fixed now.
Please update to the dev version with
```
require('devtools')
install_github("awalker89/openxlsx")
```

**Comment by awalker89** [comment]
8a099ec071683d04605d1bbf94e583ad7396f85d

**Comment by mkim0710** [comment]
Thank you so much! :)
