### ISSUE TITLE
loadWorkbook error

### ISSUE THREAD

**Issue by tmamiya** [awalker89/openxlsx#187]
Hello,
Just wanted to bring this to your attention, not a big deal since reverting to stable 3.0 version fixes it\

When I run
openxlsx::loadWorkbook(paste0(Sys.getenv("todd"),"/Reporting-Shipping_Performance/template.xlsx"))
on version 3.1.18 i get:
Error in tmp_vals[["ref"]] : subscript out of bounds

If I revert back to 3.0 it runs fine.  Again not a huge issue but thought you'd want to know.  Let me know if you want me to try any different variations

Much thanks for your work
Todd-

**Comment by awalker89** [comment]
Thanks for the bug report, are you able to attach an example xlsx file which causes the error?

**Comment by tmamiya** [comment]
[template.xlsx](https://github.com/awalker89/openxlsx/files/355251/template.xlsx)

**Comment by awalker89** [comment]
This loads fine for me.  The line of code which is causing the error is related to hyperlinks but it looks like this template no longer contains any hyperlinks?

**Comment by tmamiya** [comment]
Hmm, its weird because I get this error even if I try to load a blank workbook.

**Comment by tmamiya** [comment]
I am still receiving this error even if the "template" excel file is on my local drive with version 3.1.2.  The error disappears and the loadwork book functions works fine, if I revert back to 3.0.0.  Its weird because you haven't done any work on loadwork between 3.0.0 and 3.1.2.  I'd be glad to look into this, but I have no place to start, if you direct me, I'd be glad to take a look.
I don't know if this is related to this but the template file returns this error when it is opened:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error068840_01.xml</logFileName><summary>Errors were detected in file '\\fscluster.homeoffice.google\share\SFS - Todd\Reporting\2016-07-31_Performance.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Table from /xl/tables/table3.xml part (Table)</repairedRecord><repairedRecord>Repaired Records: Table from /xl/tables/table4.xml part (Table)</repairedRecord></repairedRecords></recoveryLog>

**Comment by tmamiya** [comment]
[template.xlsx](https://github.com/awalker89/openxlsx/files/402687/template.xlsx)

**Comment by awalker89** [comment]
Apologies for the very late reply. Is this still an issue with the latest dev version 3.1.24.  Do you have some sample code to replicate this issue?
Simply loading and opening the template.xlsx works fine for me
```
wb <- loadWorkbook("template.xlsx")
openXL(wb)
```

**Comment by awalker89** [comment]
The error: Repaired Records: Table from /xl/tables/table3.xml part (Table)Repaired Records: Table from /xl/tables/table4.xml part (Table)

leads me to believe the bug is introduced after it has been written to.

**Comment by awalker89** [comment]
Bug is due to writing over  an existing tables column names. Like so
```
wb <- loadWorkbook("template.xlsx")
df <- data.frame(matrix(data = runif(15*31), ncol = 15))
writeData(wb, sheet = 3, x = df)
openXL(wb)
```


This works (don't write over table column names)
```
wb <- loadWorkbook("template.xlsx")
df <- data.frame(matrix(data = runif(15*31), ncol = 15))
writeData(wb, sheet = 3, x = df, startRow = 2, colNames = F)
openXL(wb)
```
Or using the template here(contains formatting but not Excel "tables") 
[template.xlsx](https://github.com/awalker89/openxlsx/files/573603/template.xlsx)
use
```
wb <- loadWorkbook("template.xlsx")
df <- data.frame(matrix(data = runif(15*31), ncol = 15))
writeData(wb, sheet = 3, x = df)
addFilter(wb, sheet = 3, rows = 1, cols = 1:15)
openXL(wb)
```

**Comment by awalker89** [comment]
Completing #224  will prevent this from creating corrupt xlsx file.
