### ISSUE TITLE
Looping trough xlsx files to creat one df 

### ISSUE THREAD

**Issue by Elisah8** [awalker89/openxlsx#188]
Hi, 
I really like working with openxlsx and I was hoping you could help me figure out how to use it to create one data frame existing out of multiple excel file with multiple sheets. If gotten so far but somewhere down the line it isn't working: 

```
file.list <- list.files(recursive=T,pattern='*.xlsx') # list of excel files in wd

for (i in 1:length(file.list)){                                          
  wb <- loadWorkbook(file=file.list[i])  #select a file & load workbook
  sheet <- sheets(wb)                    #get sheet list

  for (j in 1:length(sheet)){
    dataframe <- readWorkbook(file.list[i], sheet=j,
                            cols= c(1:4,6,7,9:12,14,15,17:31), startRow=5,
                            skipEmptyRows = T, colNames=F, detectDates = T)
    #dataframe$file = i       # column with file id number
    if (i==1&j==1) dataset1<-dataframe else dataset1<-rbind(dataset1,dataframe) # bind sheets
  } }
```

Thanks very much! 

Elisa

**Comment by awalker89** [comment]
Hi, can you please comment the error message you are seeing.

**Comment by Elisah8** [comment]
Sorry, yes of course! 

This is the error I get: 
`Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`

Thanks!

**Comment by awalker89** [comment]
This issue is due to trying to bind together 2 data.frames that have different columns.  Closing this as not related to openxlsx.
