### ISSUE TITLE
Feature request: add an "update" argument to write.xlsx

### ISSUE THREAD

**Issue by vergilcw** [awalker89/openxlsx#190]
Currently write.xlsx is a great shorthand way to _create_ a workbook.  I am h oping it would also be fairly straightforward to allow you to _update_ a workbook that already exists. 

I'm envisioning a new argument to write.xlsx called `update` which takes either TRUE or FALSE as arguments.  For update=TRUE, the function should first attempt to read the file and if it finds a valid excel workbook, only make updates to the sheets with data listed in the x argument.  You could even leave the formatting alone and update just the data values for those sheets, which would preserve any formatting that existed previously.

This would significantly speed up workflows for folks doing work in R, who are collaborating with others using excel.

**Comment by l4mun** [comment]
Isn't read.xlsx(...) intented for this?

``
myFiles = read.xlsx(...)
#modify myFiles as you want
write.xlsx(...)
``

**Comment by vergilcw** [comment]
There are two issues I encounter when trying to use the approach you outlined:

First, if a spreadsheet has multiple sheets, you can only read in one sheet at a time (which makes sense for read.xlsx given that the output is a dataframe)

Second, write.xlsx can't just replace a single sheet, it seems to obliterate the entire workbook and make a new workbook with just one worksheet.

My feature request is to have an easy way to leave everything about an existing workbook intact, except write a dataframe to one of the sheets (either a new one, or overwrite the data on an existing sheet).

**Comment by nicholaelaw** [comment]
@vergilcw I think you are looking for:

    wb <- loadWorkBook(file)
    writeDataTable(wb, sheet, ...)
    saveWorkBook(wb, file)

This routine adds new sheet(s), and does not touch anything else in the workbook.

**Comment by vergilcw** [comment]
What if I have a sheet within an existing workbook, that, let's say has already been formatted in a specific way: column widths are pre-set (knowing what data will be going in there helps), maybe a specific font and font size are in the sheet already.  It would be nice to just write a dataframe to that sheet, and not touch anything else about the sheet.  This would be roughtly the equivalent of opening the workbook, copying data from somewhere else, and "paste values" (preserving formatting).

Neither of the solutions offered thus far get us there.

**Comment by awalker89** [comment]
I believe the solution suggested by nicholaelaw does exactly what you want.
As an example using this empty & formatted file [template.xlsx](https://github.com/awalker89/openxlsx/files/744103/template.xlsx)

```
library(openxlsx)
wb <- loadWorkbook("template.xlsx")
writeData(wb, sheet = "Iris Data", x = head(iris, 20))
saveWorkbook(wb, "populated_template.xlsx")
openXL("populated_template.xlsx")
```

**Comment by vergilcw** [comment]
Yes, I see you're correct.  Thanks for providing an example proof!  I guess from here It's up to me to create a little wrapper function for syntactical sugar that avoids the step of loading and saving the workbook, with syntax that looks something like:
```
updateWorkbook(x = head(iris, 20), file="myworksheet.xlsx", sheet = "Iris Data")
```

Shouldn't be too difficult on my end.

**Comment by JDMathew** [comment]
I find that the `loadWorkbook()` function corrupts my graphs that have specific formatting. It would be nice to be able to just update a workbook without touching the current sheets.
