### ISSUE TITLE
worksheet xml dimensions

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [awalker89/openxlsx#192]
The excel xml worksheets in xl/worksheets have a dimension tag. 

All R XML packages also openxlsx set the dimensions to 
`<dimension ref="A1"/>`
and excel doesn't worry about this although when saving the file it corrects the tag to i.e.
`<dimension ref="A1:CRF9"/>`
That is, it contains the end cell. I have to work with a software which has a picky reader that stumbles over this and requires correct dimensions. 

As a workaround I correct the sheets by the following routine. But a feature request would be to have openxlsx write the correct dimensions.

```
#' Add correct dimension to excel xml file
#'
#' @param filename  excel xml worksheet which is to be repaired
updateXLSXDimension <- function(filename){
  res <- XML::xmlParse(filename)

  nsDefs <- XML::xmlNamespaceDefinitions(res)
  ns <- structure(sapply(nsDefs, function(x) x$uri), names = names(nsDefs))
  names(ns)[1] <- "xmlns"

  nodes <- XML::getNodeSet(res, "//xmlns:c", ns)
  last_node <- XML::xmlToList(nodes[[length(nodes)]])
  last_cell <- last_node$.attrs[[1]]

  dimension <- XML::getNodeSet(res, "//xmlns:dimension", ns)[[1]]
  XML::xmlAttrs(dimension)[[1]] <- paste0("A1:",last_cell)

  XML::saveXML(res, file=filename)
}
```

**Comment by awalker89** [comment]
This tag is optional (something I didn't know). 
Does removing the tag completely fix your issue?

Something like
```
wb <- createWorkbook()
addWorksheet(wb, 1)
writeData(wb, 1, iris)
wb$worksheets[[1]]$dimension <- NULL
saveWorkbook(wb, "remove_dimension_test.xlsx", overwrite = TRUE)
```

**Comment by Nikolai-Hlubek** [comment]
Hey Alex. 

Thanks for the reply. 
You hardcode the tag at baseXML.R in line 138. So the suggestion shouldn't work. 
But I deleted the tag in the xlsx file, and the software I use cannot cope with it either. Do you have by chance a link to where it states that this tag is optional. Than I could tell the company not to rely on this tag. 

But anyway the java based implementation used by xlsx has this problem as well. 

Best wishes, 
Nikolai
