### ISSUE TITLE
Last rule priority conditionalFormatting

### ISSUE THREAD

**Issue by maressyl** [awalker89/openxlsx#193]
When adding multiple rules using conditionalFormatting() in a sheet, the priority field of the last rule added is 1 rather than "previous rule + 1", and the first created rule priority is always 2. This is quite annoying when dealing with multiple rules on the same cell area as it seems like it randomly messes up the priority we try to establish.

**Comment by awalker89** [comment]
Which version of openxlsx are you using? I think this has been fixed in the dev version on github.

**Comment by maressyl** [comment]
I was using the CRAN version (3.0.0). Indeed there were some more recent changes, priority attribution order changed but the order is now consistent. Sorry !

**Comment by awalker89** [comment]
Thanks for getting back to me.
