### ISSUE TITLE
bgFill setting results in black cells

### ISSUE THREAD

**Issue by daroczig** [awalker89/openxlsx#197]
Hello, first of all, thanks for working on this awesome package!

It seems that setting the `bgFill` param of `createStyle` results in black background color -- independently from what I set. Others seem to have the very same issue: http://stackoverflow.com/questions/37849624/r-unable-to-select-color-using-bgfill-under-createstyle-command-in-openxlsx-pa

Quick example:

```r
wb <- createWorkbook()
addWorksheet(wb, 1)
writeData(wb, 1, mtcars)
addStyle(wb, 1, createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE"),
         rows = 1:(nrow(mtcars)+1), cols = 1:ncol(mtcars), gridExpand = TRUE)
openXL(wb)
```

Resulting spreadsheet (screenshot):

![screenshot from 2016-08-04 02-18-41](https://cloud.githubusercontent.com/assets/495736/17386316/d75598a0-59e9-11e6-829c-3b1e2bb46cd6.png)

And the actual Excel file:  [openxlsx-197.xlsx](https://github.com/awalker89/openxlsx/files/400594/openxlsx-197.xlsx)

My session info (this issue is reproducible both with the CRAN and current dev version):

```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_3.1.20

loaded via a namespace (and not attached):
[1] Rcpp_0.12.6
```

**Comment by awalker89** [comment]
Yeah I'm not sure how excel uses bgFill - change it to fgFill and this will work.

**Comment by awalker89** [comment]
looks like bgFill is used by conditional formatting only.  Have updated the documentation to reflect this.

**Comment by daroczig** [comment]
Ohh, wow, thank you! cc @ajzz

**Comment by guillaumechaumet** [comment]
I have met the same problem here but [onlyoffice](https://fr.wikipedia.org/wiki/Onlyoffice) (my default excel viewer) showed me the right colours. However, when I tried to open the xlsx files with libreoffice and numbers, the cells were black like @daroczig. 
Of course, fgFill solution works.
Thanks @awalker89 for this very useful package

**Comment by sanjmeh** [comment]
I came across a similar issue and landed up on this issue that seems to be closed. My basic question is: 

> "What's the difference between fgFill and bgFill in the createStyle function?".

 Indeed it seems that `bgFill` does not work except in `conditionalFormatting`()

Thanks in advance to @awalker89 to enlighten us.
