### ISSUE TITLE
[Feature Request] CopyWorkbook function

### ISSUE THREAD

**Issue by metanoid** [awalker89/openxlsx#200]
This is low priority, as workarounds are obvious.
But see the below:

```
wb = createWorkbook()  
wb2 = wb  
addWorksheet(wb2,"newworksheetname")  
saveWorkbook(wb, "copytest.xlsx")
```

What the user intended was to have two workbooks (wb and wb2), and only add the new worksheet to wb2.  It was added to wb as well.  

It seems (to me) that there should be something like ` wb2 = copyWorkbook(wb)` that allows the user to copy the entire workbook environment.

**Comment by awalker89** [comment]
Yeah there isn't a nice wrapper function but by default all references classes have a copy method so this can be done with

```
wb = createWorkbook()  
wb2 = wb$copy()
addWorksheet(wb2,"newworksheetname")  

names(wb)
names(wb2)

```
