### ISSUE TITLE
add support for legacy xls files

### ISSUE THREAD

**Issue by spedygiorgio** [awalker89/openxlsx#206]
Openxlsx package is much better than competing xlsx file at least cause not be grounded on Java. Nevertheless lacks support for xls legacy files that are still used somehow... Is it possible to add this support?

**Comment by awalker89** [comment]
There are a few ways to read xls file with R already that are very good. ([gdata](https://cran.r-project.org/web/packages/gdata/index.html) is one of them).  Another package which wraps up many I/O formats for R is  [rio](https://cran.r-project.org/web/packages/rio/index.html) which uses openxlsx.

Given the functionality already exists and the format will hopefully die soon I'd rather not add this to openxlsx to keep the package singularly focussed and clean.
