### ISSUE TITLE
ENH: add "TEXT" format to "numFmt" argument.

### ISSUE THREAD

**Issue by Paykoman** [awalker89/openxlsx#207]
In the function `createStyle`, the argument `numFmt` doesn't have the option for "**TEXT**" format. Would it be possible to add it? Thank you!

ps: this is by far one of the best packages to interact with Excel, keep up with the good work!

![text](https://cloud.githubusercontent.com/assets/2180146/18509634/de68bde2-7a79-11e6-8d5f-4d307c639fa0.png)

**Comment by awalker89** [comment]
Functionality exists but wasn't documented. Have updated ?createStyle to list TEXT as a valid numFmt.
Thanks for reporting.
