### ISSUE TITLE
Failure if firstActiveCol = 1

### ISSUE THREAD

**Issue by djhurio** [awalker89/openxlsx#211]
There is a failure if `firstActiveCol = 1` for the function `freezePane`. The resulting XLSX file is corrupt. See the reproducible example and the error message from the Excel.

```
require(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
freezePane(wb, 1, firstActiveRow = 3, firstActiveCol = 1)
saveWorkbook(wb, "freezePaneExample.xlsx", overwrite = T)
shell.exec("freezePaneExample.xlsx")

```

![image](https://cloud.githubusercontent.com/assets/744800/18553813/a8181d04-7b6a-11e6-9d45-7cfec9aaae32.png)

**Comment by awalker89** [comment]
Thanks for the bug report. a3bdc7e4eac51255a00c3a556a9d1d95fd4d9038 fixes this.

**Comment by djhurio** [comment]
I confirm it is fixed now. Thanks a lot!
