### ISSUE TITLE
when does cran get updated?

### ISSUE THREAD

**Issue by GeraldCNelson** [awalker89/openxlsx#219]
I am using v 3.1.23 and use the skipEmptyCols option of readxlsx. This does not appear to be available in the cran version. I'd rather keep using this but want to make sure my users can also get a version with skipEmptyCols. When do you expect this version to be on cran? 

thanks,
Jerry

**Comment by awalker89** [comment]
Yeah I haven't pushed to CRAN for over year now. I'll try to get this done by the end of the year.

**Comment by ProfFancyPants** [comment]
I also had to move to the dev. version due to empty columns corrupting preceding columns data. Either way, it is an excellent package. I hope it will be stable enough to release to cran.

**Comment by awalker89** [comment]
Version 4.0.0 on CRAN! (but I highly recommend still using the latest github version)
