### ISSUE TITLE
data isn't written to merged cells after the first set of merges

### ISSUE THREAD

**Issue by tejaykodali** [awalker89/openxlsx#220]
If I merge two sets of cells, data isn't being written to the second set of cells. Here's how to reproduce it:

```
library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, "abc")

data <- c("abcd", "efgh", "IJKL")

for (i in 1:3) {
  mergeCells(wb, 1, cols=2:15, rows=i)
  writeData(wb, 1, data[i], startCol=2, startRow=i)
}

for (i in 7:9) {
  mergeCells(wb, 1, cols=2:15, rows=i)
  writeData(wb, 1, data[i], startCol=2, startRow=i)
}

saveWorkbook(wb, "asdf.xlsx", overwrite=TRUE)
```

What it looks like: http://imgur.com/av6Y3fn
What it should look like: http://imgur.com/Vw6pTXb

**Comment by awalker89** [comment]
There's a bug in your code in the second loop. You are referencing data[7], data[8], data[9] which are all NA. writeData leaves NA cells blank in the resulting xlsx file by default.

The second loop should contain
```writeData(wb, 1, data[i-6], startCol=2, startRow=i)```

**Comment by awalker89** [comment]
The results looks like
![image](https://cloud.githubusercontent.com/assets/7400673/20033924/3eb02252-a401-11e6-8a19-ebe62ad022a2.png)
