### ISSUE TITLE
Negative text rotation values are not respected

### ISSUE THREAD

**Issue by TARehman** [awalker89/openxlsx#221]
I'm using openxlsx 3.0.0 - I didn't see anything about this in the issues already, but it might be fixed in some newer version that isn't on CRAN.

I am trying to create some worksheets that have text vertically rotated to -90 degrees, but it seems like the `textRotation` option in `createStyle()` does not respect values below zero. Here's some sample code:

```
library(openxlsx)
sampledata <- matrix(1:20,ncol = 2)
colnames(x = sampledata) <- c("column name one",
                              "column name two")

output_wb <- createWorkbook()
positive_rotate <- createStyle(textRotation = 90)
negative_rotate <- createStyle(textRotation = -90)

addWorksheet(wb = output_wb,sheetName = "Positive Rotate")
writeData(wb = output_wb,
          sheet = "Positive Rotate",
          x = sampledata,
          startCol = 1,
          startRow = 1,
          colNames = TRUE,
          rowNames = FALSE)
addStyle(wb = output_wb,
         sheet = "Positive Rotate",
         style = positive_rotate,
         rows = 1,
         cols = 1:2,
         gridExpand = TRUE,
         stack = TRUE)

addWorksheet(wb = output_wb,sheetName = "Negative Rotate")
writeData(wb = output_wb,
          sheet = "Negative Rotate",
          x = sampledata,
          startCol = 1,
          startRow = 1,
          colNames = TRUE,
          rowNames = FALSE)
addStyle(wb = output_wb,
         sheet = "Negative Rotate",
         style = negative_rotate,
         rows = 1,
         cols = 1:2,
         gridExpand = TRUE,
         stack = TRUE)

saveWorkbook(wb = output_wb,
             file = "rotation_example.xlsx")
```

On my machine, I get two worksheets in the workbook - one has the first row rotated by 90 degrees, and the other shows no rotation at all.

I also tried a value of 270 in the rotation (thinking maybe it would "wrap around", and that ended up giving me a value of 14 degrees in the output (maybe something to do with the max of 255, I don't know).

**Comment by TARehman** [comment]
Just an update - I looked at the XML for a file where I set the rotation to -90 in Excel, and it shows up as 180. If I use that parameter in `openxlsx` for `textRotation`, I get the correct alignment when I open the file.

I don't know why the standard would use 0-90 as normal, and then 91 - 180 for negative values...but it seems like you could add some simple logic in to catch the problem in R, probably around line 670ish in wrappers.R. Something like...

```
if(textRotation < 0 & textRotation >= -90) {
    textRotation <- (textRotation * -1) + 90
}
```

It's a hack, but I think it might work - I'm not super familiar with the standards behind the xlsx format, so I could be totally off-base here, of course.

**Comment by awalker89** [comment]
Thanks for the bug report and fix. Have included your fix.
