### ISSUE TITLE
freeze pane options in write.xlsx outputs to console

### ISSUE THREAD

**Issue by t-kalinowski** [awalker89/openxlsx#227]
small example:
```
> openxlsx::write.xlsx(mtcars, "mtcars.xlsx",  firstCol = TRUE, firstRow = TRUE)
[1] "<pane ySplit=\"1\" xSplit=\"1\" topLeftCell=\"B2\" activePane=\"bottomRight\" state=\"frozen\"/><selection pane=\"bottomRight\"/>"
```

as far as I can tell, the resulting file is fine. This probably should be returning the input object invisibly rather than this character string.

**Comment by awalker89** [comment]
Thanks for the bug report. a57932a8f5d5dad7657f5d0818ac09f9ed9c04f6 fixes this.
