### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by gse-cc-git** [awalker89/openxlsx#228]
Hello,
First, thank you for your wonderful package.
I have an issue regarding the RAM usage: I am using `openxlsx` in the Rstudio environment and writing a ~60MB dataframe (~400k rows x 18cols) in a workbook using `writeDataTable` and saving it  using `saveWorkbook` made the RAM usage raise by about 2Go !

I observed this using both the CRAN and dev versions of `openxlsx` .

Am I doing something wrong ? Any insights ?
Thank you.

Edit:
Profiling the `writeDataTable` function showed that the `replaceIllegalCharacters` function and particularly the `gsub` call was memory consuming. As `gsub` doesn't seem to make use of regex pattern, maybe using the `fixed=TRUE` parameter would help ?

**Comment by awalker89** [comment]
The main issue  is that openxlsx stores the data.frame as a character vector ready for writing to file.
So this happens:
```
> object_size(1:1E6)
4 MB
> object_size(as.character(1:1E6))
56 MB
```

I've spent the last few weeks rebuilding much of openxlsx to reduce the memory usage (and eventually speed it up).  The memory usage has more than halved in the latest dev version 3.2.0 so please update with
`devtools::install_github("awalker89/openxlsx")`


As an example:


```
library("openxlsx")
library("pryr")
fl <- tempfile(fileext = ".xlsx")

x <- as.data.frame(matrix(runif(4E5*20), ncol = 20))

mem_change({
  
  wb <- createWorkbook()
  addWorksheet(wb, "S1")
  writeData(wb, 1, x)
  saveWorkbook(wb, fl, overwrite = TRUE)
  
})

## Memory usage
### openxlsx 3.1.x: 3.52 GB
### openxlsx_3.2.0: 1.13 GB
```
Also, thanks for your tip re `fixed = TRUE` - have made this change.
