### ISSUE TITLE
1x1 namedRegion being imported as a column name

### ISSUE THREAD

**Issue by jjcad** [awalker89/openxlsx#230]
I have a 1x1 named region in an excel file that I'm trying to pull out. I would assert that it ought to be a vector, but it's being output as a data.frame with a single column, no records, and the value I was trying to get is the name of the column.

This is affecting version 3.1.25, installed using devtools.

**Comment by awalker89** [comment]
read.xlsx always returns a data.frame. If ```colNames = TRUE``` the first row is used as column names.  
Try setting ```colNames = FALSE```.

**Comment by jjcad** [comment]
Ah gotcha.
