### ISSUE TITLE
conditionalFormatting()_multiple rules corrupt

### ISSUE THREAD

**Issue by Sunflower16** [awalker89/openxlsx#231]
### Background
Hi, I am working on an automation task, using the conditionalFormatting() function to highlight cells, based on different rules for over a dozen variables. 
 For example, for a numeric column named "a", the rules are: 
1) if (  5 < a <= 10 ), highlight cells in yellow; 
2) if ( 0 <= a < 5 ), highlight cells in blue; 
3) if ( a < 0 ), highlight cells in red. 

However, I ran into two issues:
## Issue 1: The "rule" argument does not accept argument between a range. 
Although in issue # 107 Rules in conditionalFormatting for cell values, there was one example (which does not work now): 
conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2:22, rule = c(-5, 5), type = "between")

Is there any way to recover that feature? Or an older version I can install in order to benefit from that feature?

### A working example
df <- data.frame("a" = runif(99, min = -5, max = 15))
wb <- write.xlsx(df, file = "tmpt.xlsx")

##### to transform color name to hex code automatically, using "gplots" package, colhex() function 
install.packages("gplots")
require(gplot)

conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule= "<= 10", style = createStyle(bgFill = col2hex("yellow")))
conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule = "<= 5", style = createStyle(bgFill = col2hex("blue")))
conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule = "< 0" , style = createStyle(bgFill = col2hex("red")))

openXL(wb)

But, the output only shows highlighting in "yellow" and "red", not any "blue".

**Comment by awalker89** [comment]
Hi, both your examples work fine for me.  
![image](https://cloud.githubusercontent.com/assets/7400673/21292855/6edc87d2-c566-11e6-86f3-9034b917dbfd.png)
Please update to the latest dev version of openxlsx from github.
`devtools::install_github("awalker89/openxlsx")`

**Comment by awalker89** [comment]
Also, createStyle does the col2hex conversion internally - you don't need gplots::col2hex.
This works:
```
conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule= "<= 10"
                      , style = createStyle(bgFill = "yellow"))

conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule = "<= 5"
                      , style = createStyle(bgFill = "blue"))

conditionalFormatting(wb, sheet = 1, cols = 1, rows = 2 : 100, rule = "< 0" 
                      , style = createStyle(bgFill = "red"))
```
