### ISSUE TITLE
preserve case in format styles

### ISSUE THREAD

**Issue by adatko** [awalker89/openxlsx#232]
When creating number format styles the cases of characters get converted to lower case
`cfMillion     <- openxlsx::createStyle(numFmt = "$#.00,, \" M\"")`
above is an attempt to create a format style to resemble excel's format for displaying numbers in millions, with a capital M following the rounded number, like so "$4.02  M". When applied, however, data is displayed like "$4.02  m".
culprit is `numFmt <- tolower(numFmt[[1]])` inside createStyle - a workaround, if one is needed to compare values would be to convert to lower case when comparing values (to make them safe, which is what I'm assuming this is trying to achieve), like so.:
` if (tolower(numFmt) == "longdate")`

would be greatly appreciated!

**Comment by awalker89** [comment]
This is fixed in the dev version. Please update with
```
devtools::install_github("awalker89/openxlsx")
```
