### ISSUE TITLE
Installing openxlsx

### ISSUE THREAD

**Issue by msgoussi** [awalker89/openxlsx#240]
Dear Sir,
I was trying to update your package version (4) then I received this message:
Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'EAT-3EAT'
I am wondering if this relates to your package or to the base package.
Thanks

**Comment by awalker89** [comment]
I don't think that has anything to do with openxlsx.  If you paste the full error output here I can confirm this for you.
