### ISSUE TITLE
Error in read.xlsx.default:    basic_string

### ISSUE THREAD

**Issue by MariaSL** [awalker89/openxlsx#242]
## STACK
- Openxlsx package version: 4.0.0
- RStudio version: 1.0.136
- R version: 3.3.2
- Excel version: 17.30 (170107)

## DATA EXAMPLE
[Amounts.xlsx](https://github.com/awalker89/openxlsx/files/704481/Amounts.xlsx)

## PROBLEM DESCRIPTION
When reading an Excel file with
 `data <- read.xlsx("/Users/mariaslanova/Desktop/Amounts.xlsx", detectDates = TRUE)`, the function returns the following error:

![screen shot 2017-01-13 at 15 29 04](https://cloud.githubusercontent.com/assets/9034592/21933290/17cc21ca-d9a5-11e6-97b0-1c2ddda0280a.png)

Running the function without `detectDates = TRUE` does not return any error, but the dates are not detected properly.
Using the older version of the package (Openxlsx package version: 3.0.0) solves the problem.

### 
Thanks,
Maria

**Comment by awalker89** [comment]
Thanks for the bug report.  This should be fixed now, please update with
```
devtools::install_github("awalker89/openxlsx")
```
