### ISSUE TITLE
databar "show databar only" option in conditionalFormatting

### ISSUE THREAD

**Issue by ywebbvar** [awalker89/openxlsx#253]
Hi! Thank you for the amazing work!

Is it possible within the latest version of the package to create databars that have the "show databar only" option available in Excel?

I am trying out conditionalFormatting for creating databars, and I see that I have two arguments to customize them: style and rule. Is it possible that, through them, the results is what the "show databar only" option does?

Here is an example of what I aiming for:
![screen shot 2017-02-06 at 4 41 11 pm](https://cloud.githubusercontent.com/assets/5922230/22673032/75fda4ea-ec8c-11e6-8cc9-82aa8c49fbe3.jpg)

The first column came from the following code:
```
writeData(wb, "databar2", cbind(abs(-5:5),abs(-5:5)))
conditionalFormatting(wb, "databar2", cols = 1, rows = 1:12, type = "databar", style=c("#FFFFFF","#7A7A7A"), rule= c(0,5))
```

The second came from using a rule in Excel:
![screen shot 2017-02-06 at 4 45 28 pm](https://cloud.githubusercontent.com/assets/5922230/22672923/cac15892-ec8b-11e6-97fd-53aad660265b.jpg)

Many thanks!

**Comment by awalker89** [comment]
Hi,

Thanks for the detailed question. I've added the functionality to pass additional parameters to conditionalFormatting().
Install the dev version from github with
`devtools::install_github("awalker89/openxlsx")`

The documentation has been extended with an example to show all databar functionality.
See ?conditionalFormatting


To get what you are after try this
```
wb <- createWorkbook()
addWorksheet(wb, "databar2")
writeData(wb, "databar2", cbind(abs(-5:5),abs(-5:5)))
conditionalFormatting(wb, "databar2", cols = 1, rows = 1:12, type = "databar", style=c("#FFFFFF", "#7A7A7A"))
conditionalFormatting(wb, "databar2", cols = 2, rows = 1:12, type = "databar", style=c("#a6a6a6"), showValue = FALSE, gradient = FALSE)
openXL(wb)

```

**Comment by ywebbvar** [comment]
Hi, Alex. I was able to reproduce the example. Thank you so very much!
Specially for updating the package so quickly!

**Comment by ywebbvar** [comment]
Feedback: there is a typo in the help file: 'sepcifiying'
