### ISSUE TITLE
Data validation type = 'list'?

### ISSUE THREAD

**Issue by WHMan** [awalker89/openxlsx#254]
I totally agree with @debarros that this is a fantastic package. It would be even fantasticker if [dataValidation](https://github.com/awalker89/openxlsx/issues/143) included the option to add "list" as the validation type.

This may be somewhat related to #160.

Thanks in advance.

**Comment by awalker89** [comment]
d8c8209a42b7ec58e0066ccba9ea8a748ad77f16 adds this functionality.  It's very beta at the moment and will corrupt the workbook if the `value` parameter isn't correct (note if the worksheet name has space in it it needs to be quoted in single quotes).  Will wrap error checking around this eventually.

Example:
```
## update to dev version
install_github("awalker89/openxlsx")

wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
addWorksheet(wb, "Sheet 2")

writeDataTable(wb, sheet = 1, x = iris[1:30,])
writeData(wb, sheet = 2, x = sample(iris$Sepal.Length, 10))

## list validation pointing to sheet 2
dataValidation(wb, 1, col = 1, rows = 2:31, type = "list", value = "'Sheet 2'!A1:A9")

openXL(wb)


``
