### ISSUE TITLE
Table not removed after clearing Worksheet

### ISSUE THREAD

**Issue by mhermans** [awalker89/openxlsx#256]
I am trying clear a Worksheet of existing tables, and subsequently write new tables with `writeDataTable()` to the same region where those tables where.

However, clearing the cell contents, nor removing/re-adding the Worksheet seem to work, as the tables seem to be retained. This results in the error "**Error in writeDataTable(wb, "test", x, startCol = 1, startRow = 1) :  Cannot overwrite existing table.**"

Minimally reproducible example & system info below.

thanks,

Maarten

----

    x <- data.frame(
      id = c(1, 2, 3, 4),
      gender = c('M', 'M', 'F', 'F'))

    wb <- createWorkbook()
    addWorksheet(wb, 'test')
    writeDataTable(wb, 'test', x, startCol = 1, startRow = 1)
    saveWorkbook(wb, 'test.xlsx', overwrite = TRUE)

    wb <- loadWorkbook('test.xlsx')
    deleteData(wb, 'test', 1:100, 1:300, gridExpand = TRUE)
    removeCellMerge(wb, 'test', 1:100, 1:300)
    writeDataTable(wb, 'test', x, startCol = 1, startRow = 1)

> Error in writeDataTable(wb, "test", x, startCol = 1, startRow = 1) : 
>  Cannot overwrite existing table.

    str(wb$tables)

> atomic [1:1] <table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="3" name="Table3" displayName="Table3" ref="A1:B5" totalsRowShown="0"><autoFilter ref="A1:B5"/><tableColumns count="2"><tableColumn id="1" name="id"/><tableColumn id="2" name="gender"/></tableColumns><tableStyleInfo name="TableStyleLight9" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table> 
>  - attr(*, "sheet")= int 1
> - attr(*, "tableName")= Named chr "Table3"
> ..- attr(*, "names")= chr "A1:B5"

    wb <- loadWorkbook('test.xlsx')
    removeWorksheet(wb, 'test')
    addWorksheet(wb, 'test')
    writeDataTable(wb, 'test', x, startCol = 1, startRow = 1)

> Error in writeDataTable(wb, "test", x, startCol = 1, startRow = 1) : 
>   Cannot overwrite existing table.

    str(wb$tables)

> atomic [1:1] <table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="3" name="Table3" displayName="Table3" ref="A1:B5" totalsRowShown="0"><autoFilter ref="A1:B5"/><tableColumns count="2"><tableColumn id="1" name="id"/><tableColumn id="2" name="gender"/></tableColumns><tableStyleInfo name="TableStyleLight9" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table> 
>   - attr(*, "sheet")= int 1
> - attr(*, "tableName")= Named chr "Table3_openxlsx_deleted"
> ..- attr(*, "names")= chr "A1:B5"

    sessionInfo()

> R version 3.3.1 (2016-06-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux stretch/sid
> 
> locale:
>   [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
> [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
> [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
>   [1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
>   [1] openxlsx_4.0.0

> loaded via a namespace (and not attached):
>   [1] tools_3.3.1 Rcpp_0.12.6

**Comment by PeterVermont** [comment]
I also experienced this -- I called removeWorksheet but the table that was on that sheet was not removed since when I tried to re-create the worksheet and table I got this: 'Cannot overwrite existing table.'

**Comment by PeterVermont** [comment]
Actually found a workaround that may help inform you about what is happening. I got it to work by saving the workbook and then reloading.

      new_sheet_name <- paste0(results_prefix,scn$name)
      #delete sheet if already exists
      if (any(sheet_names==new_sheet_name)) {
       removeWorksheet(wb, new_sheet_name)
       saveWorkbook(wb, excelFile, overwrite=TRUE)
       wb <- loadWorkbook(file = excelFile)
      }
      addWorksheet(wb, new_sheet_name)
      writeDataTable(wb, scenario_products_market_share, sheet=new_sheet_name) #, tableName=new_sheet_name)


Additionally, I thought the message was about a named table object but I still got the error even after stopping specifying a data table name.

**Comment by mhermans** [comment]
Thanks for the workaround Peter. 

I'm relatively sure that the issue is related to the check for not overwriting a table [here](https://github.com/awalker89/openxlsx/blob/master/R/writeDataTable.R#L175) is not ignoring the deleted-indicator assigned [here](https://github.com/awalker89/openxlsx/blob/d8c8209a42b7ec58e0066ccba9ea8a748ad77f16/R/WorkbookClass.R#L1403).

I'll try the coming days to test a small patch to see if that is true. This would then take care of the removeWorksheet() / addWorksheet() way of clearing tables, as I don't see logic to detect table-deletion when using deleteData() + removeCellMerge().

**Comment by awalker89** [comment]
This should work now (still testing a bit)
```

wb <- createWorkbook()
addWorksheet(wb, sheetName = "Sheet 1")
addWorksheet(wb, sheetName = "Sheet 2")

writeDataTable(wb, sheet = "Sheet 1", x = iris, tableName = "iris")
writeDataTable(wb, sheet = 1, x = mtcars, tableName = "mtcars", startCol = 10)


removeWorksheet(wb, 1) ## delete worksheet removes table objects

writeDataTable(wb, sheet = 1, x = iris, tableName = "iris")
writeDataTable(wb, sheet = 1, x = mtcars, tableName = "mtcars", startCol = 10)

## removeTable clears table object and all data
getTables(wb, sheet = 1)
removeTable(wb = wb, sheet = 1, table = "iris")
writeDataTable(wb, sheet = 1, x = iris, tableName = "iris", startCol = 1)

getTables(wb, sheet = 1)
removeTable(wb = wb, sheet = 1, table = "iris")
writeDataTable(wb, sheet = 1, x = iris, tableName = "iris", startCol = 1)

openXL(wb)
```

**Comment by jallen1006** [comment]
I am having a similar issue, but the workaround @PeterVermont provided doesn’t seem to work for me.

I have a workbook with multiple worksheets, 1 of which contains data that I need to update weekly. The worksheet that needs to be updated weekly contains 1 table (Table2). I created this workbook in Excel. When I run the code below the first time through, everything works great. 

    '#Prior to this code, I have some steps that update the data with no issues
    wb <- loadWorkbook(“C:/…./file.xlsx”)
    removeWorksheet(wb, sheet = “Sheet1")
    addWorksheet(wb, sheetName = "Sheet1")
    writeDataTable(wb, sheet="Sheet1", updated.data, startCol = 1, startRow = 1, colNames = TRUE,     tableStyle = "TableStyleMedium2", tableName = "Table2")
    saveWorkbook(wb,“C:/…./file.xlsx”,overwrite = T)'

Then when I run the script again (i.e. the next week) I get the error “Error in file(con,”r”) : invalid ‘description’ argument” after running the line wb <- loadWorkbook(“C:/…./file.xlsx”). If I continue to run the script, when I get to the writeDataTable line, that is when I get the “Cannot overwrite existing table” error.

If I use the workaround @PeterVermont suggested the code looks like this

    '#Prior to this code, I have some steps that update the data with no issues
    wb <- loadWorkbook(“C:/…./file.xlsx”)
    removeWorksheet(wb, sheet = “Sheet1”)
    saveWorkbook(wb,“C:/…./file.xlsx”,overwrite = T)
    wb <- loadWorkbook(“C:/…./file.xlsx”)
    addWorksheet(wb, sheetName = "Sheet1")
    writeDataTable(wb, sheet="Sheet1", updated.data, startCol = 1, startRow = 1, colNames = TRUE, tableStyle = "TableStyleMedium2", tableName = "Table2")
    saveWorkbook(wb,“C:/…./file.xlsx”,overwrite = T)'

When I run through it the first time (starting from the original Excel doc), I get “Error in file(con,”r”) : invalid ‘description’ argument” after the second “loadWorkbook” step but it seems to work fine despite this error. However, on the second time through, I get “Error in file(con,”r”) : invalid ‘description’ argument” on the first and second “loadWorkbook” steps and then when I get to the writeDataTable step I get the “Cannot overwrite existing table” error.

After all this, when I open the Excel doc it says “We have found a problem with some content. Do you want us to recover as much as we can…” I select yes and it says “Removed Records: Table from xl/tables/table3.xml part (Table). However, I never had a table3 in the workbook. I only had a table1 and table2. 
Based on this, I think something is happing during the saveWorkbook step that is causing the problem. I can run the script without error when I start from the original doc I created in Excel, but when I try to load the workbook after it has been saved (using saveWorkbook) from R to Excel that is when the problems start.

Can anyone recommend a fix? Will the removeTable function fix this? When will it be available?
