### ISSUE TITLE
skipEmptyCols argument for read.xlslx still removes columns when set to FALSE

### ISSUE THREAD

**Issue by awarmack** [awalker89/openxlsx#257]
I read an entire xlsx file here: 
`> read.xlsx("test.xlsx")`

```
>   x1 x2 x3 x4 x5
> 1  0  1 NA  1  a
> 2  0  2 NA  3  b
> 3  0  3 NA  4  c
> 4  0  4 NA  1  d
```

I skip the header row and set skipEmptyCols to TRUE: 

`> read.xlsx("test.xlsx", skipEmptyCols = TRUE, startRow=2, colNames=FALSE)`

```
  X1 X2 X3 X4
1  0  1  1  a
2  0  2  3  b
3  0  3  4  c
4  0  4  1  d
```

No problem

`> read.xlsx("test.xlsx", skipEmptyCols = FALSE, startRow=2, colNames=FALSE)`

```
  X1 X2 X3 X4
1  0  1  1  a
2  0  2  3  b
3  0  3  4  c
4  0  4  1  d

```

Same output

**Comment by renatovargas** [comment]
Same issue here, but also on the rows.

`> a <- read.xlsx("openxlsxTest.xlsx", startRow = 5, colNames = FALSE, rowNames = FALSE, skipEmptyRows= FALSE, rows = c(5:10), cols = c(4:8))`
and I get
`
  X1 X2 X3 X4
1  2  6  6  6
2  3  6  6  6
3  g  7  7  6
4  4  5  7  6
5  6  5  6  6
`
When it should be...
`
    X1 X2 X3 X4 X5
1    2  6  6 NA  6
2    3  6  6 NA  6
3   NA NA NA NA  6
4    g  7  7 NA  6
5    4  5  7 NA  6
5    6  5  6 NA  6
`
I've tried `openWorkbook(sheet = 1, ...) `, and embedding it in as.data.frame() or as.matrix() with the same results.

Any thoughts?

[openxlsxTest.xlsx](https://github.com/awalker89/openxlsx/files/782183/openxlsxTest.xlsx)

**Comment by awalker89** [comment]
This has been fixed now. Please update to the latest version on github using
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by renatovargas** [comment]
Very much appreciated. Thank you!
