### ISSUE TITLE
Feature Request: Add border style top border with double bottom border

### ISSUE THREAD

**Issue by debmartin06** [awalker89/openxlsx#258]
In finance, we use this border style to foot sums. I've been able to do a workaround, by doing a bottom border on the cells above, and a double bottom on the cells below, but it's not ideal.

![image](https://cloud.githubusercontent.com/assets/17315897/23068425/a172b544-f4f1-11e6-8993-ff3367382a88.png)

**Comment by awalker89** [comment]
Please update to the latest dev version and try this
```
devtools::install_github("awalker89/openxlsx")

wb <- createWorkbook()
addWorksheet(wb, "sheet1")

addStyle(wb, sheet = 1, style = createStyle(border = "topbottom",
                                            borderStyle = c("thin", "double")), rows = 5, cols = 3)
## or
addStyle(wb, sheet = 1, style = createStyle(border = c("top", "bottom"),
                                            borderStyle = c("thin", "double")), rows = 5, cols = 6)

openXL(wb)


```
