### ISSUE TITLE
Suggestion: in Readme.md make clear this is cross-platform because message about RTools gives wrong impression

### ISSUE THREAD

**Issue by PeterVermont** [awalker89/openxlsx#259]
Great library -- thanks!

**Comment by PeterVermont** [comment]
Suggest ‘For Linux and MacOS this should be available by default’

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by awalker89** [comment]
Thanks - done.
