### ISSUE TITLE
possible issue with encoding--uploading Excel files to shiny app on shinyapps.io via openxlsx

### ISSUE THREAD

**Issue by klittle314** [awalker89/openxlsx#260]
`Hi, we have a shiny app running on shinyapps.io that allows users to upload Excel files; we use openxlsx package to interact with Excel.   

We created the uploadable files for users via VBA.   We found that some files would not load, in those cases, we get an error when the user clicked on the upload widget (see screen shot)
![error image](https://cloud.githubusercontent.com/assets/3459577/23222294/0891b8fc-f8ed-11e6-8d34-2ced15f0565f.jpg)

All files always loaded when we ran the shiny app locally on my Windows 10 system.

We narrowed down possible problems to encoding (see BACKGROUND, below)

Wondering if you have any insights into encoding of Excel and interaction with shiny apps.

Thanks for a useful package, we like it very much.

BACKGROUND
We found that we could usually get Excel files to load if we opened them and made a trivial edit and then saved them again.  

The issue seems to be related to encoding.   When we force the failed files to have UTF-8 encoding rather than the Window default encoding on my Windows 10 system, the files will load to shinyapps.io

We also have found that if we use Excel 2016 version of VBA to create user files and force encoding to be UTF-8 (automating the manual steps [here](https://help.surveygizmo.com/help/encode-an-excel-file-to-utf-8-or-utf-16)), then all files load successfully.

As far as I can tell, openxlsx package does not allow users to work with encoding directly?

I filed a support ticket with RStudio as part of our troubleshooting.

RStudio support said:
"fileInput doesn't have an encoding parameter because it's not doing the reading.  fileInput just passes the file through to the function that actually does the reading, and it's that other, reading function that must handle encoding.  The encoding examples in the article - readLines, write.csv - are in other packages, not shiny itself. [[article](http://shiny.rstudio.com/articles/unicode.html)]

In your case, you should check if the openxlsx function you are using to read the file supports some sort of encoding, encode, or file encoding parameter.  If not, there is a package called Encoding that you may be able to use to encode the file between fileInput and the openxlsx function."
#####
Our situation:  we are trying to go to a production version that potentially will have 100+ users submitting Excel files.    And we may need to generate the Excel files for the users.  So we are trying to understand the causes of the underlying problem to convince ourselves we know how to prevent users from experiencing problems loading their Excel files.

**Comment by awalker89** [comment]
Do you have an example xlsx file I can use to reproduce this error?

**Comment by klittle314** [comment]
Thanks for responding.   Problem may be elusive.   I cannot cause anything to fail when I run the shiny app locally on my machine, only for certain files on upload to shinyapps.io server.   If you want to observe the failure, I have invited you to my shinyapps.io app using your gmail address.   You can try loading the attached file.   We have not been able to see anything in the file itself that causes trouble.
[CHC Test 8.xlsx](https://github.com/awalker89/openxlsx/files/801594/CHC.Test.8.xlsx)  Thanks for any insight

**Comment by awalker89** [comment]
I can't reproduce the error locally either.

I've setup a minimal app to reproduce this error here:  https://alexanderwalker.shinyapps.io/shiny_file_failure/

The error is thrown before getting to any openxlsx function (infact it looks like it's thrown before getting to
`output$contents <- renderTable({...})`)

Look to me like something on shinyapps.io's end.

![image](https://cloud.githubusercontent.com/assets/7400673/23336099/5eba0a7a-fc19-11e6-9a74-ccf8c9da232c.png)

**Comment by awalker89** [comment]
Code for my app FYI
```
## Only run examples in interactive R sessions
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput("file_name1", "Select a file")
    ),
    mainPanel(
      verbatimTextOutput("inFile"),
      tableOutput("contents")
    )
  )
)
```
```
library("shiny")
library('openxlsx')

server <- function(input, output) {
  output$contents <- renderTable({
    
    inFile <- input$file_name1

    txt <- sprintf("$ class(input$file_name1)       : %s", class(input$file_name1))
    for(nm in names(input$file_name1)){
      txt <- c(txt, sprintf("$ %s            : %s", nm, input$file_name1[[nm]]))
    }

    output$inFile <- renderText(paste(txt, collapse = "\n"))

    if (is.null(inFile))
      return(NULL)
    
    print("now read in file")
    read.xlsx(xlsxFile = inFile$datapath, sheet = 1)
  })
}
```

**Comment by klittle314** [comment]
Thanks for minimal example.  I confirm that when I load the minimal app to shinyapps.io, my fail file can not be processed by fileInput.  I reopened the ticket with RStudio support, forwarding your example and linking to my shinyapps.io version of the minimal example.   Will update here for posterity if RStudio can help.  Thanks again!

**Comment by geolauf** [comment]
Hi, facing the same issue.. could somebody find a solution? best regards

**Comment by klittle314** [comment]
We don't have a fix yet.  We are looking at moving to Hadley's readxl package for other reasons but have not tested or implemented.   Since we stopped trying to create files with VB, the incidence has decreased but still occurs from time to time.   Not a good way to maintain a shiny app.

**Comment by jeffzs** [comment]
I am facing the same issue. was there a solution?

**Comment by klittle314** [comment]
Have not found a solution.   We plan to update to readxl this summer as part of our package maintenance but have no insight into cause of the failures.
