### ISSUE TITLE
openXL fails silently with relative path

### ISSUE THREAD

**Issue by PeterVermont** [awalker89/openxlsx#261]
Once again -- thanks for the terrific tool.

I gave it a file path that had been retrieved with system.file like this
    system.file("extdata", "CalcMarketShare_sample.xlsx", package = "CalculateProductShare")

and it failed without any warning or error.

When I made a full path with normalizePath it worked as expected.

**Comment by awalker89** [comment]
Do you have a example to reproduce this error?
This works for me
```
openXL(system.file("readTest.xlsx", package = "openxlsx"))
```
and this correctly throws an error
```
> openXL(system.file("some-non-existant-file.xlsx", package = "openxlsx"))
Error in openXL(system.file("some-non-existant-file.xlsx", package = "openxlsx")) : 
  Non existent file or wrong path.
```

**Comment by awalker89** [comment]
d327c9ee5c1973702e8cc82b40608983c603dfc7 fixes this bug.  Thanks for the bug report and fix.
