### ISSUE TITLE
Tables with column names containing two consecutive spaces cause corruption

### ISSUE THREAD

**Issue by PeterVermont** [awalker89/openxlsx#263]
I know this is strange -- believe me it took a while to narrow this down.

To replicate all you need to do is loadWorkbook with a workbook that has a table with two consecutaive spaces in one of the column titles and then open it:
```
library(openxlsx)
#if test.xlsx has a table column name with at least two consecutive spaces...
wb <- loadWorkbook("test.xlsx")
#this open will report a corrupted file
openXL(wb)
```

![image](https://cloud.githubusercontent.com/assets/889233/23262606/5285921e-f9a9-11e6-843e-3b9f5d783c6e.png)

If you remove the spaces and save the file again it works without any problems:

![image](https://cloud.githubusercontent.com/assets/889233/23262660/7b72712e-f9a9-11e6-8264-3744771847cf.png)

**Comment by awalker89** [comment]
Thanks for this one - that would have been a nightmare to find. cd2cbfd7185146d83eba0c4c3d5c0a5d089f5358 fixes this bug.

**Comment by PeterVermont** [comment]
I really appreciate the library and since you are still actively working on it I was inspired to take the time to figure this out in detail…

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..
