### ISSUE TITLE
Error when saving 0 row data.frame with "POSIXct" "POSIXt" columns.

### ISSUE THREAD

**Issue by dmontaner** [awalker89/openxlsx#267]
Hi

I am saving data.frames which have "POSIXct" "POSIXt" columns. When the data.frames have more than 0 rows everything is fine but when I try to save __0 rows__ data.frames I get an error message. The error seems to happen just when I have the "POSIXct" "POSIXt" columns.

This code reproduces the error:

```
library (openxlsx)
a <- data.frame (one = 1:3, two = letters[1:3], three = Sys.time ())
b <- a[FALSE,]
a
b
sapply (a, class)
sapply (b, class)
write.xlsx (a, file = "test_a.xlsx")
write.xlsx (b[,-3], file = "test_b.xlsx")
write.xlsx (b, file = "test_b.xlsx")      ## error here
```

The last line returns an error: `Error in `[[.default`(df[[i]], 1) : subscript out of bounds`

I am using openxlsx version "4.0.8" and "R version 3.3.2 (2016-10-31)"

Thanks for the package!!!

**Comment by awalker89** [comment]
Thanks for the bug report.

**Comment by dmontaner** [comment]
It is working perfect for me now... Thanks for the quick fix !!!
