### ISSUE TITLE
na.strings don't work when xlsxFile=WORKBOOK

### ISSUE THREAD

**Issue by hroptatyr** [awalker89/openxlsx#268]
Steps to reproduce:

    wb <- loadWorkbook(FILE)
    head(readWorkbook(wb, na.strings="#N/A N/A"), n=1)
    =>
            Date            PX_LAST PX_VOLUME AVERAGE_BID_ASK_SPREAD_%
    1 2016-01-01           #N/A N/A  #N/A N/A                 #N/A N/A

This works however:

    head(readWorkbook(FILE, na.strings="#N/A N/A"), n=1)
    =>
            Date PX_LAST PX_VOLUME AVERAGE_BID_ASK_SPREAD_%
    1 2016-01-01      NA        NA                       NA

**Comment by awalker89** [comment]
Thanks for the bug report.
