### ISSUE TITLE
can't overwrite a previously created file

### ISSUE THREAD

**Issue by ywebbvar** [awalker89/openxlsx#271]
Hi! Again, thank you for the awesome work you guys have done with openxlsx.

I found an error when trying to use writeData to overwrite a 'used' workbook. I attach a file I was testing ([conditionalFormattingExample.xlsx](https://github.com/awalker89/openxlsx/files/813099/conditionalFormattingExample.xlsx)).

The conditionalFormattingExample already has a table in sheet 1. I want to overwrite the numbers it has.

Here is the code I was using:

```{r} 
wb <- loadWorkbook("conditionalFormattingExample.xlsx")
set.seed(749309421)
dta =  runif(n = 11,min = 0,max = 3)
writeData(wb, x=dta,
          sheet = 1, startCol = 1, startRow = 1, colNames = FALSE)
```

This produces the error:

`Error in if (possible_overlap) inds <- which(paste(rows, cols, sep = ",") %in%  : 
  missing value where TRUE/FALSE needed`

This error is pointing at the function 'worksheets[[sheet]]$sheet_data$write' ([which I found here](openxlsx/R/sheet_data_class.R))

And it appears the cols vector has an NA, and the min and max function output NA instead of a number. 

Thanks!

**Comment by awalker89** [comment]
Hi, running the latest dev version from github I am unable to reproduce this error. Do you have another example?

I am running this
```
wb <- loadWorkbook("conditionalFormattingExample.xlsx")
set.seed(749309421)
dta =  runif(n = 11,min = 0,max = 3)
writeData(wb, x=dta,sheet = 1, startCol = 1, startRow = 1, colNames = FALSE)
openXL(wb)
```

**Comment by ywebbvar** [comment]
Hi, Alex,

I confirm that the error is no longer there. Many thanks!
