### ISSUE TITLE
Empty worksheet on MacOS causes Error in loadWorkbook("filename") : basic_string

### ISSUE THREAD

**Issue by PeterVermont** [awalker89/openxlsx#272]
Simply create an empty workbook with a single empty worksheet.

calling loadWorkbook will get the error.

If you type in any cell and save again the load will work!

**Comment by PeterVermont** [comment]
Definitely did not mean to close!

This sounds like a silly error -- why would someone want a totally blank worksheet. In our case we had an 'Introduction' tab with nice graphic images and text but no data in the cells...

**Comment by awalker89** [comment]
I'm unable to reproduce this on windows with a blank xlsx file or only file only containing an image.  Do you have an example xlsx file I can use to reproduce this error?

**Comment by PeterVermont** [comment]
This only occurs on MacOS.

**Comment by PeterVermont** [comment]
The error is happening inside this call:
`
  wb <- .Call("openxlsx_loadworksheets", wb, styleObjects, worksheetsXML, is_chart_sheet, PACKAGE = 'openxlsx')`

I have attached the empty workbook and also the sheet1.xml which worksheetsXML pointed to.


[empty_sheet.zip](https://github.com/awalker89/openxlsx/files/819828/empty_sheet.zip)


[sheet1.xml.zip](https://github.com/awalker89/openxlsx/files/819826/sheet1.xml.zip)

**Comment by PeterVermont** [comment]
Figured it out!

load_workbook.cpp has this check for an empty sheet:

```
     bool has_data = true;
      if(pos == string::npos){
        has_data = false;
        pos = xml.find("<sheetData/>");
      }

```

However, on the MacOS the empty sheetData tag **has an extra space**: `<sheetData />`
