### ISSUE TITLE
Named Regions Referring to Single Cell

### ISSUE THREAD

**Issue by kloppen** [awalker89/openxlsx#274]
It appears that there is a bug in openxlsx where named regions that contain only a single cell cannot be read when a workbook is passed to read.xlsx (instead of a path to a worbook). This problem occurs in the lastest version available from CRAN (4.0.0) and also in the latest development version, (currently commit a63e4cb).

To reproduce this bug, a workbook was created. [Book1.xlsx](https://github.com/awalker89/openxlsx/files/819814/Book1.xlsx) This workbook contained the following named regions:

Name       | Refers To
-----------|------------------
NamedCell  | =Sheet1!$ C $ 2
NamedCell2 | =Sheet1!$ C $ 2 : $ C $ 2
NamedTable | =Sheet1!$ C $ 5 : $ D $ 8

For named regions with multiple rows and columns, the correct behavior is exhibited. The workbook Book1.xlsx contains two named region. The NamedTable region has three rows of data and two columns (plus a column header). Calling read.xlsx with the filename of the workbook works as expected.

```r
library(openxlsx)
res <- read.xlsx("Book1.xlsx", namedRegion = "NamedTable")
print(res)
```

Similarly, calling read.xlsx after a workbook is loaded with loadWorkbook works as expected with multi-row/column named regions.

```r
wb <- loadWorkbook("Book1.xlsx")
res <- read.xlsx(wb, namedRegion = "NamedTable")
print(res)
```

When read.xlsx is called with the path to a workbook and asked to read a named region containing a single cell, it works as expected. This is demonstrated by reading two named regions: one referring to "=Sheet1! $ C $ 2", the other referring to "=Sheet1! $ C $ 2: $ C $ 2"

```r
res <- read.xlsx("Book1.xlsx",
                 namedRegion = "NamedCell",  # This refers to Sheet1!$C$2
                 colNames = FALSE,
                 rowNames = FALSE)
print(res)
```

```r
res <- read.xlsx("Book1.xlsx",
                 namedRegion = "NamedCell2",  # This refers to Sheet1!$C$2:$C$2
                 colNames = FALSE,
                 rowNames = FALSE)
print(res)
```

However, when read.xlsx is called using a workbook loaded with loadWorkbook, it works when the named region refers to Sheet1! $ C $ 2: $ C $ 2, but not when it refers to Sheet1! $ C $ 2

```r
wb <- loadWorkbook("Book1.xlsx")

# The following works fine
res <- read.xlsx(wb,
                 namedRegion = "NamedCell2",  # This refers to Sheet1!$C$2:$C$2
                 colNames = FALSE,
                 rowNames = FALSE)
print(res)
```

```r
wb <- loadWorkbook("Book1.xlsx")

# The following produces the error:
##  Error in seq.default(from = cols[1], to = cols[2], by = 1) : 'to' cannot be NA, NaN or infinite
res <- read.xlsx(wb,
                 namedRegion = "NamedCell",  # This refers to Sheet1!$C$2
                 colNames = FALSE,
                 rowNames = FALSE)
print(res)
```

My devtools::session_info is as follows:

Session info ----------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-03-05                  

Packages --------------------------------------------------------------------
 package    * version date       source        
 backports    1.0.5   2017-01-18 CRAN (R 3.3.2)
 base64enc    0.1-3   2015-07-28 CRAN (R 3.3.2)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 evaluate     0.10    2016-10-11 CRAN (R 3.3.2)
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.2)
 jsonlite     1.0     2016-07-01 CRAN (R 3.3.1)
 knitr        1.15.1  2016-11-22 CRAN (R 3.3.2)
 magrittr     1.5     2014-11-22 CRAN (R 3.3.1)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.1)
 openxlsx   * 4.0.0   2017-01-09 CRAN (R 3.3.2)
 Rcpp         0.12.5  2016-05-14 CRAN (R 3.3.1)
 rmarkdown    1.3     2016-12-21 CRAN (R 3.3.2)
 rprojroot    1.2     2017-01-16 CRAN (R 3.3.2)
 rstudioapi   0.6     2016-06-27 CRAN (R 3.3.1)
 stringi      1.1.1   2016-05-27 CRAN (R 3.3.0)
 stringr      1.1.0   2016-08-19 CRAN (R 3.3.1)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)
 yaml         2.1.13  2014-06-12 CRAN (R 3.3.1)

I have found the code causing this issue and will submit a PR shortly that addresses the problem. There was a difference in the way that read.xlsx.Workbook and read.xlsx.default handled named regions. In the PR that I'll submit, I've updated read.xlsx.Workbook to mirror what read.xlsx.default does.

**Comment by awalker89** [comment]
Thanks for this
