### ISSUE TITLE
No header/footer when writing an excel file

### ISSUE THREAD

**Issue by samuelreuther** [awalker89/openxlsx#276]
I can not find out how to print header/footer in an excel file. Even if I try the example code provided in the R help section, no header/footer will be written in the excel file.

Best regards,
Samuel

openxlsx version 4.0.0 from CRAN
Excel version: Microsoft Office Professional Plus 2010 14.0.7177.5000

Example code provided in the R help section
## Create a new workbook
wb <- createWorkbook("Fred")

## Add 3 worksheets
addWorksheet(wb, "Sheet 1")
addWorksheet(wb, "Sheet 2", gridLines = FALSE)
addWorksheet(wb, "Sheet 3", tabColour = "red")
addWorksheet(wb, "Sheet 4", gridLines = FALSE, tabColour = "#4F81BD")

## Headers and Footers
addWorksheet(wb, "Sheet 5",
             header = c("ODD HEAD LEFT", "ODD HEAD CENTER", "ODD HEAD RIGHT"),
             footer = c("ODD FOOT RIGHT", "ODD FOOT CENTER", "ODD FOOT RIGHT"),
             evenHeader = c("EVEN HEAD LEFT", "EVEN HEAD CENTER", "EVEN HEAD RIGHT"),
             evenFooter = c("EVEN FOOT RIGHT", "EVEN FOOT CENTER", "EVEN FOOT RIGHT"),
             firstHeader = c("TOP", "OF FIRST", "PAGE"),
             firstFooter = c("BOTTOM", "OF FIRST", "PAGE"))

addWorksheet(wb, "Sheet 6",
             header = c("&[Date]", "ALL HEAD CENTER 2", "&[Page] / &[Pages]"),
             footer = c("&[Path]&[File]", NA, "&[Tab]"),
             firstHeader = c(NA, "Center Header of First Page", NA),
             firstFooter = c(NA, "Center Footer of First Page", NA))

addWorksheet(wb, "Sheet 7",
             header = c("ALL HEAD LEFT 2", "ALL HEAD CENTER 2", "ALL HEAD RIGHT 2"),
             footer = c("ALL FOOT RIGHT 2", "ALL FOOT CENTER 2", "ALL FOOT RIGHT 2"))

addWorksheet(wb, "Sheet 8",
             firstHeader = c("FIRST ONLY L", NA, "FIRST ONLY R"),
             firstFooter = c("FIRST ONLY L", NA, "FIRST ONLY R"))

## Need data on worksheet to see all headers and footers
writeData(wb, sheet = 5, 1:400)
writeData(wb, sheet = 6, 1:400)
writeData(wb, sheet = 7, 1:400)
writeData(wb, sheet = 8, 1:400)

## Save workbook
saveWorkbook(wb, "addWorksheetExample.xlsx", overwrite = TRUE)

**Comment by awalker89** [comment]
Appears to be working for me
![image](https://cloud.githubusercontent.com/assets/7400673/23742994/1ffc37b6-0503-11e7-8607-9a3b08021f93.png)

![image](https://cloud.githubusercontent.com/assets/7400673/23743017/33b08b5e-0503-11e7-989e-9f945310ef45.png)


If you are still not seeing anything please re-open the ticket.

**Comment by samuelreuther** [comment]
Hi Alex,

 

thank you very much for your answer!

 

I’m sorry, I didn’t check out the page layout. It‘s working exactly as you showed in your print screens.

 

With best regards,

Samuel

 

 

Von: Alex [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. März 2017 10:02
An: awalker89/openxlsx
Cc: samuelreuther; Author
Betreff: Re: [awalker89/openxlsx] No header/footer when writing an excel file (#276)

 

Appears to be working for me
 <https://cloud.githubusercontent.com/assets/7400673/23742994/1ffc37b6-0503-11e7-8607-9a3b08021f93.png> image

 <https://cloud.githubusercontent.com/assets/7400673/23743017/33b08b5e-0503-11e7-989e-9f945310ef45.png> image

If you are still not seeing anything please re-open the ticket.
