### ISSUE TITLE
Workbook size inflated

### ISSUE THREAD

**Issue by ksak3** [awalker89/openxlsx#278]
Is there a way to keep openxlsx from inflating the file size? In this example, I started with a 5.6MB workbook, wrote data to about 300 cells, and the new file size is about 8MB.  It drops down to 7.1MB if I open the file and resave. The XLConnect version is slower but the file size increases by only 2K. This is with most recent CRAN package and running on Linux. 

`> wb = loadWorkbook("~/test6.xlsx")`
`> writeData(wb, x = status, sheet = 1)`
`> saveWorkbook(wb, file = "~/test6c.xlsx", overwrite = TRUE)`

I unzipped the workbooks and found that the unzipped file size of xl/worksheets/sheet3 (which I did not edit) is 54MB in the test6c and and 45MB in test6. sheet1 (which I did write to) grew from 1K to 11K.

**Comment by awalker89** [comment]
Now a global option to set the compression level
```
df <- matrix(sample(LETTERS, size = 2000000, replace = T), ncol = 200)

fl <- tempfile(fileext = ".xlsx")
fl2 <- tempfile(fileext = ".xlsx")

wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
writeData(wb, sheet = 1, x = df)

options("openxlsx.zipFlags" = "")
saveWorkbook(wb, file = fl, overwrite = TRUE)

options("openxlsx.zipFlags" = "-9")
saveWorkbook(wb, file = fl2, overwrite = TRUE)

> file.info(fl)[["size"]] / 1024^2 ## MB
[1] 9.634725
> file.info(fl2)[["size"]] / 1024^2 ## MB
[1] 6.183241
> 
```

**Comment by ksak3** [comment]
Tested this and down to 5.9MB. Thanks!
