### ISSUE TITLE
Borders impacted by writedata

### ISSUE THREAD

**Issue by ksak3** [awalker89/openxlsx#279]
From the documentation it appears that the default border style for writeData is 'no border' but does this mean if there is a border prior to writing it would disappear? In any case it appears borders are disappearing at random.  Ideally (to me?) no formatting should be changed unless specified.

Starting:
![formattest1](https://cloud.githubusercontent.com/assets/9751462/23812864/42d1e914-05aa-11e7-9604-0104ed6079f5.png)
After writeData:
![formattest2](https://cloud.githubusercontent.com/assets/9751462/23812875/4b893c24-05aa-11e7-832d-d1618626db90.png)
Repeated same writeData:
![formattest3](https://cloud.githubusercontent.com/assets/9751462/23812888/5396bdba-05aa-11e7-9d2b-a8bcb0cf9bb6.png)

**Comment by awalker89** [comment]
This bug should be fixed now - existing styling should nto be affected by writeData(). Please update with
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by ksak3** [comment]
Looks great now, thanks!
