### ISSUE TITLE
Default createWorkbook arg env var USERNAME should be USER on linux

### ISSUE THREAD

**Issue by tedtoal** [awalker89/openxlsx#284]
The default argument for createWorkbook() is Sys.getenv("USERNAME").  On Linux and OSX, the user name is in environment variable USER, not USERNAME.

**Comment by awalker89** [comment]
Will changing the default to 
```
ifelse(.Platform$OS.type == "windows", Sys.getenv("USERNAME"), Sys.getenv("USER"))
```
fix the issue?

**Comment by tedtoal** [comment]
Yes, that would probably do it.

—
Ted Toal, Postdoctoral Researcher
Carvajal-Carmona Lab
4502 GBSF, One Shields Ave
Davis, CA  956626  (530) 263-5986
twtoal@ucdavis.edu
