### ISSUE TITLE
Default zip command doesn't work under Linux

### ISSUE THREAD

**Issue by tedtoal** [awalker89/openxlsx#285]
On OSX, openxlsx works without Windows-specific Rtools, because OSX has a zip command built in.  Linux usually also has a zip command, and in my case it did, in the usual location of /usr/bin, but openxlsx complained with an error message about it.  I was able to make it work with:

Sys.setenv("R_ZIPCMD"="zip")

since /usr/bin is on the path.  This seems like a reasonable default for R_ZIPCMD, at least on Linux platforms.

**Comment by awalker89** [comment]
Hi, the default is already set as `Sys.getenv("R_ZIPCMD", "zip")`. I think this might be related to your particular setup as has been tested on Windows and Linux.

**Comment by tedtoal** [comment]
The setting of R_ZIPCMD, using Sys.getenv("R_ZIPCMD"), is empty.

**Comment by awalker89** [comment]
The use of `Sys.setenv("R_ZIPCMD" = "path/to/zip.exe") ` is documented in the vignette. 
The default behaviour is to use Sys.getenv("R_ZIPCMD", "zip") which will return "zip" if R_ZIPCMD has not been set.

**Comment by tedtoal** [comment]
Ok, just did some more checking.  I installed R 3.1.1 yesterday, and it shows R_ZIPCMD=/usr/bin/zip, and this is because there is an Renviron file in the R local etc directory containing that assignment.  I guess the R installer must have created that file because I didn't.  When I look at my R 3.3.2 installation, the Renviron file assigns an empty string to R_ZIPCMD.  I don't know why the difference exists, but it seems like this must be caused by whatever is putting that value in the Renviron file.

**Comment by PeterVermont** [comment]
FYI my Rcmd_environ at location: C:\Program Files\R\R-3.3.2\etc has this:

```
## Default zip/unzip commands
R_UNZIPCMD=${R_UNZIPCMD-'unzip'}
R_ZIPCMD=${R_ZIPCMD-'zip'}
R_BZIPCMD=${R_BZIPCMD-'bzip2'}

```

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
```

**Comment by PeterVermont** [comment]
```
> Sys.getenv("R_ZIPCMD")
[1] ""
```

**Comment by tedtoal** [comment]
Btw, I'm installing my R's using conda, into a conda environment.

**Comment by awalker89** [comment]
openxlsx now uses the `zip` R package

**Comment by Hamedhm** [comment]
Please follow the steps below:
```
conda install zip
conda install r-zip
whereis zip
export R_ZIPCMD=THE_PATH_FROM_WHEREIS
```
