### ISSUE TITLE
Error in .Call("openxlsx

### ISSUE THREAD

**Issue by skanskan** [awalker89/openxlsx#290]
Today my openxlsx produces this error:

Error in .Call("openxlsx_get_shared_strings", sharedStringsFile, isFile,  : 
  "openxlsx_get_shared_strings" not available for .Call() for package "openxlsx"

No matter what excel file I try to open.

I'm using Rstudio+R 3.3.1 in Windows 10 X64.
openxlsx 4.0.17

Any idea of what is going on?

Reinstalling it doesn's solve the problem

**Comment by awalker89** [comment]
Have now removed all .Call calls from openxlsx.
