### ISSUE TITLE
Invalid characters result in corrupted file

### ISSUE THREAD

**Issue by etienne-s** [awalker89/openxlsx#294]
Writing a dataframe containing invalid characters results in a corrupted xlsx file.

When I say "invalid characters" I mean the ones that are invalid in XML, such as U+0001.

## Steps to Reproduce the Problem 

  ```r
write.xlsx("hello\u0001", "test.xlsx")
```

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.3.3

**Comment by kerry-ja** [comment]
I think this may be the same issue as #185
