### ISSUE TITLE
error while reading a xlsx with A1 cell empty

### ISSUE THREAD

**Issue by Oleg-dM** [awalker89/openxlsx#295]
While trying to read a xlsx with empty A1 cell, I got the error:

> openxlsx::read.xlsx("../data/9QTM.xlsx")
Error in read.xlsx.default("../data/9QTM.xlsx") : expecting a single value

The sheet:

![image](https://cloud.githubusercontent.com/assets/8371571/25333730/bdeb4fc8-28eb-11e7-9627-d7a7bc4679b4.png)

## sessionInfo()

  - Version of openxlsx: openxlsx_4.0.17
  - Version of R: 3.3.3

**Comment by awalker89** [comment]
Do you have an example xlsx file to reproduce this?

**Comment by awalker89** [comment]
Closing as related to #262
