### ISSUE TITLE
Feature Request: set the spreadsheet display size upon opening

### ISSUE THREAD

**Issue by lazarillo** [awalker89/openxlsx#297]
## Expected Behavior

I would like to be able to set the default size that the xlsx file will be upon opening.  In my use case, I am cleaning up and organizing data for others to "consume".  But the files that I generate create very tiny display sizes (the actual size of the display upon opening), so I have to open each one after completion and change the screen size.

## Actual Behavior

Allow for a function or flag that lets this display size be adjustable, something similar to what [VBA allows](https://www.mrexcel.com/forum/excel-questions/391680-visual-basic-applications-screen-size-%3D.html)

## Steps to Reproduce the Problem 

There's no problem.

## sessionInfo()

Not sure it's relevant, but here goes:

    R version 3.3.2 (2016-10-31)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: macOS Sierra 10.12.4

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] openxlsx_4.0.17 tm_0.7-1        NLP_0.1-10      readr_1.0.0    
    [5] dplyr_0.5.0     readxl_0.1.1   

    loaded via a namespace (and not attached):
     [1] magrittr_1.5   R6_2.2.0       assertthat_0.1 parallel_3.3.2 DBI_0.5-1     
     [6] tools_3.3.2    tibble_1.2     Rcpp_0.12.9    slam_0.1-40    stringi_1.1.2 

  - Version of openxlsx:

 4.0.17

  - Version of R:

      $svn rev
      [1] "71607"

    $language
    [1] "R"

    $version.string
    [1] "R version 3.3.2 (2016-10-31)"

    $nickname
    [1] "Sincere Pumpkin Patch"

**Comment by awalker89** [comment]
Looks like this can only be done using vba (please correct me if I'm wrong).
Try creating a template file with the required VBA and loading and writing to this with R.

I created an xlsm file with containing the VBA
```
Private Sub Workbook_Open()
    Application.WindowState = xlNormal
    Application.Top = 300
    Application.Left = 300
    Application.Width = 300
    Application.Height = 200
End Sub
```

Then from R
```
wb <- loadWorkbook("template.xlsm")
writeData(wb, sheet = 1, x = iris)
openXL(wb)
```

**Comment by lazarillo** [comment]
OK, thanks @awalker89 !

In my particular case, providing the xlsm with VBA is not ideal, because I was trying to provide "push button" code for a client, where they could just run the R script I'd provided and get the updated Excel workbook to hand to their less technical colleagues.

But it's also not a big deal... anyone can adjust the window manually when desired.

OpenXLSX is a great library, by the way!  Thank you for all your wonderful work!

**Comment by gonulate** [comment]
This would be a great feature. It is very inconvenient to resize the windows every time an excel file is created. VBA method is not feasible and complicated enough to implement.

**Comment by hoegge** [comment]
Yes - openxlsx must do something special in the current export, that forces Excel to open the file in a small Windows. This does not happen to other files. It probably depends on some default settings, that are not used, when openxlsx creates the files, as when you create a file yourself in Excel.

**Comment by jzadra** [comment]
I've tried the VBA solution and I get this error.  I'm using Excel for Mac 16.60 on OSX 12.3.1

![image](https://user-images.githubusercontent.com/25590353/164773214-a6f67aa3-f6e7-41bf-9b73-6ef958542b7c.png)

![image](https://user-images.githubusercontent.com/25590353/164773229-cc95e72c-6b89-4b4f-8906-ac79c0833094.png)

**Comment by dcaud** [comment]
Any chance of addressing this?

**Comment by mansfin** [comment]
I'm also finding the default display size to be inconvenient. It would be great if this issue could be addressed.

**Comment by epruesse** [comment]
This can be set other than through VB. I looked into it a while back. There is a place in the XML that says how large the window should be.

**Comment by tsolloway** [comment]
You can edit these defaults in 
```
wb <- openxlsx::createWorkbook()
wb[["workbook"]][["bookViews"]]
```

Something like this solves your issues on init 

```
oxl_create_workbook <- function(
    window_width = 33125,
    window_height = 16105
){

require(openxlsx)

  wb <- openxlsx ::createWorkbook()
  wb[["workbook"]][["bookViews"]] <- glue::glue('<bookViews><workbookView xWindow=\"0\" yWindow=\"0\" windowWidth=\"{window_width}\" windowHeight=\"{window_height}\"/></bookViews>')

  return(wb)
}
```
