### ISSUE TITLE
Openxlsx Package/ writeData Function Issue

### ISSUE THREAD

**Issue by upchair** [awalker89/openxlsx#302]
## Expected Behavior
My R Code is supposed to export data extracted from facebook into an excel sheet called S1. It 
 successfully pulls the data from facebook into data frames.

## Actual Behavior
My Script runs successfully but gives me a blank excel sheet named S1.  It does not import the data frame into the S1 excel sheet at all.

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.
  
  2.
  
  3.

## sessionInfo()

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.10     openssl_0.9.6    openxlsx_4.0.17  Rfacebook_0.6.11 httpuv_1.3.3    
[6] rjson_0.2.15     httr_1.2.1      

loaded via a namespace (and not attached):
[1] compiler_3.4.0 R6_2.2.1       tools_3.4.0    curl_2.6 

  - Version of openxlsx:
Version 4.0.17

  - Version of R: 3.4.0 
(I run it Via RStudio Version 1.0.136

- My Code

load ("fb_oauth")

wb <- createWorkbook()
addWorksheet(wb, "S1")
saveWorkbook(wb, file = "C:/gboyega/G_Comments.xlsx", overwrite = FALSE)

fb_page_no_nullz<-getPage(page="gtbank", token=fb_oauth,n=1, since= '2017/05/23', until= '2017/05/24',feed=TRUE)  #Extract THE LATEST n=7 FCMB posts excluding Null rows from FCMB page# into variable/vector fb_page .

no_of_rows= na.omit(nrow(fb_page_no_nullz))   # Count the number of rows without NULLS and store in var no_of_rows

i=1

while (i<=no_of_rows)
  
{
  
  postt <- getPost(post=fb_page_no_nullz$id[i], n=11, token=fb_oauth)
   
  
  postt$comments$Brand_Post<-c(fb_page_no_nullz[1,3])

writeData(wb, "S1", x = postt$comments[,1:1], xy = c("A", 1),colNames = TRUE,rowNames = FALSE)

i=i+1   
}

Thank You.

Richard

**Comment by awalker89** [comment]
You need to save the object after writing to it.  Move `saveWorkbook(wb, file = "C:/gboyega/G_Comments.xlsx", overwrite = FALSE)` to the end.  

Please use the examples in the help files e.g. `?writeData`
