### ISSUE TITLE
Error in pageSetup function

### ISSUE THREAD

**Issue by mtrudeau314** [awalker89/openxlsx#304]
## Expected Behavior
The sheet parameter should take the name or index of a sheet in the workbook and set the orientation.

## Actual Behavior
When the sheet parameter is set to the name of the sheet, the orientation parameter appears to be ignored and set to portrait no matter what the default is. However, fit to height and fit to width was still functional regardless of providing the name versus the index of the sheet.

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.   pageSetup(wb, sheet = "sheet name", orientation = 'landscape', scale = 100, left = 0.1,
               right = 0.1, top = .75, bottom = .75, header = 0.1, footer = 0.1,
              fitToWidth = TRUE, fitToHeight = TRUE, paperSize = 1)
  
  2.  Above code results in portrait orientation with all other parameters still functional.
  
  3.

## sessionInfo()

  - Version of openxlsx:  4.0.17
  - Version of R:  3.4.0

**Comment by gkotler** [comment]
I have the same problem:

 pageSetup(WB, Sheet, 
                  orientation = "landscape", scale = 100, 
                  left = 0, right = 0, top = 0, bottom = 0, header = 0, footer = 0,
                  fitToWidth = FALSE, fitToHeight = FALSE)

Please pay attention: difference in  generated XML files:
version 3.0.0:
........><pageMargins left="0" right="0" top="0" bottom="0" header="0" footer="0"/>"<pageSetup paperSize="9" orientation="landscape" scale = "100" fitToWidth="0" fitToHeight="0" horizontalDpi="300" verticalDpi="300" r:id="rId2"/></worksheet>

version 4.0.17:
.... ><pageMargins left="0" right="0" top="0" bottom="0" header="0" footer="0"/></worksheet>

**Comment by awalker89** [comment]
Thanks for the bug report.  This should be fixed now. Please update with 
```
devtools::install_github("openxlsx", username = "awalker89")
```
