### ISSUE TITLE
openxlsx can't open file, generated by apache poi

### ISSUE THREAD

**Issue by nik-lazer** [awalker89/openxlsx#306]
## Expected Behavior
I'm trying to open via openxlsx the simple Excel file, whic was generated by Java (apache POI library). This is the code I use:
```
# Test Excel
## Needed library - if you do not have it, import it on the right lower side -> packages
library(openxlsx)
options(show.error.locations = TRUE)
options(error=traceback)

# adapt the path to where the Detail Modulator Excel files is
setwd("C:///Rprojects/")


# Name of the Detail Modulator Output File
# xlsmfile <<- c("Book_2.xlsx")
xlsmfile <<- c("Book_2_corrupt.xlsx")

sheetname="RAWDATA"
RAW_DATA_1_raw = read.xlsx(xlsmfile)

# If it does not work, it returns the error below:
# Error in read.xlsx.default(xlsmfile, sheet = sheetname) : 
#  expecting a single value
```

For testing I use two files:
1) Book_2.xlsx, which I create via Excel
2) Book_2_corrupt.xlsx - this I get via Apache POI - opened via Java Book_2.xlsx, saved without changes.

Both files doesn't contain any content, so formating of cells is excludeed.

[Book_2.xlsx](https://github.com/awalker89/openxlsx/files/1094695/Book_2.xlsx)
[Book_2_corrupt.xlsx](https://github.com/awalker89/openxlsx/files/1094696/Book_2_corrupt.xlsx)

## Actual Behavior
Instead of succesful reading of the file, script crushes with the error:

```
xlsmfile <<- c("Book_2_corrupt.xlsx")
> sheetname="RAWDATA"
> RAW_DATA_1_raw = read.xlsx(xlsmfile)
Error in read.xlsx.default(xlsmfile) : 
 Expecting a single string value: [type=character; extent=0].
4: stop(list(message = "Expecting a single string value: [type=character; extent=0].", 
      call = read.xlsx.default(xlsmfile), cppstack = NULL))
3: .Call("openxlsx_getCellInfo", xmlFile = worksheet, sharedStrings = sharedStrings, 
      skipEmptyRows = skipEmptyRows, startRow = startRow, rows = rows, 
      getDates = detectDates, PACKAGE = "openxlsx")
2: read.xlsx.default(xlsmfile)
1: read.xlsx(xlsmfile)
```

If I use Book_2.xlsx - openxlsx opens it without errors. I'm not sure that openxlsx is the reason, may be Apache POI does something wrong, but it'd be great to understand that exactly

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. Take the code from example, change argument of setwd() to actual folder of Excel files
  
  2. Set Book_2_corrupt.xlsx as a file name (variable xlsmfile),
  
  3. run script, get error.

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.3.2

**Comment by awalker89** [comment]
76560d1db16557330dc41d77dee21c7bf5966f26 closes this.

Thank you for the bug report and reproducible example.  
Please update with
```
devtools::install_github("awalker89/openxlsx")
```

This now works as expected
```
fl <- "Book_2.xlsx"
x <- read.xlsx(fl)

fl <- "Book_2_corrupt.xlsx"
x <- read.xlsx(fl)


fl <- "Book_2.xlsx"
x <- read.xlsx(loadWorkbook(fl))

fl <- "Book_2_corrupt.xlsx"
x <- read.xlsx(loadWorkbook(fl))
```
