### ISSUE TITLE
Error when writing with empty table

### ISSUE THREAD

**Issue by graywh** [awalker89/openxlsx#313]
## Expected Behavior
An empty data frame/table should produce an empty worksheet

## Actual Behavior
```
Error in sapply(colClasses, function(x) "formula" %in% x) & sapply(colClasses,  : 
  operations are possible only for numeric, logical or complex types
```

## Steps to Reproduce the Problem 

  1. `write.xlsx(list(A=data.frame()))`

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.4.1 (2017-06-30)

**Comment by akaever** [comment]
Same for `asTable = TRUE`:

`write.xlsx(x = data.frame(), file = "test.xlsx", asTable = TRUE)`

Maybe just check and then set `asTable = FALSE`.
