### ISSUE TITLE
Help: Building on Windows Fails

### ISSUE THREAD

**Issue by nicholaelaw** [awalker89/openxlsx#314]
Hi there, I've updated Rtools and packages like Rcpp, etc. But I'm still getting symbol not defined error when building the package. Anyone knows what's wrong with my setup?

Here's build output:
[build_msg.txt](https://github.com/awalker89/openxlsx/files/1201999/build_msg.txt)

And here's my `sessionInfo()`:

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.3

loaded via a namespace (and not attached):
 [1] httr_1.2.1     R6_2.2.2       tools_3.3.3    withr_2.0.0    rstudioapi_0.6 curl_2.8.1     memoise_1.1.0  knitr_1.16    
 [9] git2r_0.19.0   digest_0.6.12 
```

**Comment by awalker89** [comment]
The latest update to Rcpp broke openxlsx. I think this is fixed now. If you are still having issues please reopen this ticket.
Update with
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by nicholaelaw** [comment]
Sadly building still failed on my system. Here's the console output:

[build_msg.20170814.txt](https://github.com/awalker89/openxlsx/files/1221630/build_msg.20170814.txt)

I tried building by hand, all the `.o` files builds fine. However if I execute the command to build `openxlsx.dll` :

```
c:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o openxlsx.dll tmp.def RcppExports.o helper_functions.o load_workbook.o openxlsx_init.o read_workbook.o write_data.o write_file.o write_file_2.o -LC:/swarm/workspace/External-R-3.3.3/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.3.3/vendor/extsoft/lib -LC:/PROGRA~1/MICROS~2/ROPEN~1/bin/x64 -lR
```

`g++` would report that it couldn't find `tmp.def`. Removing `tmp.def` from that line, it built fine. But I don't know if it was built correctly. I hope this helps.
