### ISSUE TITLE
Minor:  Two Typos (spelling mistakes) in Merge Cells error message

### ISSUE THREAD

**Issue by cbailiss** [awalker89/openxlsx#319]
## Expected Behavior
Attempting to merge cells where merged cells already exist should give the following error:
Merge intersects with **existing** merged cells: 
		A5:A6.
Remove **existing** merge first.

## Actual Behavior
The following error (typo, missing "s") is received:
Merge intersects with **exisiting** merged cells: 
		A5:A6.
Remove **exiting** merge first.

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.4.1

**Comment by awalker89** [comment]
Thank you.
