### ISSUE TITLE
File corruption after loading and saving

### ISSUE THREAD

**Issue by manuSrep** [awalker89/openxlsx#320]
## Expected Behavior
The .xlsx file should not change after loading a wb and saving the wb.

## Actual Behavior
The formatting gets completely corrupted when using openxlsx but everything works fine for XLConnect 

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

library(openxlsx)
wb <- openxlsx::loadWorkbook("corruption.xlsx")
openxlsx::saveWorkbook(wb,"corruption_occured.xlsx")

[corruption.xlsx](https://github.com/awalker89/openxlsx/files/1241077/corruption.xlsx)

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: Microsoft R Open 3.3.3

**Comment by awalker89** [comment]
Thank you for the reproducible example. This should be fixed now.
Please update with
