### ISSUE TITLE
Include a vignette for all the possible premade tableStyles

### ISSUE THREAD

**Issue by hansthompson** [awalker89/openxlsx#322]
I think it would be valuable to have a vignette that produces a gallery of excel styles with names attached. 

If I look in excel 2013 I can see the different premade options visually but I can't find the name of them. 

I put together this small code chunk to output an xlsx with what looks like the options in the validNames object in the writeDataTable function that holds the possible options.  

I'd be happy to either submit a pull request or have the chunk altered how you see fit and incorporated by yourself. 

```
wb <- createWorkbook(paste0("tableStylesGallery.xlsx"))

addWorksheet(wb, "Style Samples")

for(i in 1:21) {
  writeDataTable(wb, tableStyle = paste0("TableStyleLight", i), startRow = 1, startCol = i * 3 - 2, sheet = 1, 
                 x = data.frame(Style = paste0("TableStyleLight", i)))
}

for(i in 1:28) {
  writeDataTable(wb, tableStyle = paste0("TableStyleMedium", i), startRow = 4, startCol = i * 3 - 2, sheet = 1, 
                 x = data.frame(Style = paste0("TableStyleMedium", i)))
}

for(i in 1:11) {
  writeDataTable(wb, tableStyle = paste0("TableStyleDark", i), startRow = 7, startCol = i * 3 - 2, sheet = 1, 
                 x = data.frame(Style = paste0("TableStyleDark", i)))
}


saveWorkbook(wb, file = paste0("tableStylesGallery.xlsx"), overwrite = TRUE)
```

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.4.0 (You Stupid Darkness :laughing: )

**Comment by awalker89** [comment]
Thank you for the suggestion and code. I have included this in `?writeDataTable`
