### ISSUE TITLE
Corrupt Excel when saving a variable with a new line as Table

### ISSUE THREAD

**Issue by kerry-ja** [awalker89/openxlsx#323]
## Expected Behavior
When saving a data frame with a variable name that has a new line to Excel as a Table, it is expected that the Excel file will open without error and have the data frame as a table

## Actual Behavior

The Excel file when opened says 

> "We found a problem with some content in 'Corrupt.xlsx' Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

After Excel repairs the content, the workbook is as expected.
[Corrupt.xlsx](https://github.com/awalker89/openxlsx/files/1282055/Corrupt.xlsx)

## Steps to Reproduce the Problem 
```
library(openxlsx)
write.xlsx(data.frame(`colA\nLine2` = "Foo", colB = "Bar",check.names = FALSE), 
           file="Corrupt.xlsx", asTable = TRUE)](url)
```

## sessionInfo()

  - Version of openxlsx: openxlsx_4.0.17
  - Version of R: 3.4.1 (2017-06-30)

**Comment by awalker89** [comment]
This should work now
```
## write
wb <- write.xlsx(data.frame(`colA\nLine2` = "Foo", colB = "Bar",check.names = FALSE), file="Corrupt.xlsx", asTable = TRUE)
addStyle(wb, sheet = 1, style = createStyle(wrapText = TRUE), rows = 1, cols = 1:2)


## check (set heights & widths so can see multiple lines)
setRowHeights(wb, sheet = 1, rows = 1:2, heights = 40) 
setColWidths(wb, sheet = 1, cols = 1:2, widths = 40)
saveWorkbook(wb, file = "Corrupt.xlsx", overwrite = TRUE)
openXL("Corrupt.xlsx")
```
