### ISSUE TITLE
Corrupt Excel file if inserting more than 10 plots

### ISSUE THREAD

**Issue by Gjermund06** [awalker89/openxlsx#325]
## Expected Behavior
Insert one plot per sheet for n sheets.

## Actual Behavior
If n > 10, Excel file is corupt. (Excel warning on opening file).
When comparing worksheet tab name and plot title they are not aligned.
Worksheet tab 10 have corrupt image.
[hm.xlsx](https://github.com/awalker89/openxlsx/files/1302079/hm.xlsx)

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

####################################
test_to_excel <- function(file_xlsx, sheet, obj) {
  if (file.exists(file_xlsx)) {
    wb <- loadWorkbook(file_xlsx)
  }
  else {
    wb <- createWorkbook(creator = 'MyName')
  }
  addWorksheet(wb, sheet)
  
  windows()
  x <- 1:10; y <- x + rnorm(10, 0, 2)
  plot(x, y, main=sheet)
  insertPlot(wb, sheet, width = 12, height = 8)
  dev.off()
 
  saveWorkbook(wb, file_xlsx, overwrite = T)
  
  invisible(NULL)
}

###############
## Main
library(openxlsx)
file_xlsx = 'failed.xlsx'
for (i in 1:15) {
  sheet <- paste0('sheet', i)
  test_to_excel(file_xlsx, sheet)
}

## sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
[1] openxlsx_4.0.17

**Comment by Gjermund06** [comment]
The following code works, so it must be realted to multiple load/save Workbook

###########################
test2_to_excel <- function(file_xlsx, n=1) {
  if (file.exists(file_xlsx)) {
    file.remove(file_xlsx)
  }
  wb <- createWorkbook(creator = 'MyName')

  for (i in 1:n) {
    sheet = paste0('sheet', i)
    addWorksheet(wb, sheet)
    
    x <- 1:10; y <- x + rnorm(10, 0, 2)
    plot(x, y, main = sheet)
    insertPlot(wb, sheet)
  }
  
  saveWorkbook(wb, file_xlsx, overwrite = T)
 
  invisible(NULL)
}

**Comment by awalker89** [comment]
Thank you for the bug report. Should be fixed now.
