### ISSUE TITLE
Datetime values are truncated to 2 decimal places in xlsx/xml file

### ISSUE THREAD

**Issue by kbzsl** [awalker89/openxlsx#327]
## Expected Behavior

Correct time data in the excel file: to write the real and not truncated datetime values in the xlsx file.  

## Actual Behavior

All the datetime values truncated to 2 decimal places in xlsx, which leads to wrong time values in the xlsx.
For example (xl\worksheets\sheet1.xml ):  `<c r="B2" s="1" t="n"><v>40699.21</v></c>`

I tried different settings for numFmt, without any success. 

## Steps to Reproduce the Problem 

I used the following R script for testing (these libraries are used in the real application):

```
library(tidyverse)
library(openxlsx)
library(lubridate)

tdf <- tibble(n = sample(365, 10), 
       time_value = now() -  dseconds(1234567 * n))

wb <- createWorkbook()
addWorksheet(wb, "time")
writeDataTable(wb, "time", tdf, tableName = "time")
# freezePane(wb, "time", firstRow = TRUE) 
# addStyle(wb, "time", style = createStyle(numFmt = "#,##0.0"), rows = 2:(1+nrow(tdf)), cols = 1, gridExpand = FALSE)
addStyle(wb, "time", style = createStyle(numFmt = "LONGDATE"), rows = 2:(1+nrow(tdf)), cols = 2, gridExpand = FALSE)

saveWorkbook(wb, file = "tdf_test.xlsx", overwrite = TRUE)
```

## sessionInfo()

‘openxlsx’ version 4.0.17

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252 
```

**Comment by awalker89** [comment]
This has been fixed in the latest dev version on github.
