### ISSUE TITLE
Corrupted Excel spreadsheet - excel unable to recover document

### ISSUE THREAD

**Issue by lance-buick** [awalker89/openxlsx#328]
I have recently installed the 3.4.0 version of R and I am trying to get some useful openxls R script running again.
## Expected Behavior
When creating a new empty workbook, using openxlsx, add a blank worksheet and saving file, I expect the new workbook to open in MS Excel 2016 without errors.

## Actual Behavior
When creating a new empty workbook, adding an empty worksheet, then saving workbook, MS Excel 2016 fails to open and recover the workbook.
A xlsx file with the expected filename and extension is created in the destination directory. Excel 2016 states file is corrupt and fails to recover it.

Note 1: I can successfully use the read file and openXL functions on my PC, from the openxlsx library. The issues seems limited to the creating and saving of a new workbook.
I have spent a couple of hours pulling apart my R script, to get to the basic failure scenario. All I need to do is create a new workbook, add an empty worksheet and save.
Note 2: I have tested multiple variations on fixed filenames, fixed path and actual flename to try and isolate the issue.
Note 3: I have successfully run the same testing sceanrios using XLConnect, with no issues. The XLConnect created workbook has no issues.
I abandonded XLConnect as soon as openxls was written, saving me from various issues processing large datasets. I would really like to continue using openxlsx... to write workbooks.
Note 4: I receive a warning when I load the openxlsx library, built under R 3.1.4 , sorry if this is why I'm getting the error. Was expecting the library to work based on its past stable history.

##################################################
Update: 2.10.2017:: NB: I have WinZip insatlled on my PC.
I have tested the shell("zip") : received the following:

zip error: Internal logic error (fstat(stdin))
Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c zip' had status 5 
2: In shell("zip") : 'zip' execution failed with error code 5

#################################################

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. Use create procedure to create a new workbook
  
  2. Add a blank worksheet.
  
  3. Save workbook on local PC harddrive.

4. When attempting to open workbook in Excel 2016, Excel states file corrupt, attempts to recover document, fails to recover document and states contents corrupt.

Uploaded an example of error workbook: 26.9.2017
## sessionInfo()

  - Version of openxlsx:
Latest version: 4.0.17
  - Version of R: 3.4.0
Win 64bit distribution R, downloaded from CRAN

-- Updated 26.9.2017
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

-- Updated 2.10.2017 : WinZip is installed on my PC
WinZIP version
WinZIP 21.5 (21480) Pro 64-bit

Running on a Windows 10 64bit Enterprise Edition laptop
MS Excel 2016

**Comment by awalker89** [comment]
I am unable to reproduce this error - can you please update to the latest dev version and test again.
`devtools::install_github("awalker89/openxlsx")`

Please re-open the issue if it's still a problem.

**Comment by CameronGSnow** [comment]
@awalker89 FYI - I encountered a similar error when trying to save a workbook I had previously loaded that had filters on an existing tab. When I removed the filters, saved the workbook, and reloaded it I was able to save the new workbook just fine. I'm not sure they're related but I wanted to share.

**Comment by csetzkorn** [comment]
I encountered similar issues

**Comment by csetzkorn** [comment]
In my case I isolated the problem to the sheet names containing "special" (????) characters like:

?

Removing them solved my issue.
