### ISSUE TITLE
small numbers lead to corrupt files in tables, but not in sheets

### ISSUE THREAD

**Issue by yasirs** [awalker89/openxlsx#332]
## Expected Behavior
The saved xlsx files should open in Excel without errors.

## Actual Behavior
The file with the data saved as a table opens  with an error.

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. Write the Excel files

```
library(openxlsx)
openxlsx::write.xlsx(data.frame(a=c(1,2),b=c(1e-294,1e-10)), file = "corrupt.xlsx", asTable = T)
openxlsx::write.xlsx(data.frame(a=c(1,2),b=c(1e-294,1e-10)), file = "notcorrupt.xlsx", asTable = F)
```  
  2. Open the files in Excel
  
## sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

openxlsx version 4.0.17

  - Version of openxlsx:
  - Version of R:

## Here are the files:

[notcorrupt.xlsx](https://github.com/awalker89/openxlsx/files/1350718/notcorrupt.xlsx)
[corrupt.xlsx](https://github.com/awalker89/openxlsx/files/1350719/corrupt.xlsx)

**Comment by awalker89** [comment]
This has been fixed in the latest dev version ( 4.0.30). Please update with 
```
devtools::install_github("awalker89/openxlsx")
```
