### ISSUE TITLE
flexibility for sheetName length

### ISSUE THREAD

**Issue by munrosa** [awalker89/openxlsx#336]
## Feature Request
Thanks for openxlsx. I'm using it to replace the use of xlsx, which seems to be having rJava dependency issues.

Can you remove the hard limit of 31 characters for sheetNames? Or at least make it possible to exceed this limit. I'm rewriting someone's code that used xlsx with openxlsx, and now I'm getting the error "sheetName too long! Max length is 31 characters." For consistency I want to continue using the long names that my colleagues were using in their files.

## sessionInfo()

  - Version of openxlsx: ‘4.0.17’
  - Version of R: 3.4.2

**Comment by bishop22** [comment]
Microsoft Excel limits worksheet names to 31 characters, so I don't think
increasing the limit in this package is prudent.

**Comment by munrosa** [comment]
Yeah it looks like the limit is enforced in the xlsx package too, but instead of throwing an error xlsx truncates the sheetName and writes the file. Instead of openxlsx stopping with an error an alternative would be to throw a 31 character warning and truncate the name. That way the file is still written, and the user is warned about Excel's character limits.

**Comment by awalker89** [comment]
I agree with @bishop22. Not going to change this.

**Comment by Saren-T** [comment]
Actually the file format allows 255 but the UI doesn't.
