### ISSUE TITLE
Feature request : read a sheet from a Workbook object

### ISSUE THREAD

**Issue by jomuller** [awalker89/openxlsx#34]
The `loadWorkbook()` function allow to create a `Workbook` object from a _xlsx_ file. I didn't find any function to transform a sheet from this object to a data.frame. I tried `read.xlsx` and `readWorkbook` but both read from a file, not from an `Workbook` object.

Then a `readSheet` function, or, better, a method `read.xlsx` for `Workbook` should be useful.

If this function already exists, maybe add the name of this function in the document page of the `loadWorkbook()` function.

And thank you again for this very useful package.

**Comment by christation** [comment]
+1
