### ISSUE TITLE
Special characters in sheet names

### ISSUE THREAD

**Issue by mattantaliss** [awalker89/openxlsx#341]
It seems there is an issue with extracting and using sheet names when special characters are included. Here is an [example file](https://github.com/awalker89/openxlsx/files/1489109/Sheet_Names_Example.xlsx) and code:

```
library(openxlsx)

tmp.file <- loadWorkbook("Sheet_Names_Example.xlsx")

sht.name.1 <- names(tmp.file)
sht.name.2 <- tmp.file$sheet_names

read.xlsx(tmp.file, sheet = sht.name.1)
read.xlsx(tmp.file, sheet = sht.name.2)
```

## Expected Behavior

1. sht.name.1 and sht.name.2 should be the same
2. Both read.xlsx lines should execute properly

## Actual Behavior

1. sht.name.1 is "Hello & World" while sht.name.2 is "Hello &amp; World"
2. The read.xlsx line that uses sht.name.1 produces the following error: `Error in read.xlsx.Workbook(tmp.file, sheet = sht.name.1) : 
  Cannot find sheet named "Hello & World"` while the one that uses sht.name.2 reads the file correctly.

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. Execute the above code from a clean session (using the attached example file)

## sessionInfo()
  - Version of openxlsx: 4.0.17
  - Version of R: 3.3.2

**Comment by awalker89** [comment]
This works now
```
fl <- "Sheet_Names_Example.xlsx"
wb <- loadWorkbook(fl)

sht.name.1 <- names(wb)
getSheetNames(fl)

read.xlsx(fl, sheet = sht.name.1)
read.xlsx(wb, sheet = sht.name.1)
```
