### ISSUE TITLE
cannot read sheets with ampersands in sheet name

### ISSUE THREAD

**Issue by jaydennord** [awalker89/openxlsx#349]
## Expected Behavior

Expected to read sheet.

## Actual Behavior

Error occurs if sheet name contains ampersand; says cannot find sheet.

## Steps to Reproduce the Problem 

File: [example.xlsx](https://github.com/awalker89/openxlsx/files/1607826/example.xlsx)
```
library(openxlsx)
d1 <- read.xlsx("example.xlsx", sheet = "this good")
d2 <- read.xlsx("example.xlsx", sheet = "this&bad") # throws error
# Error in read.xlsx.default("example.xlsx", sheet = "this&bad") : 
#   Cannot find sheet named "this&bad"
```

## sessionInfo()

  - Version of openxlsx: 4.0.17
  - Version of R: 3.3.3

**Comment by awalker89** [comment]
This has been fixed in the latest dev verision on github. Please update with
`devtools::install_github("awalker89/openxlsx")`
