### ISSUE TITLE
write.xlsx() writes dates (POSIXct format) inconsistently

### ISSUE THREAD

**Issue by courageup** [awalker89/openxlsx#350]
## Expected Behavior
Dates of "11/1/2017 (1-Nov-2017)" should be written to Excel as Date 11/1/2017

## Actual Behavior
Dates of "11/1/2017 (1-Nov-2017)" were written to Excel as "10/31/2017  4:00:00 PM" (see the "my2.xlsx" file using the code below)
## Screenshot
![s180115_124122](https://user-images.githubusercontent.com/15612572/34927482-7d93dbd4-f9f1-11e7-8079-f160195aae84.png)

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)
```{r}
# unzip the file "Mydata.rds.gz", you'll get the r binary file "Mydata.rds" which was a simplified version
#  from a data pull from an Oracle database using ROracle packages.
require(openxlsx)
my2<-readRDS("Mydata.rds")
write.xlsx(my2,"my1.xlsx")
str(my2)
my2[1:10,2]<-NA
write.xlsx(my2,"my2.xlsx") ## strange dates happened
sessionInfo()
```

## sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.0.17

loaded via a namespace (and not attached):
[1] tools_3.3.2 Rcpp_0.12.9

  - Version of openxlsx: 4.0.17
  - Version of R: 3.3.2 (2016-10-31)

## attachments:
[Mydata.rds.gz](https://github.com/awalker89/openxlsx/files/1630382/Mydata.rds.gz)

**Comment by courageup** [comment]
Here are my output files using the r code.
[my2.xlsx](https://github.com/awalker89/openxlsx/files/1630395/my2.xlsx)
[my1.xlsx](https://github.com/awalker89/openxlsx/files/1630396/my1.xlsx)

**Comment by awalker89** [comment]
Thank you for the bug report and reproducible example. This should be fixed now. Please update with 
```
devtools::install_github("awalker89/openxlsx")
```
If you still have issues please reopen the issue.

**Comment by courageup** [comment]
Thank you very much for your prompt response ans solution.
After updating the package using your code, the issue is resolved.

**Comment by mos790** [comment]
Hi, 
Unfortunately get the same result, can you fix it ? thanks in advance
Edit : I changed the format to date on Excel file directly, the job is done :)
Thanks for your work
