### ISSUE TITLE
openxlsx

### ISSUE THREAD

**Issue by SheelaPkasbekar** [awalker89/openxlsx#353]
## Expected Behavior

I am unabele to down load openxlsx from cran

Please help.
Thanks
Sheela
## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.
  
  2.
  
  3.

## sessionInfo()

  - Version of openxlsx:
  - Version of R:

**Comment by awalker89** [comment]
install.packages("openxlsx")
