### ISSUE TITLE
Feature request: allow column specification using column header names

### ISSUE THREAD

**Issue by burgerga** [awalker89/openxlsx#361]
I often create named regions to extract data from large excel files and currently I need to convert the usual column headers (e.g. C, K, AC, BZ) to numeric values. I would be nice if I could just insert the columns as they appear in excel. This could be done in a similar way as `cols()` in the `readr` package. Example of (would-be) equivalent calls:

```r
createNamedRegion(..., cols =  25:27, ...)
createNamedRegion(..., cols =  colRange('Y', 'AA'), ...)
```

https://stackoverflow.com/a/34537691/1439843 can be used to convert the letter values to numeric values.

**Comment by smingerson** [comment]
See ?openxlsx::convertFromExcelRef 
That appears to be what you want, and you could always do `colRange <- convertFromExcelRef` for a more convenient name.

**Comment by smingerson** [comment]
See ?convertFromExcelRef. It is not quite what you want, since it takes a vector as opposed to an unspecified # of arguments. You could do something like the below if you *really* wanted to not enter as a vector.
`colRange <- function(...) {
  cols <- c(...)
  convertFromExcelRef(cols)
}
`

**Comment by smingerson** [comment]
How about this? 
```
library(openxlsx)
colRange <- function(start, end) {
  ind <- convertFromExcelRef(c(start, end))
  ind[1]:ind[2]
}
colRange('y', 'aa')
# 25 26 27
```

**Comment by burgerga** [comment]
I searched through the manual before posting but still missed it, this will work, thanks!
