### ISSUE TITLE
Change return value of read.xlsx() from data.frame to tibble

### ISSUE THREAD

**Issue by timvink** [awalker89/openxlsx#364]
I suspect there are many people who have this type of code:

```r
openxlsx::read.xlsx(file) %>% tibble::as_tibble()
```

[tibble](https://github.com/tidyverse/tibble) is a modern reimagining of the data.frame and part of the tidyverse. It also prints your data.frames in a more useable fashion. 

Could we change the return type of `read.xlsx()` to a tibble? Alternatively, we could make a tidyverse function called `read_xlsx()` which returns a tibble instead. The tidyverse recommends to use underscores instead of dots. 

Happy to submit a pull request if you agree.

**Comment by awalker89** [comment]
I don't think it's worth adding a package dependency just for this.
