### ISSUE TITLE
return data.tables

### ISSUE THREAD

**Issue by ycphs** [awalker89/openxlsx#366]
## Expected Behavior

Option to return data.table from read.xlsx

`library(data.table)`
`libraryy(openxlsx)`
`x<-read.xlsx("testfile.xlsx",asdatatable=T)`

## Actual Behavior

`library(data.table)`
`libraryy(openxlsx)`
`x<-read.xlsx("testfile.xlsx")`
`setDT(x)`

**Comment by awalker89** [comment]
I don't think it's worth adding a package dependency just for this.
`x<-as.data.table(read.xlsx("testfile.xlsx"))`
