### ISSUE TITLE
GetSheetNames function no longer working

### ISSUE THREAD

**Issue by flachboard** [awalker89/openxlsx#367]
## Expected Behavior
Return a vector of sheet names

## Actual Behavior
Receiving an error (unfortunately don't have the exact error message on hand)

  - Version of openxlsx: 4.0.17
  - Version of R: 3.4.1

**Comment by awalker89** [comment]
Works for me - reopen if you have a reproducible example.
```
> getSheetNames(system.file("readTest.xlsx", package = "openxlsx"))
 [1] "Sheet1"  "Sheet2"  "Sheet 3" "Sheet 4" "Sheet 5" "Sheet 6" "1"       "11"      "111"     "1111"    "11111"   "111111" 
```
