### ISSUE TITLE
Opening and writing in xlsm files (with macros preserved)

### ISSUE THREAD

**Issue by itssimon** [awalker89/openxlsx#37]
openxlsx does not seem to work with *.xlsm files containing macros. What I'm trying to do is opening a xlsm file, writing some data and saving it. The file extension xlsx is being added automatically, resulting in a .xlsm.xlsx with all macros removed.

The package xlsx on the other hand does not have any issues with xlsm.

**Comment by pooranis** [comment]
I think it's because of line 87 in the loadWorkbook.R code:
```
on.exit(expr = unlink(xmlFiles[!grepl("charts|media|vmlDrawing|comment|embeddings|pivot|slicer", xmlFiles, ignore.case = TRUE)
```

If you add "vbaProject" as one of the things not to remove in the grep statement, then it works like a champ.  

Thanks so much to the developer for this R package, by the way.  It works great, and is so helpful.

**Comment by LeeVondrak** [comment]
I am having the same issue as @itssimon. How do you change the code of the grep statement of loadWorkbook.R? Thanks

**Comment by ksak3** [comment]
This seems to suggest that writing to XLSM files is supported but I am having trouble even with a toy example. I created a small worksheet and then did File -> Save As -> Macro-Enabled Workbook. When I run this code Excel returns a message saying that the file type doesn't match the extension. I've also run it for a larger complex XLSM file and the message is different and it tries and fails to repair it. Am I missing something?

`wb = loadWorkbook(xlsxFile = "test.xlsm")
writeData(wb, sheet = "Sheet1", x = mtcars)
saveWorkbook(wb, file = "xlsmtest.xlsm", overwrite = TRUE)`

**Comment by petbadger** [comment]
Just jumping into this thread to say that the "toy example" provided by @ksak3 worked for me.  

Note that if you open xlsm files, you need to appropriately set MS Excel and LibreOffice Calc security settings.

**Comment by ksak3** [comment]
Thanks @petbadger but what security settings are you referring to? I tried fiddling with Macro Settings in Trust Center but no luck. Even without the writeData step, just loading and saving.

**Comment by petbadger** [comment]
My comment about the security settings was only a general tip for those struggling to _manually_ run macros in their spreadsheets. Say a person uses this R code to save the macro workbook.  Then they go to open the workbook but the macro doesn't run.  They might think the R code didn't do it's job when in fact it's the security settings of their spreadsheet software is prohibiting the macro from running.

**Comment by ksak3** [comment]
In any case I still can't modify xlsm files, and loading and saving reduces the file size and corrupts the workbook. I tried in Windows and Linux using openxlsx 4.0.17:
wb = loadWorkbook(file = "~/test.xlsm")
saveWorkbook(wb, file = "~/test2.xlsm")
and I get the same error messages.  A workbook with macros that I can open fine reduces in file size from  1200K to 970K and is corrupted after loading and saving. This may just be a documentation issue but I note that loadWorkbook help says the file can be xlsx or xlsm, while saveWorkbook help just mentions xlsx. I can view sheetnames, etc. for the workbook object in R.

**Comment by petbadger** [comment]
Here is some code I am using.  When I save the new file, even without writing any data to it, it increases the file size 2.5 times the size.  But the file is not corrupt. Perhaps the data you are writing is corrupt itself? Perhaps some strange encoding?

#install.packages("openxlsx")
library(openxlsx) 

setwd("~/Desktop")

file_template <- "xlsm_test.xlsm" #file size 6.4 kB
file_generated <- "copied_xlsm_test.xlsm"
file.copy(from = file_template, to = file_generated, overwrite = TRUE)

wb = loadWorkbook(xlsxFile = file_generated) 
#random_mat <- replicate(10, sample(1:255))
#writeData(wb, sheet = "Sheet1", x = random_mat, colNames = FALSE, rowNames = FALSE) 

saveWorkbook(wb, file = file_generated, overwrite = TRUE) #file size 16.7 kB
#Can also just save it to a new file without doing the file copy
saveWorkbook(wb, file = "copied_xlsm_test_2.xlsm", overwrite = TRUE) #file size 16.7 kB

**Comment by Atan1988** [comment]
I think the problem is with a xlsm file without actual macro in it. 
When the xlsm file loaded in is without a macro, then when the file is saved out to .xlsm format, it would appear to be corrupted. However, changing the extension to .xlsx will make the file openable.
