### ISSUE TITLE
NA is not handled correctly for class hyperlink

### ISSUE THREAD

**Issue by kbzsl** [awalker89/openxlsx#370]
## Expected Behavior
to create a hyperlink for each cell containing an URL string 
but to leave the empty (NA) cells empty and without any hyperlink

## Actual Behavior
in case of the missing data (NA) the hyperlink from the consecutive cell is inserted erroneously for the empty cell
and the hyperlinks are rolled in advance for every consecutive cell (check the hyperlinks from the last line)

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. code to reproduce the fault

		table <- tribble(
		  ~amazon, ~ebay, ~rakuten,
		  "https://www.amazon.com/", "https://www.ebay.com/", "https://www.rakuten.com/",
		  "https://www.amazon.com/", "https://www.ebay.com/", "https://www.rakuten.com/",
		  "https://www.amazon.com/", NA, "https://www.rakuten.com/",
		  "https://www.amazon.com/", "https://www.ebay.com/", "https://www.rakuten.com/"
		)

		class(table$amazon) <- "hyperlink"
		class(table$ebay) <- "hyperlink"
		class(table$rakuten) <- "hyperlink"

		wb <- createWorkbook()
		addWorksheet(wb, "url")
		writeDataTable(wb, "url", table, tableName = "url")
		freezePane(wb, "url", firstRow = TRUE) 
		saveWorkbook(wb, file = "fault.xlsx", overwrite = TRUE)

  2.
  
![image](https://user-images.githubusercontent.com/15076626/37536094-eea6d506-2949-11e8-8994-e5e9c77ebc6a.png)

  3.

## sessionInfo()

  - Version of openxlsx: openxlsx_4.0.17
  - Version of R: 3.4.2 (2017-09-28)

**Comment by awalker89** [comment]
Thank you for the reproducible example.
