### ISSUE TITLE
Error loading an xlsx file

### ISSUE THREAD

**Issue by nmolanog** [awalker89/openxlsx#386]
## Expected Behavior
To load the workkbook in environment

## Actual Behavior
Error in fonts[[(as.integer(s[["fontId"]]) + 1)]] : 
  subscript out of bounds

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1. library(openxlsx)
  
  2. wb <- loadWorkbook(file = "Sjö-Subjets22032018 - Unificado (DEF).xlsx")

## sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS
openxlsx_4.0.17
[Sjö-Subjets22032018 - Unificado (DEF).xlsx](https://github.com/awalker89/openxlsx/files/1995490/Sjo-Subjets22032018.-.Unificado.DEF.xlsx)

**Comment by nmolanog** [comment]
Thanks

**Comment by sanjmeh** [comment]
Sorry but how is this closed? I still get the same error from a perfectly valid xlsx file that is easily read by read_excel(). 
But the loadWorkbook() gives the same error.

```
Error in fonts[[(as.integer(s[["fontId"]]) + 1)]] : 
  subscript out of bounds
```

I use openxlsx 4.1.0

**Comment by srearl** [comment]
Curious the status of this issue as I am getting the same error:

`loadWorkbook(file = 'path/master2.xlsx')`

is yielding...

Error in fonts[[(as.integer(s[["fontId"]]) + 1)]] : 
  subscript out of bounds

```
sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS
```

[master2.xlsx](https://github.com/awalker89/openxlsx/files/2583120/master2.xlsx)

This error is occurring with multiple Excel workbooks, one of which is attached. Not sure if this has anything to do with it, but these workbooks were downloaded from Google Drive where they existed initially as Google Sheets.


Thanks

**Comment by nmolanog** [comment]
You MUST install the developer version of the package, using devtools::install_github

**Comment by MonkieDein** [comment]
@nmolanog Thank you, can you write the exact github repo :) or the whole line of code .

**Comment by MonkieDein** [comment]
Exactly like what @nmolanog mentioned. 
# Some might need Rtools install separately as well :) Good luck
install.packages("Rcpp")
devtools::install_github("awalker89/openxlsx")

**Comment by srearl** [comment]
Thank you @nmolanog and @MonkieDein - that worked! There is a lot of new, unintended formatting (e.g., blocks of cells with now italicized and bold text) but the structure and functionality are there.
