### ISSUE TITLE
Incompatibility between openxlsx and XLConnect

### ISSUE THREAD

**Issue by manuSrep** [awalker89/openxlsx#389]
## Expected Behavior
Read excel file written with XLConnect

## Actual Behavior
Error in read.xlsx.default("test.xlsx") : 
  Expecting a single string value: [type=character; extent=0].

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)
 XLConnect::writeWorksheetToFile("test.xlsx",iris ,"Sheet")
  openxlsx::read.xlsx("test.xlsx")

## sessionInfo()
  - Version of openxlsx: 4.0.17
  - Version of XLConnect: 0.2-13
  - Version of R: 3.4.1

Would be nice if you have a look on your package. I guess the problem is not with XLConnect directly but by the underlying Java library because I have the same problem with other Java programs writing xlsx files.

Best Regargs
Manuel

**Comment by awalker89** [comment]
This works for me using
```
Version of openxlsx: 4.1.0
Version of XLConnect: 0.2.15
Version of R: 3.5.0
```
