### ISSUE TITLE
NAs get added to xlsx file from just opening and closing

### ISSUE THREAD

**Issue by ajdamico** [awalker89/openxlsx#398]
hi, thanks for the great software.  any idea why these NAs get added to the attached `test2 using 4_1_0.xlsx` file?  if the behavior is expected, a workaround would be great..  thank you!!

## Expected Behavior

loading & immediately saving an xlsx file results in zero changes to xlsx file

## Actual Behavior

NA text added in certain places

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

	# works fine with 4.0.17
	# devtools::install_version("openxlsx", version = "4.0.17", repos = "http://cran.us.r-project.org") 

	# fails using cran version
	# install.packages( 'openxlsx' )

	# fails using dev
	# devtools::install_github( "awalker89/openxlsx" )

	library(openxlsx)
	fn <- "C:/Users/AnthonyD/Desktop/test.xlsx"
	fn2 <- "C:/Users/AnthonyD/Desktop/test2.xlsx"
	this_wb <- loadWorkbook( fn )
	saveWorkbook( this_wb , fn2 )

[test.xlsx](https://github.com/awalker89/openxlsx/files/2186665/test.xlsx)
[test2 using 4_0_17.xlsx](https://github.com/awalker89/openxlsx/files/2186666/test2.using.4_0_17.xlsx)
[test2 using 4_1_0.xlsx](https://github.com/awalker89/openxlsx/files/2186667/test2.using.4_1_0.xlsx)

## sessionInfo()

  - Version of openxlsx: cran and dev fail, 4.0.17 works fine
  - Version of R: 3.5.1

**Comment by ycphs** [comment]
Please try to check the new current package and the new repository GitHub.com/ycphs/openxlsx

**Comment by ajdamico** [comment]
@ycphs  thank you!  i've verified this is still an issue and moved to https://github.com/ycphs/openxlsx/issues/72
