### ISSUE TITLE
Read dates as text

### ISSUE THREAD

**Issue by petrbouchal** [awalker89/openxlsx#40]
Currently `read.xlsx` in `openxlsx` returns dates as numbers, presumably the number of days from the relevant origin. 

But given the [inconsistency](http://support.microsoft.com/kb/180162) (also [here](http://stackoverflow.com/questions/15686451/dates-from-excel-to-r-platform-dependency)) of the origin in Excel between platforms, this date format is not straightforward to parse correctly. It would be more useful (and less error-prone) to instead return a string with the date as formatted in the relevant cell.

This would also make it consistent with the treatment of dates by the `xlsx` package.

**Comment by awalker89** [comment]
Working on this. will be an option to auto detect dates - may not be perfect as relies on detecting a cell style which "looks" like a date.
