### ISSUE TITLE
Worksheet order incorrect after writing

### ISSUE THREAD

**Issue by itssimon** [awalker89/openxlsx#50]
When opening an existing workbook, adding sheets to it and saving it, the sheets are not necessarily being added after the last existing sheet (intended), but after the first existing sheet. When calling worksheetOrder(wb) it does spit out the intended order, but writes it differently anyway.

Btw.: Thank you so much for your effort! I've posted a few issues now and I'm really glad that you're fixing them in almost no time! Keep up the good work!

**Comment by itssimon** [comment]
I've found one more quirk while adding sheets to an existing file. The existing sheets lose their tab color after saving.

**Comment by awalker89** [comment]
This should be fixed. Please close the issue once you have confirmed this now works as expected.

**Comment by itssimon** [comment]
Works fine now! Thanks!
