### ISSUE TITLE
error: invalid numFmt

### ISSUE THREAD

**Issue by williFiebranz** [awalker89/openxlsx#51]
Hi,

I wonder why I cannot define e.g. 

> s <- createStyle(numFmt = "0.00") 

while the manual/vignette says so.

Regards,
Willi

**Comment by awalker89** [comment]
Hi,

This works for me
```
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, 1, x = 1:10/7, startCol = 1)
writeData(wb, 1, x = 1:10/7, startCol = 2)

## apply style to column 1 only
s <- createStyle(numFmt = "0.00")
addStyle(wb, 1, style = s, rows = 1:10, cols = 1, gridExpand = TRUE)

openXL(wb)

```
![image](https://cloud.githubusercontent.com/assets/7400673/5884310/eb993eda-a3af-11e4-9c99-2993ed648d9a.png)


Please send me an example I can run myself if you are still having issues.

Thanks,
Alex
