### ISSUE TITLE
Plans for keeping openxlsx on CRAN

### ISSUE THREAD

**Issue by dpc10ster** [awalker89/openxlsx#518]
I received an email from CRAN saying that `openxlsx` will be archived on Sept 25 if issues are not addressed. See partial copy of email from CRAN below.

My package, which depends on openxlsx, and several others, will also be archived. 

Would appreciate knowing your plans to fix the cited issues. Your package is very useful and I would hate to lose it.

> We have asked for an update fixing the check problems shown at
  <https://cran.r-project.org/web/checks/check_results_openxlsx.html>
with no update from the maintainer thus far.

> Thus, package openxlsx is now scheduled for archival on 2020-09-25, and
archiving this will necessitate also archiving its strong reverse
dependencies.

> Please negotiate the necessary actions.

> The CRAN Team

**Comment by ycphs** [comment]
Could you please create this also at [ycphs/openxlsx](https://github.com/ycphs/openxlsx)?

I am maintaining the active fork of the package.
