### ISSUE TITLE
Encoding issue in read.xlsx

### ISSUE THREAD

**Issue by Ronggui** [awalker89/openxlsx#52]
> read.xlsx("c:/book1.xlsx",sheet=1)
Error in tolower(sharedStrings) : invalid multibyte string 4

Original code in read.xlsx function:
        z <- tolower(sharedStrings)
        sharedStrings[z == "true"] <- "TRUE"
        sharedStrings[z == "false"] <- "FALSE"

Can be revised as follows:
        z <- tolower(sharedStrings)
        Encoding(z) <- "UTF-8"
        sharedStrings[z == "true"] <- "TRUE"
        sharedStrings[z == "false"] <- "FALSE"

**Comment by awalker89** [comment]
Hi thanks for this.
Can you please sent me an example workbook which produces this error to Alexander.Walker1989@gmail.com 

I'd like to add this to the package unit tests.
Thanks,
Alex

**Comment by awalker89** [comment]
This should be fixed now.

**Comment by eolembrain-leo** [comment]
Hi! I'm working with data including Chinese multibyte string.
When using read.xlsx, if there's "any" Chinese character in any place(even in the sheet which not to be read), it will cause error as below

        # Error in tolower(sharedStrings) : invalid multibyte string 414

or

         # Error in tolower(sharedStrings) : invalid multibyte string 2
