### ISSUE TITLE
xlsx-files written by writexl::write_xlsx cannot be read by openxlsx::read.xlsx

### ISSUE THREAD

**Issue by Close-your-eyes** [awalker89/openxlsx#526]
## Expected Behavior
Reading an excel file with data on it into R.

## Actual Behavior
A warning message appears: 
Warning message: No data found on worksheet.

## Reason:
I believe xlsx-files that were written previously with the write_xlsx from with writexl-package cannot be read. Something in the formatting may be wrong. So, this may be actually be a problem on the writexl-package but not only ...
Can this be fixed? So, that read.xlsx handles the putatively wrong formatting of xlsx files written with write_xlsx?

## Solution, even though not satisfying:
Open the xlsx file with excel first and save again. Then read.xlsx can read it.

## Steps to Reproduce the Problem 

  1. Save data to a xlsx file with writexl::write_xlsx.
  
  2. Try to read it with openxlsx::read.xlsx.
  
  3. Get an error.
  
  4. Repair it by opening with excel. Alternatively though, it would be great if read.xlsx could handle it.

## sessionInfo()

  - Version of openxlsx: 4.2.3
  - Version of R: 4.0.3
  - System: MacOS

example-file for reproduction:
[example.xlsx](https://github.com/awalker89/openxlsx/files/5861961/example.xlsx)

**Comment by ycphs** [comment]
Could you please create this also at [ycphs/openxlsx](https://github.com/ycphs/openxlsx)?

I am maintaining the active fork of the package.
