### ISSUE TITLE
Request: colIndex and rowIndex

### ISSUE THREAD

**Issue by jasonpbecker** [awalker89/openxlsx#53]
This is a really killer effort. I wonder if you would consider adding the option to `read.xls` to indicate which rows and columns you want to import. I frequently get data sourced that has stuff pasted all over in various cells and I would love to drop `xlsx` as a dependency so I don't have to use `rJava`.

**Comment by awalker89** [comment]
Added parameters "rows" & "cols" to read.xlsx to specify which rows and columns to read.

```
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, 1, iris)
x <- read.xlsx(wb, sheet = 1, rows = 1:5, cols = 1:3)
x
```

**Comment by jasonpbecker** [comment]
Working great. Thanks for the quick response!
