### ISSUE TITLE
conditionalFormat with a specific value from a varible

### ISSUE THREAD

**Issue by SangHLee** [awalker89/openxlsx#54]
I have a numerical variable with one value.
```R
mean_a <- mean(df$a)
```
Now, I would like to use this value for conditional formatting on all cells in column number 2. 

```R
conditionalFormat(df_wb, 1, cols = 2, rows=2:(nrow(df)+1), rule='>=mean_a', style = posyellowflagStyle)
```

However, above conditionalFormat line does not work. 

Can one use a variable value to set rule in conditionalFormat function?

Thank you for your help!

**Comment by fpbarthel** [comment]
Use: rule=sprintf('>=%s',mean_a)

**Comment by SangHLee** [comment]
Thank you @fpbarthel ! It worked. 

I have another question regarding conditional formatting between values. 

I want to have rule that formats cell colour to yellow, if the cell value is equal and/or greater than mean_a. Also, for the same column, if the cell value is equal and/or greater than mean_b, format the cell colour to red. (given mean_a < mean_b)

Code below is what I tried, but it does not work...

Any hints? Thank you!

```R

conditionalFormat(df_wb, 1, cols = 5, rows=2:(nrow(df)+1), rule=sprintf('>=%s',mean_a), style = posyellowflagStyle)

conditionalFormat(df_wb, 1, cols = 5, rows=2:(nrow(df)+1), rule=sprintf('>=%s',mean_b), style = posredflagStyle)
```

**Comment by SangHLee** [comment]
Never mind, I used ifelse statement.

```R
ifelse(df$a >= mean_b, conditionalFormat(df_wb, 1, cols = 5, rows=2:(nrow(df)+1), rule=sprintf('>=%s',mean_b), style = posredflagStyle), conditionalFormat(df_wb, 1, cols = 5, rows=2:(nrow(df)+1), rule=sprintf('>=%s',mean_a), style = posyellowflagStyle))
