### ISSUE TITLE
restoring of initial option scipen fails

### ISSUE THREAD

**Issue by petersteiner** [awalker89/openxlsx#55]
```
> getOption("scipen")
[1] 0
> 
> wb <- createWorkbook()
> addWorksheet(wb, "Cars")
> 
> x <- mtcars[1:6,]
> writeData(wb, "Cars", x, startCol = 2, startRow = 3, rowNames = TRUE)
> 
> getOption("scipen")
$scipen
[1] 0
```

Instead of `options("scipen")`, you should use `getOption("scipen")` instead within the following functions:

    - wrappers.R
    - writeData.R
    - writeDataTable.R

eg: `exSciPen <- getOption("scipen")` instead of `exSciPen <- options("scipen")`

Your present code returns a list of length one instead of a numeric. With each call of one of the above functions, this list is growing and openxlsx crashes at some point. Thanks for your package - it's really great!

**Comment by awalker89** [comment]
Thanks for picking this up. Change made.
