### ISSUE TITLE
convertToDateTime

### ISSUE THREAD

**Issue by GeeSharpMinor** [awalker89/openxlsx#59]
For the convertToDateTime function, can the behavior for dealing with a NaN or NA in a list of Excel date time numeric values be to give back an NA instead of halting the entire conversion?  I currently get this as an error if there are NaN values in a list of dates:

Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format

Thanks!

**Comment by awalker89** [comment]
Fixed.
