### ISSUE TITLE
Reading error if there is content above the data

### ISSUE THREAD

**Issue by christophsax** [awalker89/openxlsx#60]
A weird bug that appeares when reading a limited group of columns from a row > 1. **If there is content above the data, colnames and data are messed up.**

### Creating a minimal example
    library(openxlsx)
    wb <- createWorkbook()

    # adding 4 sheets (would be nice if this could be vectorized)
    addWorksheet(wb, "first")
    addWorksheet(wb, "third0")
    addWorksheet(wb, "third1")
    addWorksheet(wb, "third2")

    ## Need data on worksheet to see all headers and footers
    writeData(wb, sheet = 1, CO2)
    writeData(wb, sheet = 2, startRow = 3, CO2)
    writeData(wb, sheet = 3, startRow = 3, CO2)
    writeData(wb, sheet = 4, startRow = 3, CO2)

    writeData(wb, sheet = 3, startRow = 1, "lineoftext")
    writeData(wb, sheet = 4, startRow = 1, c("lineoftext", "anotherlineoftext"))

    ## Save workbook
    saveWorkbook(wb, "min.xlsx", overwrite = TRUE)

The file `min.xlsx` contains four versions of identical data:

- in sheet 'first', the data is on the first row
- in sheet 'third0', the data is on the first row, with 0 lines of content above the data
- in sheet 'third1', the data is on the first row, with 1 line of content above the data
- in sheet 'third2', the data is on the first row, with 2 line of text in the second row.

### Replicating the bug

Reading data from sheet 'third1' and 'third2' leads to wrong colnames and data in the following calls:

    read.xlsx("min.xlsx", sheet = "third1", startRow = 3, cols = 1:2)
    #    Plant  1
    # 1    Qn1  6
    # 2    Qn1  6

    read.xlsx("min.xlsx", sheet = "third2", startRow = 3, cols = 1:2)
    # Error in stringInds[[1]] : subscript out of bounds

However, reading all columns work as expected

    read.xlsx("min.xlsx", sheet = "third1", startRow = 3, cols = 1:5)
    read.xlsx("min.xlsx", sheet = "third2", startRow = 3, cols = 1:5)
    #    Plant        Type  Treatment conc uptake
    # 1    Qn1      Quebec nonchilled   95   16.0
    # 2    Qn1      Quebec nonchilled  175   30.4

Also, reading from the first sheet works fine

    read.xlsx("min.xlsx", sheet = "first", startRow = 1, cols = 1:2)
    #    Plant        Type
    # 1    Qn1      Quebec
    # 2    Qn1      Quebec

**Comment by christophsax** [comment]
Just saw that the cols arg is only part of the dev version. So maybe you can forget about it.

**Comment by awalker89** [comment]
Thanks for reporting this and thank you very much for the minimal example. This should be fixed now. Please update with 
```
devtools::install_github("awalker89/openxlsx")
```

**Comment by christophsax** [comment]
works like a charm! Thanks for the great package!
