### ISSUE TITLE
Read xlsx file containing Chinese character using `read.xlsx` shows error message

### ISSUE THREAD

**Issue by eolembrain-leo** [awalker89/openxlsx#62]
Hi! I'm working with data including Chinese multibyte string.
When using read.xlsx, if there's "any" Chinese character in any place(even in the sheet which not to be read), it will cause error as below

    # Error in tolower(sharedStrings) : invalid multibyte string 414
or

     # Error in tolower(sharedStrings) : invalid multibyte string 2

**Comment by awalker89** [comment]
Hi, are you using the most up to date dev version?

**Comment by eolembrain-leo** [comment]
Thanks for the reply!
Both the latest dev version 2.2.1 or stable CRAN version turned out to be the same result.
Here's the sample data:
https://drive.google.com/file/d/0B8FLxb6Zof5uajh0b2hQVFBJZWM/view?usp=sharing

**Comment by awalker89** [comment]
The latest dev version is 2.3.10
Please run 
```
devtools::install_github("awalker89/openxlsx")
```
![image](https://cloud.githubusercontent.com/assets/7400673/6155997/663881bc-b28a-11e4-9ac5-7c0dadc8ce84.png)


Please send me your sessionInfo() if this doesnt work for you.

**Comment by eolembrain-leo** [comment]
After update to the dev version 2.3.11 it works.
Thanks a lot for the help and the development of such an efficient r package!

**Comment by awalker89** [comment]
Good to hear.

**Comment by eolembrain-leo** [comment]
Another issue with Chinese "sheet names"by `openxlsx` ver 2.4.0:

  Error in substring(u, so, so + ml - 1L) : 
    invalid multibyte string at '<96><87><22><20>sheetId="2" r:id="rId2"/><sheet name="33" sheetId="3"r:id="rId3"/></sheets><calcPr calcId="125725"/></workbook>'

sample xlsx file
https://drive.google.com/open?id=0B8FLxb6Zof5ucnVjZE9BNDdjNjQ&authuser=0

Thanks for following up!

**Comment by awalker89** [comment]
Works for me
![image](https://cloud.githubusercontent.com/assets/7400673/6798280/a43e523a-d25f-11e4-9230-9195dd954b28.png)


please update with
```
devtools::install_github("awalker89/openxlsx")
```
and send me the code you are using to produce the error.  Thanks.

**Comment by eolembrain-leo** [comment]
Thanks for working on this.
I still got errors as below:

![default](https://cloud.githubusercontent.com/assets/8746961/6798413/bb5392f4-d247-11e4-8aa2-684bd3222053.PNG)

![default](https://cloud.githubusercontent.com/assets/8746961/6798492/a64463a6-d248-11e4-8651-c0298681dc91.PNG)

    Session info -------------------------------------------------------------------------------
      setting  value                           
    version  R version 3.1.3 (2015-03-09)    
    system   x86_64, mingw32                 
    ui       RStudio (0.99.332)              
    language (EN)                            
    collate  Chinese (Traditional)_Taiwan.950
    tz       Asia/Taipei                     
    
    Packages -----------------------------------------------------------------------------------
      package    * version  date       source                             
    bitops     * 1.0-6    2013-08-17 CRAN (R 3.1.2)                     
    devtools     1.7.0    2015-01-17 CRAN (R 3.1.2)                     
    evaluate   * 0.5.5    2014-04-29 CRAN (R 3.1.2)                     
    formatR    * 1.0      2014-08-25 CRAN (R 3.1.3)                     
    httr       * 0.6.1    2015-01-01 CRAN (R 3.1.2)                     
    knitr      * 1.9      2015-01-20 CRAN (R 3.1.3)                     
    openxlsx   * 2.4.1    2015-03-24 Github (awalker89/openxlsx@d0b88ad)

**Comment by eolembrain-leo** [comment]
updated to `2.4.2`

`read.xlsx` works well!, 
but `loadWorkbook` still got error.

![default](https://cloud.githubusercontent.com/assets/8746961/6817821/2a043dea-d2e1-11e4-87ec-edc995c05ff5.PNG)

Thank you.

**Comment by Shicheng-Guo** [comment]
Still have the challenge to read Chinese characters. All the characters are as below:

data<-read.xlsx(".//R//CGM_SpeakerInfoRequest.xlsx",sheet = 1)


<U+5982><U+679C><U+8BF4><U+73B0><U+4EE3><U+4EBA><U+7C7B><U+7684><U+6F14><U+5316><U+662F><U+4E00><U+90E8><U+8F89><U+714C><U+7684><U+53F2><U+4E66>,<U+90A3><U+4E48><U+4E1C><U+5357><U+4E9A><U+5FC5><U+5B9A><U+662F><U+5176><U+4E2D><U+4E0D><U+53EF><U+6216><U+7F3A><U+7684><U+91CD><U+8981><U+7BC7><U+7AE0><U+3002><U+4E1C><U+5357><U+4E9A><U+5730><U+5904><U+8FDE><U+7ED3><U+4E9A><U+6D32><U+548C><U+5927><U+6D0B><U+6D32><U+3001><U+5370><U+5EA6><U+6D0B><U+548C><U+592A><U+5E73><U+6D0B><U+7684><U+4EA4><U+901A><U+8981><U+9053>,<U+4E14><U+4EBA><U+53E3><U+7A20><U+5BC6>,<U+805A><U+96C6><U+4E86><U+4E16><U+754C><U+4E0A><U+73B0><U+5B58><U+7684><U+5927><U+591A><U+6570><U+539F><U+4F4F><U+6C11><U+65CF><U+7FA4><U+3002><U+8FD1><U+5E74><U+6765>,<U+4EE5><U+4E1C><U+5357><U+4E9A><U+4E3A><U+4E2D><U+5FC3><U+5E7F><U+6CDB><U+5206><U+5E03><U+7684><U+4E9A><U+6D32><U+70ED><U+5E26><U+539F><U+4F4F><U+6C11><U+65CF><U+7FA4><U+9010><U+6E10><U+5F15><U+8D77><U+4E86><U+4EBA><U+7C7B><U+5B66><U+3001><U+9057><U+4F20><U+5B66><U+3001><U+8003><U+53E4><U+5B66><U+7B49><U+9886><U+57DF><U+5B66><U+8005><U+7684><U+91CD><U+89C6>,<U+6210><U+4E3A><U+7814><U+7A76><U+73B0><U+4EE3><U+4EBA><U+7C7B><U+8DE8><U+65F6><U+7A7A><U+8FC1><U+5F99><U+3001><U+878D><U+5408><U+5E76><U+4E0D><U+65AD><U+9002><U+5E94><U+65B0><U+73AF><U+5883><U+7684><U+590D><U+6742><U+8FC7><U+7A0B><U+7684><U+91CD><U+8981><U+7A81><U+7834><U+53E3><U+3002>
