### ISSUE TITLE
Formulas in cells

### ISSUE THREAD

**Issue by Dasonk** [awalker89/openxlsx#63]
Is there a way/plan to implement creating formulas in the output file?  Right now my workaround is basically to write the formula out as characters something like

    rows <- seq(2, nrow(mydat)+1)
    myform <- paste0("\'=A", rows, " + 3")

(that's just an example) and then do a find/replace of '= with = which activates the formulas.  It would be much nicer if I could export formulas directly without having to do this workaround of the find/replace.  Am I missing this feature or does it not exist? If it doesn't exist is there any plan to implement it?

**Comment by awalker89** [comment]
This feature doesn't exist yet...

**Comment by vathymut** [comment]
This could be very useful -- it reduces the need to populate formulas by clicking-on-cell-and-dragging.

**Comment by awalker89** [comment]
bce4b4c081184afd528c39ae60c4de4aa9210a4d adds formula functionality.
see example for
```
?writeFormula

```

**Comment by vathymut** [comment]
Thank you.
