### ISSUE TITLE
write.xlsx generates a corrupt file when passed a dplyr::tbl_df argument with numeric columns

### ISSUE THREAD

**Issue by richierocks** [awalker89/openxlsx#64]
To reproduce:

    df <- data.frame(x = rnorm(10))
    write.xlsx(df, "df.xlsx")   # OK
    
    library(dplyr)
    tdf <- tbl_df(df)
    write.xlsx(tdf, "tdf.xlsx")

Opening `tdf.xlsx` in Excel 2010 gives me the error

    Excel found unreadable content in 'tdf.xlsx'.  Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.

Upon clicking Yes, I get

    Excel was able to open the file by repairing or removing the unreadable content.

In the repaired file, cell A1 contains the value 'x', as expected, but each of the cells A2:A11 contains R code for storing the whole vector, for example

    c(-2.02839019415442, -0.296757189253924, -0.93179349084483, -0.42582548909149, 1.33388224662742, 0.0213879740776284, 0.876084172352498, -1.51198388736827, 0.738358381275667, 0.663821622219774)

Where the `tbl_df` contains multiple numeric problems, they all have bad content.  Character and integer columns seem OK; I haven't tested other types.

**Comment by richierocks** [comment]
This isn't the missing `[Content_Types].xml` problem mentioned in [Issue 22](https://github.com/awalker89/openxlsx/issues/22).

![openxlsx_issue64_unzipped](https://cloud.githubusercontent.com/assets/197589/6212931/76b4169a-b5fb-11e4-9209-d563a006e2d0.PNG)

**Comment by richierocks** [comment]
Here's the recovery log, though it isn't very exciting.

![openxlsx_issue64_recovery_log](https://cloud.githubusercontent.com/assets/197589/6212979/f7deb298-b5fb-11e4-8bd2-8aa86980425e.PNG)

**Comment by awalker89** [comment]
Thanks for the example - this is fixed now.
