### ISSUE TITLE
  write.xlsx generates a corrupt file when worksheet names have more than 31 chars

### ISSUE THREAD

**Issue by richierocks** [awalker89/openxlsx#65]
To reproduce:

    l <- list(abcdefghijklmnopqrstuvwxyzABCDEF = data.frame(x = rnorm(10)))
    write.xlsx(l, "l.xlsx")

Excel will repair the file by cropping the worksheet name to its first 31 chars.

**Comment by awalker89** [comment]
Thanks again. Fixed now.
