### ISSUE TITLE
Multiple spaces are reduced to a single space

### ISSUE THREAD

**Issue by christophsax** [awalker89/openxlsx#67]
If you have more than one space in an excel file, they are reduced to a singe space.
Here's a reproducible example:

    library(openxlsx)
    dstr <- c("single spaces", "double  spaces", "tripple   spaces")
    write.xlsx(dstr, file = "test.xlsx")  # file looks good
    read.xlsx("test.xlsx", colNames = F) 
    ##               X1
    ## 1  single spaces
    ## 2  double spaces
    ## 3 tripple spaces

**Comment by awalker89** [comment]
I will fix this asap. you can use keepNewLine = TRUE as a temporary workaround.


Some notes for myself:

 - loadWorkbook and saving maintains newlines as newlines are capture in wrapText styling.
 - read.xlsx.Workbook drops new lines but maintains multiple spaces (uses readLines)
 - read.xlsx.default drops all whitespace and concatenates using space (c++ read file)
 - read.xlsx.default, keepNewLines = TRUE maintains all whitespace & newlines.


TODO
 - modify loadWorkbook to maintain newline characters for when reading from workbook object
 - set keepNewLines = TRUE code as default (re-write this)
 - remove keepNewLines parameter from read.xlsx. Should only read exactly what is there.

**Comment by ProfFancyPants** [comment]
I just had this happen to me when saving long file paths to an excel spreadsheet. Was this resolved, or is the workaround still necessary?
