### ISSUE TITLE
read.xlsx/loadWorkbook Error: not compatible with requested type if space in title

### ISSUE THREAD

**Issue by fpbarthel** [awalker89/openxlsx#68]
Hi,

Both of these functions return the error "Error: not compatible with requested type" if the filename I'm trying to open has spaces in it. Removing the spaces in the filename fixes the issue.

Thanks,
Floris

**Comment by awalker89** [comment]
![image](https://cloud.githubusercontent.com/assets/7400673/6390843/f843b066-be03-11e4-8df9-0ce49d347c7d.png)

seems to work....
Please post a reproducible example.
