### ISSUE TITLE
rotate to vertical orientation

### ISSUE THREAD

**Issue by tanakahiroaki** [awalker89/openxlsx#72]
Hi! I want to new cellstyle option.
set Cell.Orientation = xlVertical in VBA makes the orientation vertical, but it is impossible by using the function "createStyle" of the openxlsx. I wish the new choice of the augument of textRotation.
Thanks!

**Comment by awalker89** [comment]
textRotation = 255 seems to do it. I'll add a more obvious parameter value in the future

![image](https://cloud.githubusercontent.com/assets/7400673/6503330/e6c93f82-c37f-11e4-99c0-02e00ac73902.png)

**Comment by tanakahiroaki** [comment]
Thanks sooooooooooooo much!!!!!!!!!
