### ISSUE TITLE
issue with rtools after re-installation of openxlsx

### ISSUE THREAD

**Issue by fpbarthel** [awalker89/openxlsx#76]
Hey, I re-installed openxlsx but now saving worksheets doesn't work any more:

> saveWorkbook(wb, fn, overwrite = TRUE)
Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows.
> installr::install.rtools()
No need to install Rtools - You've got the relevant version of Rtools installed
> saveWorkbook(wb, fn, overwrite = TRUE)
Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows.

Thanks

**Comment by fpbarthel** [comment]
re-installation of rtools fixed this, but only after clearing the windows registry of entries related to rtools

**Comment by awalker89** [comment]
That's very odd... openxlsx uses the zip application supplied by RTools and this code hasnt changed since the very beginning so no idea why this would stop working. Glad it's working for you now.

**Comment by RomanBi** [comment]
I am having exactly the same problem as described in the first post, except for the fact that I installed openxlsx for the first time. Re-installation of rtools and clearing the windows registry did not help. I tried both CRAN and github version of openxlsx.

**Comment by mubashirqasim** [comment]
I am having the same error on Linux. Any way around?

**Comment by awalker89** [comment]
openxlsx simply calls the utils::zip() function to zip up workbooks. For this to work R needs to be able to find a zip. Have a look at ?utils::zip

**Comment by mubashirqasim** [comment]
utils::zip() function is working fine. But I am still getting the same error. Do I need to pass certain perimeters to write.xlsx function?

sh: 1: : Permission denied
Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows.

**Comment by tmamiya** [comment]
**For Linux users**
For those out there who are looking for Rtools in linux, you can use zip as an alternative.
1. install zip into linux
2. set your path (using command below) to that location for me it was /usr/bin/zip
Sys.setenv(R_ZIPCMD= "/usr/bin/zip")
