### ISSUE TITLE
reading from connection

### ISSUE THREAD

**Issue by ggrothendieck** [awalker89/openxlsx#80]
It would be useful if read.xlsx could read from a connection such as 

```
read.xlsx( url("http://somewebsite.com/abc.xlsx"))
```

or possibly even just 

```
read.xlsx("http://somewebsite.com/abc.xlsx")
```

Currently it seems one has to download the file and then read it in.

**Comment by awalker89** [comment]
I might add this in in the future. For now you can just do
```
u <- "http://www.vertex42.com/Files/exclusive/gantt-chart_o365_free.xlsx"
download.file(u, mode="wb", destfile = "download.xlsx")
read.xlsx("download.xlsx")
```

**Comment by ggrothendieck** [comment]
That is what I was doing. I was hoping not to have to do that.

**Comment by awalker89** [comment]
It took 18 months but it's done dd2893f6947992ab3133c370783f2c77838181a3!

**Comment by awalker89** [comment]
```
df <- read.xlsx("https://github.com/awalker89/openxlsx/raw/master/inst/readTest.xlsx")
head(df)
```
