### ISSUE TITLE
endRow parameter for read.xlsx

### ISSUE THREAD

**Issue by jasonpbecker** [awalker89/openxlsx#82]
It would be great to be able to specify an `endRow` in `read.xlsx` just like startRow, e.g.:

```read.xlsx(file, startRow=8, endRow = 15)```

It's especially useful when the source has multiple tables in the same sheet.

**Comment by awalker89** [comment]
Use rows and cols
```
read.xlsx(file, rows = 8:15, cols = c(1, 3, 5))
```
