### ISSUE TITLE
Write to existing xlsx file without altering formatting

### ISSUE THREAD

**Issue by joranE** [awalker89/openxlsx#83]
I'm thinking of something similar to **XLConnect**'s 

`setStyleAction(wb,XLC$"STYLE_ACTION.NONE")`

which is very useful when writing data to pre-formatted Excel templates. I've been looking, but I can't find anything similar to that in openxlsx. If it doesn't exist, it would be a feature I would bery much appreciate.

**Comment by awalker89** [comment]
Hi,
load the formatted workbook using loadWorkbook then write to it. Something like
```
wb <- loadWorkook(...)
writeData(wb, sheet = 1, ...)
```
If you are losing any formatting please send me an example xlsx file and script.

**Comment by joranE** [comment]
Aha! I think I was used to the XLConnect idiom of having to call `saveWorkbook` to have any changes come into effect! So I was doing that with `overwrite = TRUE` after calling `writeData`. Omitting that step solved it. Sorry for the noise, and thanks for the quick help!

**Comment by joranE** [comment]
It actually looks like it might just be any existing borders that are being over-written. I sent you an email with a xlsx file and short script.

**Comment by awalker89** [comment]
Thanks for sending the xlsx file through. This is a bug. I will look in to it soon.

**Comment by awalker89** [comment]
Just a note
loadWorkbook "copies" the xlsx file into an R object. So anything you do will not affect the original file.  An actual file doesn't exist until saveWorkbook is called.
