### ISSUE TITLE
worksheets[[sheet]] Error

### ISSUE THREAD

**Issue by MinkyuKwon** [awalker89/openxlsx#85]
I read. xlsx files with openxlsx's read.xlsx function.
When I read some xlsx files with it, I have some error message " ~~ worksheets[[sheet]] ~~ "subscript out of bounds~~"

Please let me know how can I open this file with openxlsx's read.xlsx function.
Thank you.

**Comment by awalker89** [comment]
please update with devtools::install_github("awalker89/openxlsx")

**Comment by tlphillips** [comment]
When I installed the above, I got this error after running:
Error in .Call("openxlsx_getCellInfo", xmlFile = worksheet, sharedStrings = sharedStrings,  : 
  "openxlsx_getCellInfo" not available for .Call() for package "openxlsx"

I noted that I got a permissions denied on overwriting the openxlsx.dll during install

**Comment by awalker89** [comment]
Close and reopen R, then update.

**Comment by awalker89** [comment]
This is now fixed.
