### ISSUE TITLE
writeWorksheetToFile

### ISSUE THREAD

**Issue by Stefan2015-5** [awalker89/openxlsx#88]
It would be an even greater package if it would allow to add data to an existing xlsx instead of overwriting the file. 
The function writeWorksheetToFile in package XLconnect provides for that (but comes with the disadvantage of relying on Java).

Thanks so much for the work done!!
Stefan

**Comment by awalker89** [comment]
You can do something like
```
wb <- loadWorkbook(...) # load an existing xlsx file into R
addWorksheet(wb, "New Sheet") # add a new worksheet.
writeData(wb, sheet = "New Sheet",  ...) ## write data.frame to new sheet
saveWorkbook(wb, ...) # save over existing file or elsewhere.
```

**Comment by Stefan2015-5** [comment]
Great, thanks
