### ISSUE TITLE
Create Cell Comments

### ISSUE THREAD

**Issue by omarbenites** [awalker89/openxlsx#91]
Hello awalker89, I wonder If  there is any function to create cell comments like "xlsx" package

For instance:

Functions to manipulate cell comments.
createCellComment(cell, string="", author=NULL, visible=TRUE)
getCellComment(cell)
removeCellComment(cell)

Regards

**Comment by awalker89** [comment]
49e2bce34dfd97112b06da14d2a6ff23425056c2 adds comment functionality

See
```
?createComment
?writeComment
?removeComment

```

Yet to write, getComment

**Comment by omarbenites** [comment]
Thanks so much!!
