### ISSUE TITLE
Feature Request: Read named region

### ISSUE THREAD

**Issue by fleimgruber** [awalker89/openxlsx#93]
I would like to swap `XLConnect` for `openxlsx`. Now there is `XLConnect::readNamedRegion` for which there is no `openxlsx` equivalent yet, AFAICS. In #23 I found `writeDataTable` and the `tableName` argument. Is the reading of named regions already there? Maybe just undocumented?

**Comment by awalker89** [comment]
This feature does not yet exist. I'll add it to the TODO list.

**Comment by fleimgruber** [comment]
Thanks for the fast implementation, feature works when testing manually. I want to contribute an automated test, but could not find a `writeNamedRegion` (`writeDataTable` did not work for me).
