### ISSUE TITLE
vcf validator tool

### ISSUE THREAD

**Issue by dwaggott** [awalker89/openxlsx#98]
Hey,

I've got another corrupt vcf. Do you have a vcf validator script that helps figure out where the issues are? The repair log from excel is not helpful.

Thanks

**Comment by awalker89** [comment]
No sorry I don't have any such tool. I generally use "Check XML Syntax" from the XML plugin in notepad++. I'm always interested to see corrupt xlsx files see please email them to me if you are having issues and don't contrain any confidential data.
